### ISSUE TITLE
Merge master into development for all websites

### ISSUE THREAD

**Issue by Vilnite** [threefoldfoundation/www_threefold_io#102]
Update staging and production for all.

- [x] threefold_io
- [x] farming
- [x] digitaltwin
- [x] cloud
- [x] marketplace
- [x] aci
- [x] tf tech
- [x] freeflow
- [x] examplesite

**Comment by hossnys** [comment]
why this action is needed as the last commit on master branch on all sites is since 4 months ?!!

**Comment by ramezsaeed** [comment]
@Vilnite this is a very dangerouse step,
i recommend this should be done by repo owners as they know the latest status content.
and the merge will need a lot of content decisions.
