### ISSUE TITLE
Create a Careers Page

### ISSUE THREAD

**Issue by Vilnite** [threefoldfoundation/www_threefold_io#103]
We are very low on hands to build the future Internet.
To support hiring process and allow people to easily learn about available positions and apply we need **Join Us** page on our website.

Functions:
- [x] gives links to available roles in the company as well as the ones opening soon..
- [x] gives a link to application form that gathers all the information about applicant

See Holo Join Us page for an example: https://holo.host/join/

Application form: https://06gdrqp39yz.typeform.com/to/FffDv61M

**Comment by Vilnite** [comment]
Need promo teams review and approval to go live.

**Comment by Sacha96** [comment]
<img width="1315" alt="Screenshot 2021-07-23 at 12 45 32" src="https://user-images.githubusercontent.com/54844940/126765136-81e2bd10-b83e-4233-b2fc-f3c64842059c.png">

can we make this more appealing like in holo example?

**Comment by Sacha96** [comment]
Also would suggest to create a join the community page to guide to telegram groups and then recruit like holo did - really nice

**Comment by Sacha96** [comment]
please check linkedIn and other recruitment pages to improve structure

**Comment by Sacha96** [comment]
i'm pushing review on everything but not recruitment structure

**Comment by Vilnite** [comment]
Tweaks on development side to be finalised on Sunday.
