### ISSUE TITLE
Fix filter tags 

### ISSUE THREAD

**Issue by Vilnite** [threefoldfoundation/www_threefold_io#105]
- [x] There are underscores left on filter tags, please remove.
- [x] Check across all websites

<img width="1428" alt="Screenshot 2021-07-21 at 15 28 48" src="https://user-images.githubusercontent.com/20182572/126488632-ee67cf5a-3e7b-49a2-8ee0-0864af44bbef.png">

**Comment by ehab-hassan** [comment]
I found that blog/news/people at (farming , cloud) linked external to threefold.io blog and news and people at navbar!!!
Is that right or should linked to its blogs/news ......??

**Comment by Vilnite** [comment]
Let's leave it linking to threefold_io for now, yes. Not ready to separate content between sites just yet.
