### ISSUE TITLE
Support colon in blog titles

### ISSUE THREAD

**Issue by scottyeager** [threefoldfoundation/www_threefold_io#107]
Currently, the website fails to build if a colon is used in the title of a blog post, such as:

`title: Building a New Internet From the Ground Up - Part 2: Storage`

I guess that using the colon to delineate key/value here creates a parsing issue. Is it possible to improve the parsing logic to allow for using colons within blog titles?

**Comment by Vilnite** [comment]
If fix is applied please do so for News as well.

**Comment by samaradel** [comment]
![image](https://user-images.githubusercontent.com/11662805/127771130-cbc8b543-39e6-466b-94c4-5246fd33ea47.png)

**Comment by scottyeager** [comment]
Ah, good to know! Thanks @samaradel 🙏🏻
