### ISSUE TITLE
TF_IO - add token block

### ISSUE THREAD

**Issue by Sacha96** [threefoldfoundation/www_threefold_io#11]
The only mention of the token for now is in the CTA at end of page. 

Need a section for token that incentivises people to purchase TFT.

Ex:

Join the P2P Economy 

TFT fuels the ThreeFold Ecosystem and represents a unit of compute and storage capacity on the ThreeFold Grid. Get your TFT now to start your journey on the new Internet. 

QUICK BUY / HOW TO GET TFT

**Comment by Vilnite** [comment]
Suggesting to add one more card like this for TFT that leads to: https://farming.threefold.io/token

<img width="1124" alt="Screenshot 2021-02-16 at 08 16 30" src="https://user-images.githubusercontent.com/20182572/108025554-59f60000-702f-11eb-93c4-00ca26d5193b.png">

**Comment by Vilnite** [comment]
Keep it clean. Keep it simple. Reuse.

**Comment by Sacha96** [comment]
well i think the token is the fuel of the whole ecosystem, showing that gives actually mofe value to the token too, so i'd create a seperate block for it.

**Comment by samtaggart** [comment]
@Vilnite 

Let's please try this as a header component with image. Let's try it beneath Cyber Pandemic / ACI & above The world needs a new internet.

**Title**
Join the P2P Economy

**Image**
![token_header 81a2a12 16c10d0611d2375d71c9c67ab061daf9](https://user-images.githubusercontent.com/50134479/108857425-be96f900-75f3-11eb-9a35-479947e733ef.png)

**Text**
TFT fuels the ThreeFold ecosystem and represents a unit of compute and storage capacity on the ThreeFold Grid. Get your TFT now to start your journey on the new Internet.

**Buttons**
Quick Buy >>> https://www.liquid.com/quick-exchange/
More About TFT >>> https://farming.threefold.io/token
