### ISSUE TITLE
A block for careers page

### ISSUE THREAD

**Issue by Vilnite** [threefoldfoundation/www_threefold_io#110]
Need to create a full with image with a text or button top of it that's clickable (with a link) on the bottom of Careers page.
Just like in Holo example:

<img width="1428" alt="Screenshot 2021-07-29 at 11 02 56" src="https://user-images.githubusercontent.com/20182572/127455068-d783975a-ad91-4a9f-9d37-df42f953c724.png">

https://holo.host/careers/compliance-regulatory-and-legal-manager/

**Comment by Vilnite** [comment]
Looks great so far :))))

<img width="1416" alt="Screenshot 2021-07-30 at 11 00 46" src="https://user-images.githubusercontent.com/20182572/127621316-0e663993-b546-4c07-8c1c-f0efc3095ff2.png">


- [ ] Let's make sure it shows on careers page itself as well (on the bottom)
- [ ] Links to /community page
- [ ] I've added on community dir with content including customCTA_2 that we need to make work on the bottom of Community page, linking back to /careers page


Thank you :)

**Comment by Sacha96** [comment]
@samtaggart @Karoline888 @VonSub please propose some pictures here
