### ISSUE TITLE
Activate emails

### ISSUE THREAD

**Issue by Vilnite** [threefoldfoundation/www_threefold_io#113]
Can we please make sure all these emails are created / activated so that when we push the support page emails are accessible?

<img width="1438" alt="Screenshot 2021-07-30 at 14 11 16" src="https://user-images.githubusercontent.com/20182572/127644845-69f58427-a86a-483e-8a9a-931d1b0fbbbe.png">

**Comment by PeterNashaat** [comment]
- press@threefold.io and listing@threefold.io , are already created groups.
  - press@threefold.io has 2 users (Maximilian, Sam)
  -  listing@threefold.io has 2 users (Oussama benjelloun, Nickolay Babenko)

- partners@threefold.io and 3node@threefold.io are not created

**Comment by Vilnite** [comment]
Can you please create partners@threefold.io and 3node@threefold.io ?
For partners@threefold.io add @AlexandreHannelas 
For 3node@threefold.io add @andhartl

**Comment by PeterNashaat** [comment]
Both groups created with the requested users

**Comment by Vilnite** [comment]
@PeterNashaat can you please add also @VonSub to 3node@threefold.io?

**Comment by PeterNashaat** [comment]
Added Roel to 3node@threefold.io

**Comment by Vilnite** [comment]
Another ask, can @sasha-astiadi be added to info@threefold.io she will need access to email (pw) to set up a GitHub support account.
You can reach out to her directly with access details.

**Comment by PeterNashaat** [comment]
Added sasha to the group and access to receive emails going to info@threefold.io

**Comment by Vilnite** [comment]
Thank you @PeterNashaat, we can now finally close this :)
