### ISSUE TITLE
crisp widget is down - no live chat

### ISSUE THREAD

**Issue by Sacha96** [threefoldfoundation/www_threefold_io#115]

**Comment by ehab-hassan** [comment]
works for me and checked with support they got my massage
![ThreeFold-Welcome](https://user-images.githubusercontent.com/10484295/127773868-2769832e-6706-4c9c-93f2-37cc02191632.png)

**Comment by Vilnite** [comment]
Works for me as well.

**Comment by Sacha96** [comment]
ok seems like its back indeed. thanks
