### ISSUE TITLE
Support & Careers page feedback

### ISSUE THREAD

**Issue by Vilnite** [threefoldfoundation/www_threefold_io#117]
Please provide feedback preferably with tick boxes (- [ ] ....) and printscreens where needed in comments. 

Thank you.

**Comment by maximilianrang** [comment]
"Join us" could be mistaken by a "join the movement" type of action. I would propose to name the section "careers".

**Comment by sabrinasadik** [comment]
- [ ] Add live chat information on the support page

**Comment by Sacha96** [comment]
Text is redundant between team and community...

Proposed text for community:

Join our community 
The new Internet is powered by people like **you**

The ThreeFold ecosystem is a global community of developers, creators, leaders and community builders who together join forces to build an open, autonomous and regenerative Internet. We believe that everyone should own their data, and no one else, not even ThreeFold. Our Peer-to-Peer technology allows every user to be autonomous -  giving them 100% control over their data. 

ThreeFold unifies practices, partnerships, and products around a single mission - to heal our planet. By making our technology actionable, we enable a collective approach to have an impact together. We help people find themselves and do what they love. We provide support to people and projects that help build a better world, whether they have moonshot visions or down-to-earth ambitions. We aren’t the hero of our story - they are.   

Join our community and help us build the next Internet.

**Comment by Vilnite** [comment]
> * [ ]  Add live chat information on the support page

Does this work?

<img width="1403" alt="Screenshot 2021-08-02 at 17 03 19" src="https://user-images.githubusercontent.com/20182572/127874163-c8b3497e-0c63-4757-9408-fbca01b48d02.png">

**Comment by Vilnite** [comment]
> Text is redundant between team and community...
> 
> Proposed text for community:
> 
> Join our community
> The new Internet is powered by people like **you**
> 
> The ThreeFold ecosystem is a global community of developers, creators, leaders and community builders who together join forces to build an open, autonomous and regenerative Internet. We believe that everyone should own their data, and no one else, not even ThreeFold. Our Peer-to-Peer technology allows every user to be autonomous -  giving them 100% control over their data. 
> 
> ThreeFold unifies practices, partnerships, and products around a single mission - to heal our planet. By making our technology actionable, we enable a collective approach to have an impact together. We help people find themselves and do what they love. We provide support to people and projects that help build a better world, whether they have moonshot visions or down-to-earth ambitions. We aren’t the hero of our story - they are.  
> 
> Join our community and help us build the next Internet.

- [ ] works?

<img width="1418" alt="Screenshot 2021-08-02 at 17 08 35" src="https://user-images.githubusercontent.com/20182572/127874807-f4333abc-4727-4a88-b7de-a2668cafbbc5.png">

**Comment by Sacha96** [comment]
> > Text is redundant between team and community...
> > Proposed text for community:
> > Join our community
> > The new Internet is powered by people like **you**
> > The ThreeFold ecosystem is a global community of developers, creators, leaders and community builders who together join forces to build an open, autonomous and regenerative Internet. We believe that everyone should own their data, and no one else, not even ThreeFold. Our Peer-to-Peer technology allows every user to be autonomous -  giving them 100% control over their data. 
> > ThreeFold unifies practices, partnerships, and products around a single mission - to heal our planet. By making our technology actionable, we enable a collective approach to have an impact together. We help people find themselves and do what they love. We provide support to people and projects that help build a better world, whether they have moonshot visions or down-to-earth ambitions. We aren’t the hero of our story - they are.  
> > Join our community and help us build the next Internet.
> 
> * [ ]  works?
> 
> <img alt="Screenshot 2021-08-02 at 17 08 35" width="1418" src="https://user-images.githubusercontent.com/20182572/127874807-f4333abc-4727-4a88-b7de-a2668cafbbc5.png">

missing The before ThreeFold ecosystem in first paragraph

**Comment by Sacha96** [comment]
For support page:

Change title to > Find the answers to your questions

For FAQ title-  Did you try our FAQ yet?
subtitle - ThreeFold's FAQs bring together the most essential answers to the most common questions. You might already find what you're looking for in one of them.

For Forum title - Find popular topics on the ThreeFold Forum
image (crop to remove categories, latest, top...

**Comment by samtaggart** [comment]
<img width="324" alt="Screen Shot 2021-08-02 at 5 25 04 PM" src="https://user-images.githubusercontent.com/50134479/127877099-0cdeb6aa-f3a6-452a-9bf2-fc8d6373b343.png">

- [ ] Find all the information you need in order to understand what ThreeFold Farming is and how to set up your farm.

**Comment by samtaggart** [comment]
<img width="905" alt="Screen Shot 2021-08-02 at 5 27 23 PM" src="https://user-images.githubusercontent.com/50134479/127877411-a6764a5b-c5a1-4846-99b6-055ff6021dc3.png">

- [ ] I believe these buttons should open in a new tab

**Comment by samtaggart** [comment]
<img width="241" alt="Screen Shot 2021-08-02 at 5 29 08 PM" src="https://user-images.githubusercontent.com/50134479/127877657-869ee05e-8894-4e40-acaa-8c631793c0f4.png">

- [ ] I think we can just say "You will be working on growing and creating business models on the ThreeFold Grid."

**Comment by samtaggart** [comment]
<img width="238" alt="Screen Shot 2021-08-02 at 5 30 13 PM" src="https://user-images.githubusercontent.com/50134479/127877804-36a08bc6-be0a-45ba-8d81-e2ebd47f58ef.png">

- [ ] The second digital twin should be Digital Twin

**Comment by samtaggart** [comment]
<img width="242" alt="Screen Shot 2021-08-02 at 5 30 57 PM" src="https://user-images.githubusercontent.com/50134479/127877896-32c0de4e-e238-4858-ac58-e1c794288f01.png">

- [ ] Dital Twin >>> Digital Twin

**Comment by samtaggart** [comment]
<img width="1069" alt="Screen Shot 2021-08-02 at 5 32 37 PM" src="https://user-images.githubusercontent.com/50134479/127878106-d2967d71-3b81-49ff-9409-433bb547077a.png">

- [ ] All of the job descriptions start with "The ThreeFold" but "The" needs to be removed

**Comment by samtaggart** [comment]
<img width="1059" alt="Screen Shot 2021-08-02 at 5 33 42 PM" src="https://user-images.githubusercontent.com/50134479/127878233-80d0ee48-ac3b-4be0-b2d4-c8370e2827d1.png">

- [ ] In Senior Developer role Introduction, it says "Dital Twin"

**Comment by samtaggart** [comment]
<img width="526" alt="Screen Shot 2021-08-02 at 5 34 38 PM" src="https://user-images.githubusercontent.com/50134479/127878418-f7c9da33-52ac-4cdf-8fce-09c63adb4929.png">

- [ ] In all of the job descriptions in What we offer it says "teamspirit" but it should be "team spirit"

**Comment by sabrinasadik** [comment]
> > * [x]   Add live chat information on the support page
> 
> * [ ]  works?
> 
> <img alt="Screenshot 2021-08-02 at 17 03 19" width="1403" src="https://user-images.githubusercontent.com/20182572/127874163-c8b3497e-0c63-4757-9408-fbca01b48d02.png">

Typo: emergency
Regardless, I wouldn't use 'emergency' because users might be under the impression that their issue will be resolved in 5min. 

I would rather say something like: For questions/assistance, please use the chat function on the bottom right corner of our website or under 'Support' in the ThreeFold Connect app.

**Comment by Sacha96** [comment]
> <img alt="Screen Shot 2021-08-02 at 5 25 04 PM" width="324" src="https://user-images.githubusercontent.com/50134479/127877099-0cdeb6aa-f3a6-452a-9bf2-fc8d6373b343.png">
> 
> * [x]  Find all the information you need in order to understand what ThreeFold Farming is and how to set up your farm.

Also we need a 3Node picture that aligns with rest of web presence!
