### ISSUE TITLE
TF_IO - MENU + FOOTER set-up

### ISSUE THREAD

**Issue by Sacha96** [threefoldfoundation/www_threefold_io#12]
Need Menu + Footer that leads to all important parts of ThreeFold Ecosystem

**MENU**

1. Logo (Home)

2. Products

<dropdown>

i. Be the Internet >>> https://new.threefold.io/farming

ii. Peer2Peer Cloud >>> https://new.threefold.io/cloud

iii. Peer2Peer Marketplace >>> https://new.threefold.io/marketplace

iv. Digital Twin >>> https://new.threefold.io/twin

v. Token >>> https://new.threefold.io/farming/token

3. Learn

<dropdown>

i. Knowledge Base >>> https://new.threefold.io/info/threefold

ii. Blog >>> https://new.threefold.io/blog

iii. Forum >>> https://forum.threefold.io

3. Ecosystem

dropdown

i. Team >>> https://new.threefold.io/team

ii. Partners >>> https://new.threefold.io/partners

iii. Conscious Internet >>> https://new.threefold.io/aci

iv. ThreeFold Tech >>> https://threefold.tech

4. More

i. Community >>> Telelgram Channel (https://t.me/threefoldnews)

ii. Newsroom >>> new.threefold.io/news

iii. Contact >>> info@threefold.io

FOOTER

1. Participate 

i. Get TFT >>> https://new.threefold.io/info/threefold#/threefold__how_to_buy_and_sell

ii. Store TFT >>> https://new.threefold.io/info/threefold#/threefold__storing_tft

iii. Be the Internet >>> new.threefold.io/farming

iv. Peer2Peer Cloud >>> new.threefold.io/cloud

v. Peer2Peer Marketplace >>> new.threefold.io/marketplace

vi. Digital Twin >>> new.threefold.io/twin

2. Learn

i. What is ThreeFold? >>> https://new.threefold.io/info/threefold

ii. What is TFT? >>> new.threefold.io/farming/token

iii. Knowledge Base >>> https://new.threefold.io/info/threefold#/

iv. Manuals >>> https://new.threefold.io/info/threefold#/tftech__tf_manuals?id=threefold-manuals

v. Foundation >>> https://new.threefold.io/info/threefold#/threefold__threefold_foundation

vi. ThreeFold Glossary >>> https://new.threefold.io/info/threefold#/threefold__defs

3. Developers 

i. Get Started >>> https://new.threefold.io/info/threefold#/tftech__tf_manuals?id=threefold-manuals

ii. SDK >>> https://new.threefold.io/info/sdk

iii. Peer2Peer Cloud >>> https://new.threefold.io/info/threefold#/tftech__manual_cloud

iv. Github >>> https://github.com/threefoldfoundation

4. Ecosystem

i. Community >>> Telelgram Channel (https://t.me/threefoldnews)

ii. Team >>>  new.threefold.io/team

iii. Partners >>>  new.threefold.io/partners

iv. Conscious Internet >>>  new.threefold.io/aci

v. ThreeFold Tech >>> https://threefold.tech/

5.  About

i. About >>> https://new.threefold.io/info/threefold#/

ii. Forum >>> https://forum.threefold.io

iii​​​​​​​​​​​​​​. Terms & Conditions >>> https://new.threefold.io/info/legal#/legal__terms_conditions_websites

iv. Privacy Policy >>> https://new.threefold.io/info/legal#/legal__privacypolicy

iv. Contact >>> info@threefold.io

**Comment by Vilnite** [comment]
@ehab-hassan 
I added all the content to footer.md and navigation.md

Please make both navbar and footer visible and if possible with green background to blend with large images on top and bottom.

**Comment by ehab-hassan** [comment]
I updated nav and footer but I found a lot of link not working it must be external link I fixed it but check it again when u free.
