### ISSUE TITLE
Please push threefold_data changes and push threefold.io to staging & production

### ISSUE THREAD

**Issue by samtaggart** [threefoldfoundation/www_threefold_io#120]
I added two newsroom items that need to make their way to production today.

- [x] Verify with Kristine we are OK to push (Sam)
- [x] Push to staging (Samir)
- [x] Verify content is good (Sam)
- [x] Push to production (Samir)

**Comment by hossnys** [comment]
https://staging.threefold.io updated now

**Comment by samtaggart** [comment]
We're good @hossnys can go to production

**Comment by hossnys** [comment]
production updated also https://threefold.io/news
