### ISSUE TITLE
Navbar fix on Safari

### ISSUE THREAD

**Issue by Vilnite** [threefoldfoundation/www_threefold_io#122]
I know we talked about this but its really bothersome how messed up navbar of our websites is on safari browser.
We need to fix it as many people do use safari and will see our websites as broken.

<img width="1434" alt="Screenshot 2021-08-05 at 12 18 19" src="https://user-images.githubusercontent.com/20182572/128326460-2ffeed68-e8c0-4ee3-b472-b1ff5b85c494.png">

**Comment by Vilnite** [comment]
Website was just released. Still same issue on safari:

<img width="1545" alt="Screenshot 2021-08-12 at 11 37 46" src="https://user-images.githubusercontent.com/20182572/129166058-9d3f2687-7fca-4dc5-9bad-904f7cb8ecf9.png">

**Comment by samaradel** [comment]
waiting till I can test it on mac
