### ISSUE TITLE
Telegram chat links are missing from the footer

### ISSUE THREAD

**Issue by nbabenko** [threefoldfoundation/www_threefold_io#124]
Is there any specific reason why telegram chat links is missing from the footer?
Can we add links to the news channel and a group chat to the footer?

<img width="302" alt="截屏2021-08-06 16 54 19" src="https://user-images.githubusercontent.com/4426772/128520976-af2764b0-63c2-4a35-a72f-b08a17dbcb10.png">

**Comment by nbabenko** [comment]
@Sacha96 @Vilnite what do you think?

**Comment by Vilnite** [comment]
News channel and Group chat is 2 different telegram links but telegram icon is the same.
In this view we can add only 1 telegram channel as more will be confusing.

**Comment by Vilnite** [comment]
@samaradel can you please add Telegram chat icon and link: https://t.me/threefold
in footer?

**Comment by Vilnite** [comment]
It links to ThreeFold News&Updates instead of ThreeFold main group.

@samtaggart you think that's fine or should we update link to ThreeFold main group instead?

**Comment by samtaggart** [comment]
I'd rather link people to the News & Updates group. Some people might be turned off by the two-way chat. Think it's more valuable they sign up for news and updates. And if they're looking for the main chat they can find it via the pinned message there.

But that's just my preference!
