### ISSUE TITLE
Update threefold.io to staging & production

### ISSUE THREAD

**Issue by samtaggart** [threefoldfoundation/www_threefold_io#126]
I made some updates to threefold_data, please merge them in and update threefold.io to staging and then to production.

**Comment by hossnys** [comment]
published to staging please review and comment here to go production 
https://staging.threefold.io/blog/post/artheon_blog_one/

**Comment by samtaggart** [comment]
Good to go! Thanks

**Comment by hossnys** [comment]
Done
