### ISSUE TITLE
Token Landing Page

### ISSUE THREAD

**Issue by Sacha96** [threefoldfoundation/www_threefold_io#128]
Please create a token landing page attached to threefold.io 

let's not replace current token page, instead we do a new one >> suggest: threefold.io/tft

https://xd.adobe.com/view/af614635-5f3d-4ef5-9221-b2f72765ea2e-fa32/screen/a85eccfa-1781-49d2-8788-eb2514862cd2?fullscreen

please try do it as close as possible to zia's mockup.

**Comment by Sacha96** [comment]
also don't do extra pages he did, i will comment on how we could make it in only one page, but get started with main page already

**Comment by Sacha96** [comment]
comment from kristine:

And just to clarify, it’s not a seperate website right? It’s a single page on threefold_io website?
For now brining on only what’s in mockup’s home page?

**Comment by Sacha96** [comment]
getting ai file from Zia. 

I wonder if we can have it under same domain but without current navbar?

**Comment by Vilnite** [comment]
As if threefold.io/marketplace or threefold.io/farming  being separate websites
if threefold.io/tft is a separate website (page) than it can have a different navbar or no navbar at all but then it also needs a separate repo and whole setup.

If it's supposed to be within current website (that's my question above) then it will have same navbar and footer as main website.

**Comment by Vilnite** [comment]
Please go with fastest and easiest way - a page on threefold_io for now and we will see from there.

**Comment by ehab-hassan** [comment]
Note :
While it ll be inside Threefold.io we ll use io style (font,color,button.....)

**Comment by Sacha96** [comment]
no please do page like designed by Zia @ehab-hassan

**Comment by ehab-hassan** [comment]
@Vilnite @Sacha96 for font and color Ok, what about container if we remove it ll face responsive issue we had before when it full page like ??
![tft_header](https://user-images.githubusercontent.com/10484295/129535463-e0b472cf-ed78-435f-9aca-77a3fb3d6544.png)

**Comment by Sacha96** [comment]
Ehab can't we try full page without side containers?

**Comment by ehab-hassan** [comment]
all page done .waiting for pick font from google font 
page ll found /tft

**Comment by Sacha96** [comment]
let's go with closest font we couldn't find the fonts on google fonts...

**Comment by ehab-hassan** [comment]
https://fonts.google.com/specimen/Oswald?preview.size=42&thickness=6&preview.text=THE%20WORLD%20IS%20USING%20A%20NEW%20INTERNET&preview.text_type=custom

https://fonts.google.com/specimen/Roboto+Condensed?preview.size=42&thickness=6&preview.text=THE%20WORLD%20IS%20USING%20A%20NEW%20INTERNET&preview.text_type=custom

@Sacha96 that is the closet fonts I found what do u think? I used Oswald font  it is in staging now
https://staging.threefold.io/tft

**Comment by Vilnite** [comment]
@Sacha96 please check.

**Comment by Sacha96** [comment]
Can we reduce title size by 1 size factor?

**Comment by ehab-hassan** [comment]
title smaller from 5rem to 4rem
![tft_title](https://user-images.githubusercontent.com/10484295/129890339-a7b376fa-daa7-4d6d-87f1-36ce825f3964.jpg)

**Comment by Sacha96** [comment]
Can we keep title for the first one bigger?

**Comment by Sacha96** [comment]
Also for partners can you add: Solidaridad, HPE, DigiByte, Dash, CasperLabs, Polygon (Matic), PreSearch, Neo, Seeds, Tomochain

**Comment by ehab-hassan** [comment]
- [ ] keep title for the first one bigger.
- [ ] add Partners.
- [ ] update last image.



![tft_updated](https://user-images.githubusercontent.com/10484295/130049549-6533872e-724a-4fdb-a9eb-08c971c2f0d6.jpg)

**Comment by Sacha96** [comment]
Great can we add the GET TFT like in AI file as CTA at end of page?

<img width="680" alt="Screenshot 2021-08-23 at 12 39 46" src="https://user-images.githubusercontent.com/54844940/130434250-929aab54-2900-4c6b-90c2-6ad2169c0d5c.png">

But instead of Liquid we guide to Binance Smart Chain. Change text too. 

New text: Visit Binance Smart Chain to get your TFT. 

Button > Get TFT

**Comment by Vilnite** [comment]
If additional comments/work needed, please continue on Circles tool : https://circles.threefold.me/project/despiegk-product_web_threefold/us/5?kanban-status=1611
