### ISSUE TITLE
Please update threefold.io to staging & production when possible

### ISSUE THREAD

**Issue by samtaggart** [threefoldfoundation/www_threefold_io#129]
I made updates to data_threefold which should be pushed to production when possible. It's not urgent. Thanks!

- [x] Push to staging
- [x] Ping Sam to check
- [x] Push to production

**Comment by PeterNashaat** [comment]
- getting error `gridsome: command not found`  when trying to build threefold_io site `publishtools build -r threefold_io`
<img width="1440" alt="Screen Shot 2021-08-17 at 8 55 12 AM" src="https://user-images.githubusercontent.com/13523434/129678239-8728247f-e089-44bd-9763-3d50163c2c8f.png">

**Comment by samtaggart** [comment]
@PeterNashaat Do you know what the error is in reference to?

**Comment by PeterNashaat** [comment]
@hossnys pushed to staging, can you check

**Comment by samtaggart** [comment]
Looks good, please push when ready @PeterNashaat

**Comment by hossnys** [comment]
done
