### ISSUE TITLE
Update production website with the latest team page updates

### ISSUE THREAD

**Issue by nbabenko** [threefoldfoundation/www_threefold_io#132]
Hello, we have updated threefold_data team folder:
https://github.com/threefoldfoundation/threefold_data/commits/development/content/person
Please apply latest changes for team profiles on the live website.

**Comment by PeterNashaat** [comment]
- Getting gridsome error while building
<img width="1440" alt="Screen Shot 2021-09-06 at 10 51 47 AM" src="https://user-images.githubusercontent.com/13523434/132193666-d45f5a64-17fe-47f6-af03-6951ed40471a.png">

**Comment by nbabenko** [comment]
fixed

**Comment by PeterNashaat** [comment]
- issue fixed and pushed latest updates to production
