### ISSUE TITLE
Cannot switch between pages

### ISSUE THREAD

**Issue by nbabenko** [threefoldfoundation/www_threefold_io#133]
Browsers: 
Safari Version 15.0 (16612.1.29.41.4, 16612)
Brave Browser Version 1.29.81 Chromium: 93.0.4577.82 (Official Build) (arm64)

When I click to any link from the top menu, it does not transfer me there. When I reload page from the browser address bar, page loads but then I cannot navigate other pages too. 

See video attached with full sound - you will hear when mouse clicks does not work.

https://user-images.githubusercontent.com/4426772/134864267-23a0c5b6-8de7-4a4b-a354-e2aaef2b3c9f.mp4

**Comment by nbabenko** [comment]
same issue on mobile chrome

**Comment by nbabenko** [comment]
same issue with the new website

**Comment by ehab-hassan** [comment]
fixed
