### ISSUE TITLE
fix broken links appeared after removing farming site 

### ISSUE THREAD

**Issue by hossnys** [threefoldfoundation/www_threefold_io#134]
broken links found here :
https://scan-links.threefold.tech/shared?token=eyJhbGciOiJIUzI1NiJ9.eyJ3aWQiOjEsInJvbGUiOiJ2aWV3ZXIifQ.5NgnZSAftekaqdiABRftVH2PBlia8Ah7YqKksq-L_Zc

**Comment by ehab-hassan** [comment]
I updated all broken links related to farming ,there are other links related to posts and page changed @samtaggart @Sacha96 @Vilnite can u please check it ?

**Comment by samtaggart** [comment]
Fixed on development.

**Comment by samtaggart** [comment]
All the links are still showing up as dead. But they should be fixed. @hossnys do we need to run the scanner again?

**Comment by hossnys** [comment]
@samtaggart yes i just run the scan again and here is the new report 
https://scan-links.threefold.tech/shared?token=eyJhbGciOiJIUzI1NiJ9.eyJ3aWQiOjEsInJvbGUiOiJ2aWV3ZXIifQ.5NgnZSAftekaqdiABRftVH2PBlia8Ah7YqKksq-L_Zc

**Comment by samtaggart** [comment]
OK I fixed the Unit Ventures link which I missed but the other one seems like an error.
