### ISSUE TITLE
link: point to how to boot a 3node

### ISSUE THREAD

**Issue by despiegk** [threefoldfoundation/www_threefold_io#135]
![image](https://user-images.githubusercontent.com/6021844/147866653-081143f0-9ad3-4d1e-829f-f0e9a0e58da2.png)

no links, people don't find how to get started

**Comment by Sacha96** [comment]
@andhartl can we work a doc to make a wiki page to boot a node (DIY) ? 

The latest information I found are the following forum posts from @scottyeager.

https://forum.threefold.io/t/diy-nodes-guide/837
https://forum.threefold.io/t/how-to-set-up-your-own-3node/833

Please let me know if this is still the process and that it is super accurate. Would appreciate if we could finalize this ASAP to simplify the process of getting started for farmers. 

Thanks, S

**Comment by Sacha96** [comment]
this is the closest it gets. let's work on that wiki page https://library.threefold.me/info/manual/#/manual__create_farm

**Comment by Sacha96** [comment]
Talked to @andhartl will come together with a 10 step approach to guide farmers through rather than jumping from one end of the manual to the other

**Comment by scottyeager** [comment]
I have pushed improvements to the farming section of the manual up to the development branch.

**Comment by Sacha96** [comment]
thanks scott i'm seeing the changes and it looks much better! Thanks, S

**Comment by Sacha96** [comment]
@ehab-hassan can you create a button for that section with `Build my 3Node` and link to https://library.threefold.me/info/manual/#/manual__create_farm

**Comment by despiegk** [comment]
please make sure all info is in wiki as single source of truth
forum can be a start or point to the wiki, but once its in prod info need to be in wiki
