### ISSUE TITLE
Website: show github link for team members

### ISSUE THREAD

**Issue by nbabenko** [threefoldfoundation/www_threefold_io#140]
As a user I want in the team section of the ThreeFold.io website (https://threefold.io/people) to see links to github for each person who is active in coding. 

This is something that exchanges or partners or investors often asks - to see github links for our dev team.

I've already prepared data in the data repo: https://github.com/threefoldfoundation/threefold_data/commit/878e4301ca317bb2c4a833f5686aeadd87b67250

**Comment by ehab-hassan** [comment]
done please check at staging

**Comment by nbabenko** [comment]
done, thank you
