### ISSUE TITLE
fix font awesome at io

### ISSUE THREAD

**Issue by ehab-hassan** [threefoldfoundation/www_threefold_io#141]
please fix font awesome at io acting wearied at staging
![photo_2022-02-23_13-01-00](https://user-images.githubusercontent.com/10484295/155307020-6ef4153b-f047-4fcf-8885-d48c60585073.jpg)

**Comment by samaradel** [comment]
fixed
![image](https://user-images.githubusercontent.com/11662805/155313254-d4c078ed-cd40-4d20-b244-2f6febb75dce.png)
