### ISSUE TITLE
Remove Belgium as Job Location from the Job listing under careers Tab  

### ISSUE THREAD

**Issue by desmondds** [threefoldfoundation/www_threefold_io#142]
Hi Team,

Kindly remove **A desk in our Belgian Office**; for all the below three mentioned job description under our careers page:

MASTER TECHNICAL ARCHITECT [](https://threefold.io/careers/master_architect_dt )
QUALITY ASSURANCE ENGINEER [](https://threefold.io/careers/qa_engineer)
SENIOR DEVELOPER  [](https://threefold.io/careers/senior_developer)

PS: This line reflects under the sub Tab: What we offer, which is at the extreme bottom of the page.

**Comment by ehab-hassan** [comment]
done at staging please check
https://www2.threefold.io/careers

**Comment by desmondds** [comment]
Has been updated. Thank you
