### ISSUE TITLE
Please change two button links on threefold.io/farm

### ISSUE THREAD

**Issue by samtaggart** [threefoldfoundation/www_threefold_io#143]
Please change these two buttons to: https://shop.threefold.tech

<img width="977" alt="Screen Shot 2022-04-13 at 15 00 46" src="https://user-images.githubusercontent.com/50134479/163175437-203f2ce5-a7ff-4db5-b8e1-6ece3c713c94.png">
<img width="505" alt="Screen Shot 2022-04-13 at 15 00 55" src="https://user-images.githubusercontent.com/50134479/163175454-b0f2b7a4-6416-43fc-a49f-364d86018903.png">

**Comment by ehab-hassan** [comment]
done @PeterNashaat can u update staging please

**Comment by samtaggart** [comment]
Hey guys, obviously this one was OK to go to production. No need to wait for me to confirm on something as small as this in the future! 🙏  Thanks

**Comment by ehab-hassan** [comment]
@PeterNashaat lets go production

**Comment by ehab-hassan** [comment]
@PeterNashaat Thanks for production updated
