### ISSUE TITLE
Increase telegram conversion

### ISSUE THREAD

**Issue by Nelson361** [threefoldfoundation/www_threefold_io#145]
People are having trouble finding us on telegram. Increasing the size of the telegram icon at the top of the page and also having a link for the general chat and DIY chat would help people get in contact with the community faster.

**Comment by samtaggart** [comment]
Thanks @Nelson361 will chat with @Sacha96 about this one!

**Comment by samtaggart** [comment]
I partially addressed this at www2.threefold.io but keeping this issue live until we get it right.
