### ISSUE TITLE
Find capacity size from homepage

### ISSUE THREAD

**Issue by Nelson361** [threefoldfoundation/www_threefold_io#146]
A direct link to https://explorerv3.grid.tf/ should be part of the menu at the top of the page "View Capacity"

**Comment by samtaggart** [comment]
<img width="1432" alt="Screen Shot 2022-09-01 at 3 55 08 PM" src="https://user-images.githubusercontent.com/50134479/187918749-0eb441fb-427b-4638-a3c8-625b609487f7.png">

You're saying it should be somewhere up here? It's under More Info and also it's the 2nd block on the homepage. But maybe Dashboard and Capacity deserve spots in the menu ...

**Comment by sasha-astiadi** [comment]
we can think of how to make this work @samtaggart

**Comment by sasha-astiadi** [comment]
we already have 'dashboard' on sidebar
