### ISSUE TITLE
First impressions for new visitors

### ISSUE THREAD

**Issue by Nelson361** [threefoldfoundation/www_threefold_io#147]
The very first screen that load for threefold.io tells very little information. Having to scroll down several screens or click links to get an idea of what is going on is hurting conversion.

4 links should be immediately seen upon the page loading.
-"Add capacity"  or "Farm" (maybe two links, the new marketplace and a DIY forum link)
-"Deploy" 
-A dashboard showing key statistics on our network (nodes, ssd, hdd, cores, etc)
-Link to our apps in both app stores

**Comment by despiegk** [comment]
should use new framework, @Nelson361 can you help?

**Comment by Nelson361** [comment]
I have limited web dev experience outside of wordpress but I'm willing to at least attempt taking a stab at it.

**Comment by sasha-astiadi** [comment]
will take this into consideration

**Comment by sasha-astiadi** [comment]
<img width="1165" alt="Screenshot 2023-05-23 at 11 36 00" src="https://github.com/threefoldfoundation/www_threefold_io/assets/43240801/d78b05e6-0b5f-409d-b889-c453ce0a6ae3">

**Comment by sasha-astiadi** [comment]
Weve got build and farm which are essentials as suggested
