### ISSUE TITLE
TF_IO - revive partner section on main website, gear towards 3.0 launch

### ISSUE THREAD

**Issue by despiegk** [threefoldfoundation/www_threefold_io#15]
![image](https://user-images.githubusercontent.com/6021844/108626319-d59ce600-744f-11eb-8d24-616b5e071dfe.png)

here partners need to be changed to supporting partners for 3.0

- HPE
- Solidaridad
- casperlabs (after agreement)
- digibyte
- noa-networks (after agreement)
- ... tbd

each partner has one of our partner pages with video if possible and why they like us.

this is generic, just to support the 3.0 release

### remarks

- see how noia did it
-

**Comment by samtaggart** [comment]
@despiegk I believe @Sacha96 sent you a proposal for the partners. Can you check / share next steps?

**Comment by samtaggart** [comment]
@despiegk Need your feedback in order to move this forward. Can do it on Sunday.

**Comment by samtaggart** [comment]
For now @despiegk said that the partners are fine.

We moved the partners up the io page for now.

We will add Casper ASAP.
