### ISSUE TITLE
Review Threefold New Framework

### ISSUE THREAD

**Issue by ehab-hassan** [threefoldfoundation/www_threefold_io#152]
https://www3.threefold.io/
ThreeFold with Zola ready with last updates at all data ( blogs and news, people ..... )
please check it before we update the staging

**Comment by despiegk** [comment]
see with kristof how we will bring it life
https://github.com/threefoldfoundation/www_threefold_io/tree/zola_development

**Comment by ehab-hassan** [comment]
@despiegk all updated and ready, ll check with @PeterNashaat to update production

**Comment by ehab-hassan** [comment]
Zola at production now
