### ISSUE TITLE
Impressum Link on ThreeFold.io

### ISSUE THREAD

**Issue by samtaggart** [threefoldfoundation/www_threefold_io#154]
Currently the Impressum link in the footer doesn't link anywhere.

In the footer, please change Impressum to ThreeFold Labs IT.

And please create a new page for it.

**Content:**

**ThreeFold Labs IT**
A company organized and existing under the laws of the United Arab Emirates with license number 934955

Warehouse 88:89
Al Jaddaf Dry Docks
P.O Box 283182
Dubai, United Arab Emirates

[Embed Google Maps Map of the address]

Please get in touch at info@threefold.io

**Comment by ehab-hassan** [comment]
do we have link for Embed Google Maps Map?

**Comment by samtaggart** [comment]
<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3609.732111513173!2d55.32868122377514!3d25.2122551323585!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3e5f5d5f7da0de2b%3A0x5aed461f937f54ff!2sAl%20Jaddaf%20-%20Dubai%20-%20United%20Arab%20Emirates!5e0!3m2!1sen!2str!4v1654516740830!5m2!1sen!2str" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>

@ehab-hassan

**Comment by ehab-hassan** [comment]
![image](https://user-images.githubusercontent.com/10484295/172248903-529a9e88-8838-4fdc-8c8d-179c78c9b0a8.png)
![image](https://user-images.githubusercontent.com/10484295/172249124-d2cf462c-c4f8-48a0-bd5f-c2ef3212d98c.png)

done by Samar can u check before we update production

**Comment by ehab-hassan** [comment]
production updated
