### ISSUE TITLE
probably page not used?

### ISSUE THREAD

**Issue by despiegk** [threefoldfoundation/www_threefold_io#157]
<img width="1016" alt="image" src="https://user-images.githubusercontent.com/6021844/175027523-73d7192e-48d5-4b58-af61-289ac9e3d7be.png">

**Comment by ehab-hassan** [comment]
This is the menu(nav page) I removed the wrong description
![image](https://user-images.githubusercontent.com/10484295/175229684-176ea6e9-9027-4370-b797-fca41c8d5944.png)
