### ISSUE TITLE
mistake in bitcoin mining energy blog

### ISSUE THREAD

**Issue by despiegk** [threefoldfoundation/www_threefold_io#159]
<img width="1337" alt="image" src="https://user-images.githubusercontent.com/6021844/176082405-ab936588-638f-4903-a2cb-ac447336e8af.png">

 the power consumption of such devices averages 28,470 kWh per year if operated continuously. In comparison, the annual consumption of a freezer is estimated between 200 and 500 kWh per year.

**Comment by HannahCordes** [comment]
Adjusted the number in the file. Will be pushed live along with the new blog post this afternoon.
