### ISSUE TITLE
TF_IO - invitation wizard for 3.0 info

### ISSUE THREAD

**Issue by despiegk** [threefoldfoundation/www_threefold_io#16]
- webpage where they have to login with TF Connect
    - explain how to get TFConnect and get part of our community
    - push them to go to Telegram Channel 
- they go into a wizard where
    - they agree with our terms and conditions
    - they tell us if someone did refer them (can be by threefold id or name of the person = free text)
- they need to mention why they need access (can mark all which matters)
    - want to be one of the investors to support the 3.0 launch
    - they want to collaborate in the 3.0 launch
    - they want to learn about tech
    - they want to be one of the early adopters of the grid
    - they want to learn about how tokens & farming work
    - they want to become a partner
    - ... tbd

## implementation details

- implement in nodejs (so can be part of digital twin later)
- records are just json on filesystem

**Comment by Sacha96** [comment]
To me its clear we;'re not doing this anymore so I\m closing the issue.
