### ISSUE TITLE
threefold.io publish website using zola

### ISSUE THREAD

**Issue by despiegk** [threefoldfoundation/www_threefold_io#160]
- make zola on development branch
- publish to /html
- get github to use gitpages to show the website
- put link from home to gitpages

**Comment by ehab-hassan** [comment]
zola on development branch now thanks @PeterNashaat

**Comment by ehab-hassan** [comment]
GitHub page works now when u push at development
https://threefoldfoundation.github.io/www_threefold_io/
still buttons links need to fix 
@timurgordon please push blog ,news ,people, partner when u done

**Comment by despiegk** [comment]
gitpages integration wrong
should not be a separate branch that does not make sense !!!

<img width="1052" alt="image" src="https://user-images.githubusercontent.com/6021844/180595895-3ca9aab5-59c6-4205-869b-c0ff7f3dea25.png">

**Comment by despiegk** [comment]
please document how github actions is used

**Comment by ehab-hassan** [comment]
@PeterNashaat can u help here?

**Comment by ehab-hassan** [comment]
@timurgordon links works now but external links need to open in new page
