### ISSUE TITLE
DONT use absolute links or links to the domain name

### ISSUE THREAD

**Issue by despiegk** [threefoldfoundation/www_threefold_io#161]
- many links are https://www... don't do if site itself !!!
- the images are broken online now, not right published

**Comment by ehab-hassan** [comment]
GitHub pages need path prefix
images now working but button still not working at GitHub page

**Comment by sasha-astiadi** [comment]
@ehab-hassan is it now fixed

**Comment by ehab-hassan** [comment]
No we blocked here Zola need path Link at Base url to work, Github page is working now but with (www_threefold_io) at path

**Comment by samtaggart** [comment]
Truthfully I don't fully understand this issue. @ehab-hassan @sasha-astiadi?

**Comment by samtaggart** [comment]
This is irrelevant now, closing the issue.
