### ISSUE TITLE
Is it possible on new framework to post a blog without it appearing on grid view?

### ISSUE THREAD

**Issue by samtaggart** [threefoldfoundation/www_threefold_io#162]
We want to keep the URL of some old blogs without having them appear on the grid at threefold.io/blog

Ehab and I have discussed this in chat, will let me know what the options are with Zola framework.

**Comment by samtaggart** [comment]
@ehab-hassan Please report back on this when you can.

**Comment by ehab-hassan** [comment]
@samtaggart I checked with @timurgordon he gave us a solution and tested by @samaradel and it works ll apply when we update production with zola framwork

**Comment by samaradel** [comment]
@samtaggart can you mention blog URLs you want to hide please?

**Comment by samtaggart** [comment]
Hi! Can we hide all of the ThreeFold Weekly blog posts please?

**Comment by timurgordon** [comment]
@samaradel we can use the draft: true variable in metadata to hide from all paginators and links

**Comment by samtaggart** [comment]
I still would like the blogs to be discoverable, since we have posted them in old content etc, but don't want to see them on the grid view on the blog page.

**Comment by samaradel** [comment]
@samtaggart done, check staging please

**Comment by ehab-hassan** [comment]
Lets keep this Hold for now while @timurgordon working in new publishtool to run data threefiold.
