### ISSUE TITLE
Hide www2 / www3 / any staging threefold.io sites from Google Search

### ISSUE THREAD

**Issue by samtaggart** [threefoldfoundation/www_threefold_io#163]
Please look into if there is any way to hide staging links from Google search results.

![photo_2022-08-04 15 48 48](https://user-images.githubusercontent.com/50134479/182851001-6d6d0d25-4cf7-4d72-adb4-7740ab893969.jpeg)

Check this resource: https://webmasters.stackexchange.com/questions/41021/hide-a-subdomain-from-google-search-engine-seo-result

**Comment by samtaggart** [comment]
Definitely seeing less results but still some
<img width="725" alt="Screen Shot 2022-10-11 at 1 18 46 PM" src="https://user-images.githubusercontent.com/50134479/195065131-07670434-1fd9-4823-ab2c-564f78f69d4d.png">
<img width="678" alt="Screen Shot 2022-10-11 at 1 18 24 PM" src="https://user-images.githubusercontent.com/50134479/195065145-11976c21-ae1d-4c03-b187-edf4e8627458.png">

**Comment by despiegk** [comment]
redirect www2, www3 to our main website

lets change name for staging & development to  e.g.  dev1.threefold.io ...
from now on put passwd "planetfirst" on all these dev websites

**Comment by samtaggart** [comment]
Who can work on this? @ehab-hassan @samaradel? Is it clear?

**Comment by ehab-hassan** [comment]
@samtaggart also, we can delete www3 no need it anymore?

**Comment by samtaggart** [comment]
@ehab-hassan Yes we can delete www3

**Comment by samtaggart** [comment]
Thanks @PeterNashaat should I assign you?

**Comment by PeterNashaat** [comment]
- Staging is now available at url https://dev.threefold.io/ with login
  - Username: `admin`
  - Password: `planetfirst` 
- https://www2.threefold.io and https://www3.threefold.io both now redirect to https://threefold.io

**Comment by PeterNashaat** [comment]
- Updated autodeployment workflows https://github.com/threefoldfoundation/www_threefold_io/commit/138edef0cec863bcf13f6ab35ae40aa018b289a6

**Comment by samtaggart** [comment]
![Image](https://github.com/threefoldfoundation/www_threefold_io/assets/50134479/9e256eca-e340-46f8-9f30-437a86f9c131)

![Image](https://github.com/threefoldfoundation/www_threefold_io/assets/50134479/853d4bf6-0c8b-403b-aa90-82b428f4b8e3)

**Comment by ehab-hassan** [comment]
@samtaggart 
./build.sh
then
./start.sh

**Comment by PeterNashaat** [comment]
Should be fixed now, Wrong url in config.toml file

**Comment by samtaggart** [comment]
Yes fixed, thanks!

**Comment by PeterNashaat** [comment]
- Can this be closed ?

**Comment by sabrinasadik** [comment]
Well this backfired. Pls let's not just redirect stuff like this. 
www2.threefold.io was used in the stellar testnet setup. 
Will have to fix this now. 
Horizon expects `.well-known/stellar.toml` to be present on the home domain. Since www2 is redirected this is broken.  
@PeterNashaat check if Stellar accepts domain + path if not we'll need to restore www2 or find a new domain to host this on.

**Comment by PeterNashaat** [comment]
i can make exception in the caddy config to serve sellar.toml at https://www2.threefold.io/.well-known/stellar.toml
and redirect everything else to threefold.io as is ?

**Comment by PeterNashaat** [comment]
- Created new caddy config just for stellar.toml file https://www2.threefold.io/.well-known/stellar.toml, caddy will redirect all incoming to www2.threefold.io website to threefold.io and only serve stellar.toml at url https://www2.threefold.io/.well-known/stellar.toml
```
www2.threefold.io {
    @allExceptWellKnown {
        not path /.well-known/stellar.toml
    }
    redir @allExceptWellKnown https://threefold.io

    handle /.well-known/stellar.toml {
        root * /home/webuser/websites/tmp/
        file_server
    }
}
```

**Comment by PeterNashaat** [comment]
- Added docs for stellar.toml file for mainnet and testnet with how to verify https://docs.grid.tf/threefold/itenv_threefold_main/src/branch/master/www/websites_list/threefold.io/stellar_toml.md
- https://www2.threefold.io/.well-known/stellar.toml up and running and serving the correct toml file.
![image](https://github.com/user-attachments/assets/e6e43224-b127-48ac-b88c-520456a06188)

**Comment by PeterNashaat** [comment]
- https://www2.threefold.io/.well-known/stellar.toml is back and the reset of https://www2.threefold.io/ is redirecting to dev.threefold.io
- Fixed.
