### ISSUE TITLE
Website improvements – please execute on development_sam

### ISSUE THREAD

**Issue by samtaggart** [threefoldfoundation/www_threefold_io#165]
**Please execute these on https://github.com/threefoldfoundation/www_threefold_io/tree/development_sam**

- [x] Update the logo on top-left and bottom-left to be current version (https://drive.google.com/file/d/1E9kG4_eyiZvhBgn589OemgtiDNQ6pSY8/view?usp=sharing)

**HOME**
- [x] On 2nd block, please lower Explore ThreeFold Grid Capacity button by two line breaks and link to https://dashboard.grid.tf/explorer/statistics
- [x] Change FEATURED STORIES to Dive Deeper and chance articles to 1. https://threefold.io/blog/post/planet_first_people_first/ 2. https://threefold.io/blog/post/internet_of_internets/ and keep 3. as the video
- [x] Change THE TEAM to The Team

**FARM**
- [x] Remove Build My 3Node Button in the second block (underneath the 3 steps)

**COMMUNITY**
- [x] Typo on LinkedIn button – should be Let's Network

**Comment by ehab-hassan** [comment]
Done.

**Comment by samtaggart** [comment]
@ehab-hassan Can I add one more small thing? Can you add ThreeFold logo centered in white space above "Planet and People First Internet"? Just the plain 3 logo here (https://drive.google.com/file/d/18XCJh3K2cps52D-dzUC9AKfysdLFm67R/view?usp=sharing). Maybe twice as large as the logo in the top-left corner. Then we can close this issue.

**Comment by ehab-hassan** [comment]
![image](https://user-images.githubusercontent.com/10484295/187462959-5215a3d0-7ee6-4fdd-a2cc-5be880c3f941.png)
done

**Comment by samtaggart** [comment]
Thank you brother!
