### ISSUE TITLE
Buttons linking to internal pages go to www2.threefold.io and sometimes open in new tabs

### ISSUE THREAD

**Issue by samtaggart** [threefoldfoundation/www_threefold_io#174]
If you go to the header menu and click one of the links, it goes to www2.threefold.io/page and opens in a new tab

If you go to threefold.io/grid, and click on learn more about TFT, it opens as www2.threefold.io/tft but in the same tab (as it should).

If you go to the footer, and click on Start Farming, it opens as www.threefold.io/farm (correct) but in a new tab (incorrect)

- [x] Fix menu (www2 and new tab)
- [x] Fix footer (www but new tab)
- [x] Fix all other internal links (www2)

Also see: https://github.com/threefoldfoundation/www_threefold_io/issues/173

**Comment by samtaggart** [comment]
In ecosystem menu, they open properly.

**Comment by timurgordon** [comment]
I think the [tf_update yaml is still adding the old url to config](https://github.com/threefoldfoundation/www_threefold_io/blob/8cfa6e8be1dc8570a831bc9b952bd017c06784b1/.github/workflows/tf_update.yml#L24), which might be why.

**Comment by PeterNashaat** [comment]
- Pushed to production, could you guys check!

**Comment by samtaggart** [comment]
Indeed it's working for me, apart from the footer.

**Comment by ehab-hassan** [comment]
fixed
