### ISSUE TITLE
Fix ranking of people and partners, update the ordering

### ISSUE THREAD

**Issue by samtaggart** [threefoldfoundation/www_threefold_io#176]
Right now we're showing people in alphabetical order by default.

Partners, is not clear to me the order we are showing in.

- [ ] Ranking needs to be fixed on both
- [ ] Then we need to update the ordering for both

**Comment by despiegk** [comment]
we need a ranking which can be set, and show accordingly, this same should be done for news, blogs, people, ...

**Comment by samtaggart** [comment]
This issue is very old and has been addressed.
