### ISSUE TITLE
Add ThreeFold Recommendations somewhere on the website

### ISSUE THREAD

**Issue by samtaggart** [threefoldfoundation/www_threefold_io#180]
e.g. The Social Dilemma
e.g. The Great Hack
e.g. Podcasts, books, etc

Probably on the About Us / Mission page

**Comment by samtaggart** [comment]
I don't think this is particularly relevant anymore but let's discuss.

**Comment by Mik-TF** [comment]
Not needed now with new UI/UX. Closing.
