### ISSUE TITLE
Optimize threefold.io for mobile

### ISSUE THREAD

**Issue by samtaggart** [threefoldfoundation/www_threefold_io#187]
I noticed a lot of issues with the website on mobile.

Some images are appearing below the text in the same block, instead of above.

Some spacing issues.

Etc.

Let me know if I need to get more specific but it should be fairly obvious when you compare desktop to mobile.

**Comment by ehab-hassan** [comment]
- [ ] Home
- [ ] Mission
- [ ] Grid
- [ ] build
- [ ] Farm
- [ ] TFT
- [ ] community
- [ ] Developer

**Comment by ehab-hassan** [comment]
@samtaggart all done at staging please check
