### ISSUE TITLE
Open graph issue with blogs

### ISSUE THREAD

**Issue by samtaggart** [threefoldfoundation/www_threefold_io#188]
See below. It's defaulting to see author's image rather than the blog image when sharing to social media, or at least to LinkedIn.

<img width="572" alt="Screen Shot 2022-09-16 at 5 10 58 PM" src="https://user-images.githubusercontent.com/50134479/190659129-28883d4f-a93e-4ea6-a49c-77e24fdc5e65.png">

**Comment by samaradel** [comment]
fixed on staging
![image](https://user-images.githubusercontent.com/11662805/190901033-61a51d7f-7029-4e4a-b6e5-6e2927c69f3d.png)
