### ISSUE TITLE
TF_IO - review starter page, so its all ready for 3.0 launch

### ISSUE THREAD

**Issue by despiegk** [threefoldfoundation/www_threefold_io#19]
![image](https://user-images.githubusercontent.com/6021844/108625963-05e38500-744e-11eb-93a7-7ac330f5ca7b.png)

- [x] do overview as follows
- [x] - 1: be internet: current website ok
- [x] - 2: alliance: cleanup but website ok
- [ ] - 3: marketplace: cleanup but each solution links to invitation page see #16
- [ ] - 4: Peer2Peer Cloud: 1 pager and intro page launch tbd date
- [ ] - 5: Cyber Pandemic: 1 pager and intro page launch tbd date
- [ ] - 6: digital twin: 1 pager and intro page launch tbd date

- [ ] coming soon
    - explain in 10 words what is going to happen end of march
    - tell that they can ask for access (point them to invitation wizard) see #16

- [ ] partners see #15

**Comment by samtaggart** [comment]
From Kristine:

We just spoke with Kds about that user flow.

This will be our main topic on Sunday’s sync call as invitation wizzard is still being worked on 

The main idea right now remains were we have landing pages for each website teasing people of what’s coming.

All websites will need a highlight message of upcoming TF 3.0 Launch (date tbd) linking to invitation wizzard!

- DT landing is handed in (I’ll prepare it), we add invitation wizzard on bottom when it’s ready

- Cloud website, same - adding invitation wizzard when it’s ready

- Marketplace the same

- Farming remains as is

Work on wikis remains - need to make sure we have all documentation there, proper split etc.

TF umbrella landing will need a tweak as well to meet this TF 3.0 Launch teaser with invitation wizzard.

**Comment by samtaggart** [comment]
We just need to decide on exact phrasing and how we want it to look. I will work on an idea for a component today, we can review on Sunday.

**Comment by Sacha96** [comment]
this story is outdated, removing it, new issues will be created today according to where we are now.
