### ISSUE TITLE
"X Minute Read" metric on blog posts

### ISSUE THREAD

**Issue by samtaggart** [threefoldfoundation/www_threefold_io#190]
Not a big priority but I would like to add a stat around reading time into each of the blogs.

It should be placed next to the date, underneath the author.

Medium has [an explanation](https://help.medium.com/hc/en-us/articles/214991667-Read-time#:~:text=At%20the%20top%20of%20each,an%20adjustment%20made%20for%20images.) of how they do things. We can do something similar I believe. I'm guessing Timur can write a script for this :)

**Comment by samaradel** [comment]
![image](https://user-images.githubusercontent.com/11662805/193085646-1840abb0-f03e-4533-a26a-7a8aa429893b.png)
