### ISSUE TITLE
Redirect old blog links to new links

### ISSUE THREAD

**Issue by samtaggart** [threefoldfoundation/www_threefold_io#192]
All blog links have changed with the new web framework, so all links that we used previously are dead ends right now. Since we linked blog posts in many other blog and forum post, etc. we need a fix for this issue.

EXAMPLE

- Old link: https://threefold.io/blog/post/four_phases_of_threefold/

- New link: https://www.threefold.io/blog/four-phases-of-threefold/

**Comment by ehab-hassan** [comment]
fixed by @timurgordon
