### ISSUE TITLE
Landing Page for Newsletter Sign-Ups

### ISSUE THREAD

**Issue by despiegk** [threefoldfoundation/www_threefold_io#194]
Add a landing page to the website where people can choose to sign up for different updates & newsletters.

Definitely give these options:
1. All updates & newsletters
2. Monthly newsletters
3. ThreeFold Weeklys

Optional additions (to be discussed):
4. Partnership / ecosystem updates (press releases, partnership announcements, ...)
5. Blog updates (send blog posts via email)
6. Product management updates (send Sasha's forum posts via email)

**Comment by samtaggart** [comment]
Have one of these, actually. We can tweak!

https://landing.mailerlite.com/webforms/landing/n7q9l7

**Comment by despiegk** [comment]
we need to make sure its on existing website

**Comment by samtaggart** [comment]
@despiegk Right now I don't think we have the capacity to do different updates / newsletters. We already have a landing page here.

https://landing.mailerlite.com/webforms/landing/n7q9l7

And it's already on the website.

Please clarify the ask.
