### ISSUE TITLE
TF_IO - invitation wizard for 3.0 (part 1)

### ISSUE THREAD

**Issue by despiegk** [threefoldfoundation/www_threefold_io#20]
part one of #16

needs to be coordinated with jimber in this iteration

- [ ] specs
- [ ] prototype

**Comment by Sacha96** [comment]
@Hamdy can you help develop the first version of this?

**Comment by samtaggart** [comment]
@Hamdy @ken-de-moor Can we get an update here?

**Comment by ken-de-moor** [comment]
@samtaggart no development is done for this at all on our end. Still have a backlog of couple weeks to work through for other digital twin features and this has no specs or requirements or anything.

**Comment by samtaggart** [comment]
@Sacha96 Not sure why you moved into accepted. I don't think we've gotten anywhere with this. Would recommend we move into next week.

**Comment by Sacha96** [comment]
seems this wizard didn't happen. i'm closing it and if it comes back to the picture we can define a proper story.
