### ISSUE TITLE
Main page links

### ISSUE THREAD

**Issue by matse22** [threefoldfoundation/www_threefold_io#210]
I found out that when I'm on threefold.io main page and i move to let's say https://www.threefold.io/partners/
All links from threefold.io at ABOUT US have changed source to https://www.threefold.io/partners/
You can move to it but it opens the same link that is shown in a source in new window.
![IMG_20221102_225737.jpg](https://user-images.githubusercontent.com/117125021/199611387-3c80d124-a5eb-40c5-a9a6-ef501ca534f4.jpg)![IMG_20221102_225655.jpg](https://user-images.githubusercontent.com/117125021/199611399-513491a4-ae40-4a87-b585-df99d0987b69.jpg)

**Comment by samaradel** [comment]
@matse22 fixed on [staging](https://www2.threefold.io/)
