### ISSUE TITLE
Ecosystem and MoreInfo looking bad on Android

### ISSUE THREAD

**Issue by matse22** [threefoldfoundation/www_threefold_io#211]
In my opinion it needs more spacing between bold and thin letters

![Screenshot_2022-11-02-23-09-04-058_com.opera.browser.jpg](https://user-images.githubusercontent.com/117125021/199612261-1a450e68-6757-462f-a891-21163a072191.jpg)![Screenshot_2022-11-02-23-09-13-245_com.opera.browser.jpg](https://user-images.githubusercontent.com/117125021/199612277-eabf90e2-952e-4e68-8a44-f4c092e292ad.jpg)

**Comment by samaradel** [comment]
![image](https://user-images.githubusercontent.com/11662805/199700166-eff99c64-2c2c-41da-be74-0b1aac5bc726.png)
fixed on [staging](https://www2.threefold.io/)
