### ISSUE TITLE
Links to 'Ecosystem' & 'MoreInfo' not working

### ISSUE THREAD

**Issue by sabrinasadik** [threefoldfoundation/www_threefold_io#213]
Both links don't do anything
Plus More Info are two words.

**Comment by sabrinasadik** [comment]
https://user-images.githubusercontent.com/31733464/203328257-94ca738f-1e39-41be-b8dc-039e99cf3c2e.mov

**Comment by sasha-astiadi** [comment]
strange, it works for me everytime, can yonu please try wirh another browser @sabrinasadik

**Comment by sabrinasadik** [comment]
Same on Safari


https://user-images.githubusercontent.com/31733464/203329597-0c9d5b69-1a88-458f-8324-9c9ad070e59e.mov

**Comment by sasha-astiadi** [comment]
moreinfo also need to have space

**Comment by sasha-astiadi** [comment]
@samaradel could you please investigate, i saw that you fixed the mobile dropdown on another issue

**Comment by sasha-astiadi** [comment]
More info fixed, https://github.com/threefoldfoundation/www_threefold_io/commit/8243ca70314a3b0885c8fd8a385c2d90e62d2081

**Comment by samaradel** [comment]
> @samaradel could you please investigate, i saw that you fixed the mobile dropdown on another issue

Fixed

**Comment by samaradel** [comment]
> More info fixed, [8243ca7](https://github.com/threefoldfoundation/www_threefold_io/commit/8243ca70314a3b0885c8fd8a385c2d90e62d2081)

it's broken because of that, please don't change the values

**Comment by samaradel** [comment]
@sabrinasadik it needs hard refresh to show

**Comment by sasha-astiadi** [comment]
@sabrinasadik no it was also broken before

**Comment by sabrinasadik** [comment]
Works now but MoreInfo is still missing a space.

**Comment by sasha-astiadi** [comment]
@sabrinasadik the navigation cant have space... ill just change it to 'Info'

**Comment by sabrinasadik** [comment]
@sasha-astiadi the link itself can't but the text you show can

![Screenshot 2022-11-29 at 11 11 32](https://user-images.githubusercontent.com/31733464/204501612-93824ea8-04cf-4633-8cf5-a9ae79ca5f0b.png)
![Screenshot 2022-11-29 at 11 11 41](https://user-images.githubusercontent.com/31733464/204501626-00898c49-5956-4f6e-aad2-d2d78739adab.png)

**Comment by ehab-hassan** [comment]
@sabrinasadik according to the dynamic menu code if we add space that'll break the link ,that name is go to (id) also and can't make space there the only way is to add it as one word

**Comment by ehab-hassan** [comment]
fixed
