### ISSUE TITLE
Marketplace has been flagged as a phishing site by Microsoft

### ISSUE THREAD

**Issue by scottyeager** [threefoldfoundation/www_threefold_io#214]
The marketplace link used on `threefold.io` has been marked by Microsoft as a potential phishing risk, and a big red warning page is displayed if users try to navigate there. I have submitted a report requesting that this warning be removed. In the meantime, I have noticed that the equivalent link including `index.php` is not flagged, so we might consider changing the link from:

`https://marketplace.3node.global/`

to

`https://marketplace.3node.global/index.php`

These lead to the same page. This link appear on `threefold.io/farm` as the `Buy` button, and maybe elsewhere in the site.

**Comment by sasha-astiadi** [comment]
thanks for flagging this, pun intended :)
asked ehab to fix it. @ehab-hassan can you please do a quick link change? thank yu

**Comment by sasha-astiadi** [comment]
@scottyeager do u know why its marked as phishing websitr by mcrosft

**Comment by ehab-hassan** [comment]
done at farm page at production but I found another link blogs updated it 
@timurgordon can u run ur script for data ThreFold and update production so blogs update

**Comment by scottyeager** [comment]
Thanks @sasha-astiadi and @ehab-hassan. I don't know why this happened in the first place. It's possible that someone submitted a report, either in error or as an attempt to harm the project.
