### ISSUE TITLE
Make sure threefold.io works with different prefixes, etc.

### ISSUE THREAD

**Issue by samtaggart** [threefoldfoundation/www_threefold_io#227]
threefold.io

should be accessible from:

threefold.io
http://threefold.io
https://threefold.io
www.threefold.io
http://www.threefold.io
https://www.threefold.io

threefold.me
http://threefold.me
https://threefold.me
www.threefold.me
http://www.threefold.me
https://www.threefold.me

**Comment by PeterNashaat** [comment]
- Updated all links to redirect to threefold.io

**Comment by samtaggart** [comment]
Thanks!
