### ISSUE TITLE
Remove people from team slider on home page

### ISSUE THREAD

**Issue by samtaggart** [threefoldfoundation/www_threefold_io#228]
Underneath **The Team**

- Please remove Chris, Raj, Geert, and Hannah
- Please add Sasha Astiadi and Victoria
- If possible to re-arrange the order, please make it ... Kristof, Adnan, Weynand, Sabrina, Sacha, Jan, Rob, Reem, Thabet, Florian ... and the rest can stay

**Comment by ehab-hassan** [comment]
done
