### ISSUE TITLE
GitHub link doesn’t lead to our main repo 

### ISSUE THREAD

**Issue by Parkers145** [threefoldfoundation/www_threefold_io#232]
Reported in Telegram link to GitHub leads to GitHub main page and not our landing page. 

Picture included off link in question
![766D1FAF-D5A9-493A-9D8B-0C14888F5835](https://user-images.githubusercontent.com/44621168/220078593-4f5f24b7-1e42-4055-ad88-e67ccc090ed8.jpeg)

**Comment by sasha-astiadi** [comment]
changed it to redir to https://github.com/threefoldtech/
