### ISSUE TITLE
threefold.io v3.10.0 - homepage

### ISSUE THREAD

**Issue by sasha-astiadi** [threefoldfoundation/www_threefold_io#242]
Navbar: 
- change mission into about
- add build section
- store
- add farm section
- tft
- more info
- ecosystem
- more

home page
section 1: remove buttons
section 2: same secrtion without button
section 3: change into why treefold, remove the buttons
section 4: ask timur if possible, another image
section 5:  remove the old content. add new content - page nr. 7
Section 6: remove the 3node stuff, replace with impact page
section 7: remove the old part n the button, replace with catalyst
section 8: remove, replace with the future page 10
section 9: remove the blog, replace with social media / page 11
section 10: remove the rest
- leave team page there
- and partner page also
- news
- footer

**Comment by samtaggart** [comment]
Creating a new issue which will override this.
