### ISSUE TITLE
make text indent to the right, when image is on the right side

### ISSUE THREAD

**Issue by sasha-astiadi** [threefoldfoundation/www_threefold_io#245]
for all the images left, text left is done correctly but we still have to do the
- text right, image right indent on all pages.

examples:

**Comment by sasha-astiadi** [comment]
![Image](https://user-images.githubusercontent.com/43240801/232488797-844c9318-ae2f-400c-bbc5-9e755997ad09.png)
![Image](https://user-images.githubusercontent.com/43240801/232488799-db8498a9-535e-4edd-8075-2210bd860cf8.png)
![Image](https://user-images.githubusercontent.com/43240801/232488796-cf9f0afe-d6d6-4120-9955-50a1b8d0ae8b.png)
![Image](https://user-images.githubusercontent.com/43240801/232488800-c23055d9-e07b-4dc8-a8be-a24d90f8f19b.png)
![Image](https://user-images.githubusercontent.com/43240801/232488798-33665b5d-4524-485b-90cb-0c0f33cff69b.png)

**Comment by sasha-astiadi** [comment]
they all the text have tostart on the right, and make sure there is a bit gap in between image and the text

**Comment by ehab-hassan** [comment]
updated all at the new pages do u need to update at the old pages like mission for example?
