### ISSUE TITLE
Partners click through on the main page - https://threefold.io/ 

### ISSUE THREAD

**Issue by amandacaster** [threefoldfoundation/www_threefold_io#246]
The Click through for the partners tab on the main page of https://threefold.io/ is resulting in an error https://www.threefold.iopartners/. Looks like the absence of the forward slash between our website and partners is the problem.  

![image](https://user-images.githubusercontent.com/88147124/234562749-bb5762d4-7fc9-44ea-8470-6670cb24fc89.png)

**Comment by ehab-hassan** [comment]
fixed at production

**Comment by amandacaster** [comment]
@ehab-hassan Thanks! It's working fine now.
