### ISSUE TITLE
mobile optimization v3.9.1

### ISSUE THREAD

**Issue by sasha-astiadi** [threefoldfoundation/www_threefold_io#255]
all for mobile only, desktop seem fine

# homepage

- [x] header image and title 'threefold' maybe a little bit smaller

<img width="295" alt="Screenshot 2023-05-10 at 15 16 59" src="https://github.com/threefoldfoundation/www_threefold_io/assets/43240801/cf8334ac-d17f-4ac9-bd4b-403348e7fd9c">

- [x] all benefit icons need to be 1x smaller

<img width="318" alt="Screenshot 2023-05-10 at 15 18 04" src="https://github.com/threefoldfoundation/www_threefold_io/assets/43240801/97675d63-9a66-40b1-b10c-1e8a4a895029">

# build page

- [x] icons need to be 1x smaller for mobile only, desktop seem fine

<img width="286" alt="Screenshot 2023-05-10 at 15 20 08" src="https://github.com/threefoldfoundation/www_threefold_io/assets/43240801/02d9a5da-88f2-4bd6-9717-3edfc44d0451">

# tft page

- [x] this one need to be 1x smaller for mobile only, desktop seem fine

<img width="309" alt="Screenshot 2023-05-10 at 15 21 15" src="https://github.com/threefoldfoundation/www_threefold_io/assets/43240801/aa70a7ef-73fc-4a31-9803-b84e92ea0fbb">

please make own branch from development, bring for preview to www2 (development), before going for mastee

**Comment by ehab-hassan** [comment]
fixed at staging

**Comment by sasha-astiadi** [comment]
![Image](https://github.com/threefoldfoundation/www_threefold_io/assets/43240801/183ded7a-b6cd-44ea-89ae-bddc9135679b)

add margin, and subtitle needs to be smaller

**Comment by ehab-hassan** [comment]
fixed  

![image](https://github.com/threefoldfoundation/www_threefold_io/assets/10484295/aff4022e-9226-44dd-9a35-6c936e4cf3e3)

**Comment by sasha-astiadi** [comment]
@ehab-hassan pls ask production to ops if done @ehab-hassan

**Comment by ehab-hassan** [comment]
production updated
