### ISSUE TITLE
Best Efforts: Get threefold.io good enough by end of day

### ISSUE THREAD

**Issue by samtaggart** [threefoldfoundation/www_threefold_io#259]
**Overview**
- Please work on [branch 3.10](https://github.com/threefoldfoundation/www_threefold_io/tree/3.10.0)
- Can be viewed locally and on www3.threefold.io when changes are pushed
- Let's push something live onto production by the end of the day
- See assets below

**Order of Priority**
1. Home Page
2. Build Page
3. Expand Page
4. Token Page
5. About Page
6. Secondary Pages

**General**
- [ ] Update CSS to match [website rough layout r02.pdf](https://github.com/threefoldfoundation/www_threefold_io/files/11632718/website.rough.layout.r02.pdf) – please just pull the colors that are being used, keep the font the same otherwise. [@sasha-astiadi]
- [ ] Need to find / build an icon set that we can use across the site [tbd]
- [ ] Need to find or create images when something is missing
- [x] Remove Community & Developer Resources from menus [@samtaggart]
- [x] Check and fix footer [@samtaggart]

**Home Page**
- [x] Update content (@samtaggart)
- [ ] Update layout to match the "website rough layout" doc above [@sasha-astiadi]

**Build Page**
- [ ] Finish content [@samtaggart]
- [ ] Fix the design [TBD, let's see how much work needs to be done]

Reference for build page is here: 
[ACFrOgDulCdznFizXl3zFZLbnreXkL0NUyj5StbWDpfQcvci5yiBxplrHjLE8HPuuT744r1XTqc64KOQzeQq9YFfrB1aoMUSQCdK-yreoqOFXIHNMPKjQXq1N0iX8tk=.pdf](https://github.com/threefoldfoundation/www_threefold_io/files/11634251/ACFrOgDulCdznFizXl3zFZLbnreXkL0NUyj5StbWDpfQcvci5yiBxplrHjLE8HPuuT744r1XTqc64KOQzeQq9YFfrB1aoMUSQCdK-yreoqOFXIHNMPKjQXq1N0iX8tk.pdf)

**Expand Page**
- [ ] Update header to match current style [@sasha-astiadi]
- [ ] Update anything else, secondarily [tbd]

**Token Page**
- [ ] Update header to match current style [@sasha-astiadi]
- [ ] Update anything else, secondarily [tbd]

**About Page**
- [ ] Update header to match current style [@sasha-astiadi]
- [ ] Update anything else, secondarily [tbd]

**Last Efforts**
- [ ] Check and tweak Newsroom
- [ ] Check and tweak Blog
- [ ] Check and tweak Careers Page
- [ ] Check and tweak Support Page Page
- [ ] Check and tweak People
- [ ] Check and tweak Partners

**Assets**
https://drive.google.com/drive/folders/1ye3PjDj8XVqrIYrDaFoRyUrBvFxpOtj_?usp=drive_link

**Comment by samtaggart** [comment]
@sasha-astiadi You can use one of these images for the About page header.
![about_header](https://github.com/threefoldfoundation/www_threefold_io/assets/50134479/4c885adc-2cbf-4c63-ba05-29ddb9b78654)

**Comment by samtaggart** [comment]
@sasha-astiadi Please use one of these images for header of token page. Again please let me know which you prefer so I can circle crop it the same as the other pages

![grid_0](https://github.com/threefoldfoundation/www_threefold_io/assets/50134479/0750b979-89b1-4d3c-bd13-f97940f82396)

**Comment by samtaggart** [comment]
These can be used for home, about, and token, respectively

![7](https://github.com/threefoldfoundation/www_threefold_io/assets/50134479/b348d8c2-e9ec-4d0b-a913-3b194c637e73)

![6](https://github.com/threefoldfoundation/www_threefold_io/assets/50134479/9cda94b7-7667-4ab9-b0fd-d0c67dd795bc)

![5](https://github.com/threefoldfoundation/www_threefold_io/assets/50134479/aa2d77f9-b45b-4a17-bb6f-acd624436418)

**Comment by sasha-astiadi** [comment]
# general css change
- H1 - Green color
- Some specific H2/H3 would be green but mainly black, please see the design pdf. 
- change all header bg as specified

**Comment by samtaggart** [comment]
Closing this issue, will create a new one for Ehab.
