### ISSUE TITLE
TF_IO - check website on wider screens

### ISSUE THREAD

**Issue by Vilnite** [threefoldfoundation/www_threefold_io#26]
Received feedback that on wider than usual screens (aka large developer screens), image is not stretching with.

![IMAGE 2021-03-02 17:42:55](https://user-images.githubusercontent.com/20182572/109673464-ba805380-7b7e-11eb-8e91-7796f0108ee8.jpg)

**Comment by samtaggart** [comment]
This was on a 4k "normal size" screen. Obviously this is quite rare for the market but maybe not for people interested in ThreeFold so we should take it into consideration. @VonSub comment please if you have any additional wisdom.

**Comment by Vilnite** [comment]
If I shrink the page (Ctrl -) this is what I get:

<img width="1440" alt="Screenshot 2021-03-05 at 12 26 38" src="https://user-images.githubusercontent.com/20182572/110103041-24327480-7dae-11eb-9eca-00cc20cddc6f.png">


Header image for sure is not responsive atm
