### ISSUE TITLE
Let's get updated threefold.io live asap

### ISSUE THREAD

**Issue by samtaggart** [threefoldfoundation/www_threefold_io#260]
**Notes**
- Work in [branch 3.10](https://github.com/threefoldfoundation/www_threefold_io/tree/3.10.0)
- Can be viewed locally or on www3.threefold.io when changes are pushed
- Let's push something to production by the end of the day
- See assets below

**Assets**
https://drive.google.com/drive/folders/1ye3PjDj8XVqrIYrDaFoRyUrBvFxpOtj_?usp=drive_link

**CSS**
- [x] H1 should be Green color (see reference image of home page above, match that color)
- [x] H2 should be Black
- [x] H3 also same green as H1
- [x] Normal text should be dark grey (see reference image of home page again)

**All Pages: Headers**
- [x] As per reference images, please make sure all home pages have the same background graphic, see the assets folder. You can keep the circular images now being used in the header. Only background image needs to be created / added.

**Home Page**
- [x] Keep "Why Do We Need" the same for now
- [x] Evolving the Internet should get updated based on reference image for home page
- [x] Live & Operational block should be converted into black, white, and grey as per reference image
- [x] "The ThreeFold Grid is community-owned" should be updated based on reference image
- [x] Keep "Support the Project"

**About Page**
- [x] Please follow same directions from above. Use alternating backgrounds between blocks, taking from the image assets shared above. You may zoom in, rotate, or flip assets to add variations (e.g. the folded checkered background can be used in different ways) and you can also reposition text as you like.

**Expand Page**
- [x] "Join the Revolution" should be in black, white, and grey, same as on the home page.
- [x] Please go black, white, and grey for the "Simple for Everyone" images
- [x] Same for the "Valuable and In Demand" block at the bottom

**Build Page**
- [x] Same directions as the About Page
- [x] Add links to Titles in "Engage with the Community"

**Token Page**
- [x] Same directions as About and Build Page
- [x] Make sure all images towards the bottom of the page are black, white, and grey

**Other Pages**
- [x] Make sure Blog, Newsroom, Support, and Careers are aligned with updated branding (e.g. backgrounds, black white and grey images, etc.

**Comment by ehab-hassan** [comment]
@samtaggart is there Figma or guide file for all pages to see the whole pictures that ll save time ?

**Comment by samtaggart** [comment]
No I don’t have a design file. But You are mostly just keeping the images
the same and adding backgrounds.

**Comment by samtaggart** [comment]
If something is confusing please let me know. Also if you push some things
throughout the day I can check them on www3.

**Comment by ehab-hassan** [comment]
we can't add the background in all sections some sections are divided into 2 rows, header and content I added to some sections at home with one row
https://www3.threefold.io/

**Comment by samtaggart** [comment]
Hi @ehab-hassan it's looking pretty good, thank you brother.

OK so anytime we split a row into multiple columns then we can't do a full background? Is that what you are saying?

**Comment by ehab-hassan** [comment]
Yes, That is true we can add a color background but not an image because the two sections will not fit with the repeated image.
Also making all color images (the old TFT color) black and white ll not be good it can work with icons but not images so I think we can find the source and make it green what u think?

**Comment by ehab-hassan** [comment]
@samtaggart all main pages are updated check
https://www3.threefold.io/
also please check all old pages and images and delete or archive them.

I m creating a Figma file (home page for now) so we can edit and modify it for the next version of the website to save time and imagine the whole page
https://www.figma.com/file/VzLtDXijQ76bd9myUO9A4S/ThreeFold-new-version?type=design&node-id=0-1&t=Qa8bpfVEaDsSOQbR-0

**Comment by samtaggart** [comment]
> @samtaggart do we still use the Community page at io https://www3.threefold.io/community/ so I brand it with a new theme?

For now it is not a priority, thanks @ehab-hassan

**Comment by samtaggart** [comment]
Please give me 20-30 minutes, I have some new tasks.

**Comment by samtaggart** [comment]
**All Pages**
- [ ] Change Get TFT Button, needs to match updated branding [@ehab-hassan]
- [ ] Check spacing / margins / padding across all pages / multiple screen sizes [@ehab-hassan]
- [ ] Double check spacing / margins / padding across all pages [@samtaggart]
- [ ] Check all site for visual consistency with usage of headers, subheaders, and text (e.g. we should follow a pattern across the whole site) [@ehab-hassan]
- [ ] Try buttons with light grey background and no outline stroke (what happens on hover?) [@ehab-hassan]
- [ ] Change the hover color of the top menu navigation (e.g. when on Expand page it should be clear you are on Expand Page in the header menu) [@ehab-hassan]

@ehab-hassan Here is a first batch of issues. More coming.

**Comment by samtaggart** [comment]
**General**
- [ ] Please check the checkerboard graphics across all pages. You shouldn't drag out the checkerboard graphic so it is distorted ... rather Zoom in, Zoom out, rotate, etc

**Home Page**
- [ ] Find / create new header image for home page [@samtaggart]
- [ ] Remove How it Works button from header
- [ ] Check "Build on the Platform" button – I saw it on a big screen size and the text was off
- [ ] Change "Join the Community" button to https://t.me/threefold for now
- [ ] Add line breaks between text and buttons Expand, Build, and Together
- [ ] Change "Not Equal" to "Not Scalable"

**About Page**
- [ ] Find / create new header image for Genesis [@samtaggart]
- [ ] Please try the Values 3x3 (change font size if you need to) instead of one row

**Expand**
- [ ] Add green accents or highlights to the old design images [@ehab-hassan]
- [ ] Find more realistic image for "find your fit" [@samtaggart]

**Build**
- [ ] Please do the case studies 2x2 instead of 4 in a row, decrease font size if needed [@ehab-hassan]
- [ ] Even out the button placement under Discover the ThreeFold Advantage
- [ ] Change Solution Provider title to Monetize Your Solutions

**Token**
- [ ] Add green accents or highlights to the old design images [@ehab-hassan]

**Comment by samtaggart** [comment]
- [ ] Adjust all headers so that images are cropped into one of the shapes in the background, like this (bad) example below. Feel free to rotate the grey background image to find different shapes for each header. Also feel free to change the opacity of the images so they blend in more.

<img width="707" alt="Screen Shot 2023-06-07 at 10 05 34" src="https://github.com/threefoldfoundation/www_threefold_io/assets/50134479/2b2690e4-33ae-44a5-baa5-0c8aeeaa907b">

**Comment by samtaggart** [comment]
- [ ] Clean up the folders before going to production [@samtaggart]

**Comment by ehab-hassan** [comment]
> * [ ]  Adjust all headers so that images are cropped into one of the shapes in the background, like this (bad) example below. Feel free to rotate the grey background image to find different shapes for each header. Also feel free to change the opacity of the images so they blend in more. [@ehab-hassan]
> 
> <img alt="Screen Shot 2023-06-07 at 10 05 34" width="707" src="https://user-images.githubusercontent.com/50134479/243952194-2b2690e4-33ae-44a5-baa5-0c8aeeaa907b.png">

This ll not be good with responsive and especially on mobile it is a background the black text ll be at dark part

**Comment by samtaggart** [comment]
> > * [ ]   Adjust all headers so that images are cropped into one of the shapes in the background, like this (bad) example below. Feel free to rotate the grey background image to find different shapes for each header. Also feel free to change the opacity of the images so they blend in more. [@ehab-hassan]
> > 
> > <img alt="Screen Shot 2023-06-07 at 10 05 34" width="707" src="https://user-images.githubusercontent.com/50134479/243952194-2b2690e4-33ae-44a5-baa5-0c8aeeaa907b.png">
> 
> This ll not be good with responsive and especially on mobile it is a background the black text ll be at dark part

OK, do you have any recommendations?

**Comment by samtaggart** [comment]
- [ ] Create icons for Build Page – Forum, Open Source, Farming, and Support [@samtaggart]
- [ ] Make sure two lines of text for each of these descriptions [@samtaggart]

**Comment by samtaggart** [comment]
Here are the icons for the Build page @ehab-hassan (for now)

![support](https://github.com/threefoldfoundation/www_threefold_io/assets/50134479/6b30c879-ed58-49a5-9fc3-61b138a8e9ba)
![open source](https://github.com/threefoldfoundation/www_threefold_io/assets/50134479/16ca9958-fdc6-448f-baad-e30be3045d97)
![forum](https://github.com/threefoldfoundation/www_threefold_io/assets/50134479/59a3510c-ac4d-4930-89eb-d2b59eff25cf)
![farming](https://github.com/threefoldfoundation/www_threefold_io/assets/50134479/760d04d1-b75a-4bfa-bdbf-ef8766a292e0)

**Comment by samtaggart** [comment]
@ehab-hassan Hi brother Please explains the folder structure so I know where to work (e.g. build, buildold, buildnew).

**Comment by ehab-hassan** [comment]
![menu](https://github.com/threefoldfoundation/www_threefold_io/assets/10484295/26d5a337-c05f-4add-926c-e8c1999e7c49)
@samtaggart I renamed the pages we used with the same name at nav About/Expand/Build/Token
just go through the folder I circled with red color(old pages) and archive them or put them on google drive.

**Comment by ehab-hassan** [comment]
![image](https://github.com/threefoldfoundation/www_threefold_io/assets/10484295/f847c98b-f71f-4929-a55f-cf97b99e024f)
For this part, I didn't distort, it is background so it takes the height from the content if I make a fixed height ll not work with all sections, and bad at responsive

**Comment by ehab-hassan** [comment]
https://www3.threefold.io/
@ updated please check before production

**Comment by samtaggart** [comment]
- [ ] "Explore Grid Capacity" on Home and Expand pages should open in a new tab [@ehab-hassan]

**Comment by ehab-hassan** [comment]
fixed
