### ISSUE TITLE
Create images for threefold.io

### ISSUE THREAD

**Issue by samtaggart** [threefoldfoundation/www_threefold_io#261]
Have spoken about this with @ehab-hassan on Telegram but I'm requesting that we create 7 images for threefold.io:

- [x] Home Page: Header
- [x] Home Page: Why Alternative
- [x] About Page: Header
- [x] Expand Page: Header
- [x] Expand Page: Find Your Fit
- [x] Build Page: Header
- [x] Token Page: Header

The details can be found [here](https://docs.google.com/presentation/d/1p1aPX_2azlzkgYm3ZI00R1XhpNzbpW3pIuk4bj5u7z0/edit#slide=id.g252cb85a4c1_0_18).

And the assets can be found [here](https://drive.google.com/drive/folders/1YP6fNWmokMla4dpynL_ctuphPbXF1Gno).

Please focus first on the five header images.

**Comment by ehab-hassan** [comment]
home 
![image](https://github.com/threefoldfoundation/www_threefold_io/assets/10484295/bd35cbf9-7f4b-47c2-8ad1-f32eb57d9032)
About
![image](https://github.com/threefoldfoundation/www_threefold_io/assets/10484295/6a502698-534f-4c6e-8a51-3d7148b00c28)

**Comment by ehab-hassan** [comment]
@samtaggart what u think about replacing this with a checkered background?
![image](https://github.com/threefoldfoundation/www_threefold_io/assets/10484295/b5c7e84a-f3eb-46b6-ba68-e7fd3384dd8a)
