### ISSUE TITLE
Get Started button on Home page should link to Take Action Today block

### ISSUE THREAD

**Issue by samtaggart** [threefoldfoundation/www_threefold_io#262]
<img width="1431" alt="Screen Shot 2023-06-22 at 12 04 01" src="https://github.com/threefoldfoundation/www_threefold_io/assets/50134479/a18b6a1a-e6d3-4728-9fc4-cf600949d6e8">

should link to

<img width="930" alt="Screen Shot 2023-06-22 at 12 04 40" src="https://github.com/threefoldfoundation/www_threefold_io/assets/50134479/aba98a42-298e-482b-8f3b-324e9c55a875">

**Comment by RajeevDash007** [comment]
assign me this, I can fix it

**Comment by ehab-hassan** [comment]
@samtaggart fixed
