### ISSUE TITLE
add newsletter popup

### ISSUE THREAD

**Issue by sasha-astiadi** [threefoldfoundation/www_threefold_io#267]
when user visit threefold.io, add newsletter pop up in the middle of the page , with an X on the right corner to close

https://landing.mailerlite.com/webforms/landing/n7q9l7

<img width="1021" alt="Screenshot 2023-07-11 at 14 26 44" src="https://github.com/threefoldfoundation/www_threefold_io/assets/43240801/9aac6dfd-3657-4047-844d-5581ba34ec96">

<img width="790" alt="Screenshot 2023-07-11 at 14 26 56" src="https://github.com/threefoldfoundation/www_threefold_io/assets/43240801/b5a3633b-9bfd-403b-8d71-ff9b3b180cde">

**Comment by sasha-astiadi** [comment]
maybe make a new branch for this bc its not urgent. only urgent issues can be commited to development

**Comment by ehab-hassan** [comment]
we already had this at the nav and footer
![image](https://github.com/threefoldfoundation/www_threefold_io/assets/10484295/4eb75162-90d8-4ec8-9d7b-129364f8e37a)

or you need it to show automatically like a cookies alert at the top of the page?
