### ISSUE TITLE
make a new mdbook of library.threefold.io

### ISSUE THREAD

**Issue by sasha-astiadi** [threefoldfoundation/www_threefold_io#268]
transfer all articles of library.threefold.io to a new mdbook info.grid.tf

**Comment by Mik-TF** [comment]
Isn't manual.grid.tf the new place for this? We can continue the article transfer of course.

**Comment by amandacaster** [comment]
The transfer from the library to the manual has been completed. @Mik-TF can you confirm, please?

**Comment by Mik-TF** [comment]
Months ago now! Yes. all good. Closing :)
