### ISSUE TITLE
TF_IO - privacy card fix

### ISSUE THREAD

**Issue by Vilnite** [threefoldfoundation/www_threefold_io#27]
On home page comparison component, Privacy card does not align in size with rest of the cards when shrinking screen. Let's fix it.

<img width="708" alt="Screenshot 2021-03-04 at 13 29 45" src="https://user-images.githubusercontent.com/20182572/109957758-0ef61100-7cee-11eb-8060-7e52c49ffd63.png">

**Comment by samaradel** [comment]
@ehab-hassan decrease privacy image size, please

**Comment by ehab-hassan** [comment]
fixed
