### ISSUE TITLE
Clean up people section of threefold.io

### ISSUE THREAD

**Issue by samtaggart** [threefoldfoundation/www_threefold_io#275]
**REMOVE IMMEDIATELY**
- [x] Nickolay
- [x] Victoria
- [x] Hannah
- [x] Ivan
- [x] Jonas Delrue
- [x] Ken De Moor
- [x] Tobias Chielens

**NEXT STEPS**
- [ ] Ask people to update info on this Google form: https://forms.gle/TUtzv6cQ6jrqBfPx9
- [x] Add team members who fill out form to threefold.io/people

**Comment by ehab-hassan** [comment]
@samtaggart I removed the people u mention above and updated all the Egypt team.

**Comment by sasha-astiadi** [comment]
@amandacaster @TullysInc @mahendravarmayadala93 @shng4you please fill this form and provide a picture of yourself on this issue so that @ehab-hassan can add you to the website

**Comment by mahendravarmayadala93** [comment]
Hi @sasha-astiadi & @ehab-hassan  I have filled the form & see there's no option to upload the picture there. So uploading it here.
![msg1690442694-60742](https://github.com/threefoldfoundation/www_threefold_io/assets/89931135/0c96ebc5-b564-4309-9631-c1298106e933)

**Comment by Mik-TF** [comment]
@sasha-astiadi I took the opportunity to also write a description. Here's a picture for the profile.

Thanks!

![mperreault_profile_picture](https://github.com/threefoldfoundation/www_threefold_io/assets/77026219/00ac3c8f-b620-44f2-8ef5-d6c7502f1809)

**Comment by amandacaster** [comment]
Hey @ehab-hassan, I have submitted my write-up. 
![website picture](https://github.com/threefoldfoundation/www_threefold_io/assets/88147124/37983a55-d879-47b7-a32c-d129b0283d9a)

**Comment by ehab-hassan** [comment]
@samtaggart @sasha-astiadi where I can find the data filled out on Google Form?

**Comment by samtaggart** [comment]
@ehab-hassan Just seeing this. Just gave you access, in case you never got?

**Comment by shng4you** [comment]
Hey @ehab-hassan , I have submitted/filled the form & here is my pics.
![26220518_1546932218730223_4682128195533844284_o](https://github.com/threefoldfoundation/www_threefold_io/assets/95933607/0b99515f-d35c-4e13-8893-d6ce7d8da65d)

**Comment by ehab-hassan** [comment]
@sasha-astiadi @samtaggart @Mik-TF @amandacaster @shng4you @mahendravarmayadala93  team page updated at development please check before go production
https://www2.threefold.io/people/

**Comment by samtaggart** [comment]
@ehab-hassan 

- [ ] Please remove the video from Adnan's profile
- [ ] Please change the ranking of the newly-added team members, as the top ranking is reserved for co-founders and core team members
- [ ] Please remove Ashish Bansal and Dylan Verstraete

**Comment by samtaggart** [comment]
& thank you!

**Comment by mahendravarmayadala93** [comment]
Hi @ehab-hassan ! **Mahendra Varma** here! Could you please change the bio to " **Tech enthusiast with a passion for photography**" Thank you.

**Comment by amandacaster** [comment]
Hey, @ehab-hassan can you change my picture to this, please? I am sorry for the edits. 
![photo_2023-11-07_08-59-39](https://github.com/threefoldfoundation/www_threefold_io/assets/88147124/cd484aa2-7da9-4e52-8b04-96e371a5fa21)

**Comment by ehab-hassan** [comment]
done 
https://www2.threefold.io/people/

**Comment by samtaggart** [comment]
Sorry now the ranking was too low so I fixed it already on development, please feel free to push to production!

**Comment by ehab-hassan** [comment]
production updated

**Comment by Mik-TF** [comment]
Good for me too. Great.

**Comment by sasha-astiadi** [comment]
@Mik-TF ahahh i was just gonna write you today. yay!! :)

**Comment by Mik-TF** [comment]
Can this issue be closed? I think everything is updated.

**Comment by ehab-hassan** [comment]
'll close this issue If there is someone new ll open a new one
