### ISSUE TITLE
IO: Add In The News from Farming Site

### ISSUE THREAD

**Issue by samtaggart** [threefoldfoundation/www_threefold_io#28]
Think it can go above the last component, but let me know if you think there is a better spot.

<img width="1138" alt="Screen Shot 2021-03-04 at 4 24 27 PM" src="https://user-images.githubusercontent.com/50134479/109970467-27722580-7d06-11eb-98a8-80d94b2c8a00.png">

**Comment by Vilnite** [comment]
Logos are not showing, please fix:

![Uploading Screenshot 2021-03-05 at 14.34.59.png…]()
