### ISSUE TITLE
Update partners on threefold.io

### ISSUE THREAD

**Issue by samtaggart** [threefoldfoundation/www_threefold_io#284]
threefold.io/partners is outdated, needs to be updated

first step is for @samtaggart talk to adnan about how to handle this and prepare plan of action. the issue will be updated afterwards.

**Comment by samtaggart** [comment]
@AdnanFatayerji To provide a list of who should be added / removed

**Comment by amandacaster** [comment]
This is being worked on [git issue#176](https://git.ourworld.tf/tfgrid/circle_promotion/issues/176).

**Comment by Mik-TF** [comment]
As Amanda said, the latest list is here: https://git.ourworld.tf/tfgrid/circle_promotion/issues/176#issuecomment-5047

**Comment by samtaggart** [comment]
Holochain has been added and for now we can consider this list up to date.
