### ISSUE TITLE
Broken links > Threefold.io > TFT

### ISSUE THREAD

**Issue by mahendravarmayadala93** [threefoldfoundation/www_threefold_io#288]
1) https://www.threefold.io/tft - Check All Partners -> https://www.threefold.io/partners/le-ciel-foundation/ [ **VIDEO UNAVAILABLE** ]

**Comment by amandacaster** [comment]
[PR](https://github.com/threefoldfoundation/www_threefold_io/pulls) created with the 2nd commit, the video was removed after discussion with Sam.

**Comment by samtaggart** [comment]
New iteration live – [www.threefold.io](http://www.threefold.io/)
