### ISSUE TITLE
Broken Links > Threefold.io > Ecosystem

### ISSUE THREAD

**Issue by mahendravarmayadala93** [threefoldfoundation/www_threefold_io#289]
1) Ecosystem -> People -> https://www.threefold.io/people/sam-taggart/ - No information available

2) Ecosystem -> Partners ->https://www.threefold.io/partners/money-of-good/ -> Impact -> [ **Sorry this video doesn't exist** ]

3) Ecosystem -> Partners ->https://www.threefold.io/partners/ubuntu/ : Type Errors in Bold.
 Powered by ThreeFold
ThreeFold’s unique decentralized, uncontrolled Internet solution serves as a perfect foundation for Ubuntu’s digital, social commerce platform. Together we can secure **equeal** financial **oportunities** distributed globally and with full ownership in the most secure way. 

4) Ecosystem -> Partners -> https://www.threefold.io/partners/vlinder/ : Hyperlinked Keywords that can't seem to connect.
        
          a) Vlinder - https://vlinder.app/ - This site can't be reached.
          
          b) The Vlinder app beta - https://vlinder.app/ - This site can't be reached.

5) Ecosystem -> Partners -> https://www.threefold.io/partners/spinn/ : Typo error : Craftsmanshift ; Craftsmanship

6) Ecosystem -> Partner -> https://www.threefold.io/partners/ootopia/ 
       
               a) Website linked to [Globe](https://www.ootopia.org/) symbol leads to the error - Looks like this domain isn't
                    connected to a website yet.
               b) Typo error - Effective actions **is** not being taken **bu** global leaders, politicians or corporations.
                    Corrected statement: "Effective actions are not being taken by global leaders, politicians, or corporations."

7) Ecosystem -> Partner -> https://www.threefold.io/partners/seeds/ -> Globe symbol & Keyword **SEEDS** leads to webpage https://www.joinseeds.com/ that is **404** error

8) Ecosystem -> Partners -> https://www.threefold.io/partners/beliive/ - Website taking too much to respond.

9) Ecosystem ->Partners -> https://www.threefold.io/partners/aiqom/ - 
             a) No linked-in profile found for the company 
             b) The hyperlinked keyword: 3Bot technology leads to a website that is not found.

**Comment by amandacaster** [comment]
[PR](https://github.com/threefoldfoundation/www_threefold_io/pull/290) created for Point 2 - Video removed after a discussion with Sam. 

Point 1 @samaradel is looking into it.

**Comment by samaradel** [comment]
> [PR](https://github.com/threefoldfoundation/www_threefold_io/pull/290) created for Point 2 - Video removed after a discussion with Sam.
> 
> Point 1 @samaradel is looking into it.

Fixed on staging, check it please [sam-taggart](https://www2.threefold.io/people/sam-taggart/)

**Comment by mahendravarmayadala93** [comment]
[PR](https://github.com/threefoldfoundation/www_threefold_io/pull/292) created for Point 3.

**Comment by mahendravarmayadala93** [comment]
[PR](https://github.com/threefoldfoundation/www_threefold_io/pull/292) committed for Point 4.

**Comment by mahendravarmayadala93** [comment]
[Committed](https://github.com/threefoldfoundation/www_threefold_io/pull/292/commits) to PR for Point 5

**Comment by mahendravarmayadala93** [comment]
[Committed ](https://github.com/threefoldfoundation/www_threefold_io/pull/292/commits)changes to PR for Point 6b. For 6a I can't be able to find the original link for **Ootopia** website.

**Comment by mahendravarmayadala93** [comment]
[Committed ](https://github.com/threefoldfoundation/www_threefold_io/pull/292/commits) PR for Point 7.

**Comment by mahendravarmayadala93** [comment]
For **Point 8** - **Beliive** Researched for the original website but nothing was found. As per the info [here](https://pitchbook.com/profiles/company/267990-04#overview) it states that it is out of business. Kindly recheck.

**Comment by mahendravarmayadala93** [comment]
For Point **9a** : No linked profile found & for **9b**) [committed](https://github.com/threefoldfoundation/www_threefold_io/pull/292/commits) the change to the PR by adding the new [link](https://manual.grid.tf/concepts/grid3_components.html?highlight=3bot#3bot-or-threebot).
