### ISSUE TITLE
Broken Links > Threefold.io> Mission

### ISSUE THREAD

**Issue by amandacaster** [threefoldfoundation/www_threefold_io#291]
The following links need to be amended or removed 

- [x] The link for [IETSA](https://threefold.io/news/post/threefold_ietsa/) under [Planet First People First](https://www.threefold.io/blog/planet-first-people-first/)

- [x] The link for tagged with [Adnan's name](https://threefold.io/news/post/threefold_cybernews/) under [Planet First People First](https://www.threefold.io/blog/planet-first-people-first/)

- [x] We will need to add “This article was originally published by Ashish Bansal, a former member of ThreeFold Foundation. ” to [Ashish's write-up](https://www.threefold.io/blog/decentralised-internet-india/)

**Comment by amandacaster** [comment]
All the above 3 commits are under [PR [](](https://github.com/threefoldfoundation/www_threefold_io/pull/290))

**Comment by samtaggart** [comment]
New iteration live – [www.threefold.io](http://www.threefold.io/)
