### ISSUE TITLE
Please add line of text on the partners page

### ISSUE THREAD

**Issue by samtaggart** [threefoldfoundation/www_threefold_io#296]
Not sure how to add a line of text here:

<img width="1220" alt="Screen Shot 2023-12-05 at 08 54 02" src="https://github.com/threefoldfoundation/www_threefold_io/assets/50134479/72f45823-567f-448a-b596-6acbe1760222">

But I would like it to say:

Partners are projects with whom we have at least signed an agreement (most typically a Memorandum of Understanding) to move forward. These partners collectively embody our commitment to collaboration across various phases of development, strengthening our shared mission.

**Comment by samaradel** [comment]
![image](https://github.com/threefoldfoundation/www_threefold_io/assets/11662805/d9c7deb7-2740-4da6-a95a-27d37495ee87)
