### ISSUE TITLE
Please add line of text on people page

### ISSUE THREAD

**Issue by samtaggart** [threefoldfoundation/www_threefold_io#297]
Same ask as partners page, but please put:

Our team brings together +30 years of experience in cloud automation, Internet storage, and infrastructure services. We are a passionate group on a collective mission to improve the planet’s situation and benefit the people around us.

**Comment by samaradel** [comment]
![image](https://github.com/threefoldfoundation/www_threefold_io/assets/11662805/f374ae5b-fcba-4127-9f93-72e90fa6a495)
