### ISSUE TITLE
Please remove Weynand & Rob from Team slider on homepage

### ISSUE THREAD

**Issue by samtaggart** [threefoldfoundation/www_threefold_io#298]
![Screen Shot 2023-12-05 at 15 57 29](https://github.com/threefoldfoundation/www_threefold_io/assets/50134479/f630bacf-ba06-4659-a487-bb21718b53d3)

Please also HIDE their "people" pages

**Comment by ehab-hassan** [comment]
@samtaggart I see you hid the team section at home staging is this issue still valid?

**Comment by samaradel** [comment]
Weynand & Rob are removed and the section is still hidden.

![image](https://github.com/threefoldfoundation/www_threefold_io/assets/11662805/957c318f-37e2-4d61-9973-7a9d83db465a)
