### ISSUE TITLE
Make sure grid stats are accurate or we have a disclaimer

### ISSUE THREAD

**Issue by samtaggart** [threefoldfoundation/www_threefold_io#299]
There is a discrepancy between numbers on the site and other information (e.g. grid stats on the forum). Need to either make sure the numbers all match up or add a qualifying statement on the website so it is clear that we are / are not counting sleeping nodes.

![Screen Shot 2023-12-05 at 16 47 26](https://github.com/threefoldfoundation/www_threefold_io/assets/50134479/244f6164-bd28-4369-81ef-97d21c58a831)

@scottyeager What do you think is the best way to approach?

**Comment by scottyeager** [comment]
I think standby nodes should be included in these figures. Already wrote the code: https://github.com/threefoldfoundation/www_threefold_io/pull/286. If we have sufficient consensus on the approach, can merge that PR and it will be done.

**Comment by samtaggart** [comment]
@Mik-TF Good point. cc: @scottyeager

**Comment by scottyeager** [comment]
I agree with @Mik-TF, and that's what my proposed code changes do: just show a total count that includes all online nodes and standby nodes.

**Comment by samtaggart** [comment]
Let's revisit this as a team this evening and bring an updated proposal

**Comment by samtaggart** [comment]
The numbers are consistent as compared to previously.
Will check one more time with the team before making the decision on this issue.
