### ISSUE TITLE
email button is misleading

### ISSUE THREAD

**Issue by xmonader** [threefoldfoundation/www_threefold_io#301]
I thought i'd be sending an email to threefold not signing up for a newsletter

![image](https://github.com/threefoldfoundation/www_threefold_io/assets/64129/e5892c17-c840-4069-8e92-3b3b471d9b10)

**Comment by samtaggart** [comment]
@ehab-hassan @samaradel Can we please replace the icon with something that better demonstrates it is for a newsletter? Something like the below. Please try and judge for yourself which looks best / is still legible at such a small size.

![newsletter](https://github.com/threefoldfoundation/www_threefold_io/assets/50134479/557c63d3-e9c4-4b2b-9fa7-cb0428ddff46)

**Comment by samtaggart** [comment]
@amandacaster will bring a couple new recommendations and then we will pass it off to Ehab.

**Comment by samtaggart** [comment]
We will add to the footer and get rid of the newsletter icon at the top. I will take care of this today.

**Comment by samtaggart** [comment]
Need help from someone on the web team:

1. We need to remove the newsletter icon from the header
2. Remove People and Partners from ABOUT US in the footer
3. New order should be About, Blog, Newsroom, Newsletter (and link Newsletter to the pop up that we currently have in the header)

**Comment by ehab-hassan** [comment]
done at staging
https://dev.threefold.io/

**Comment by samtaggart** [comment]
Confirmed, closing.
