### ISSUE TITLE
The website feels like scattered information 

### ISSUE THREAD

**Issue by xmonader** [threefoldfoundation/www_threefold_io#307]
I'm sorry, but it feels like lots of items are not well-connected, not to the point, and other things are hidden e.g Blog (I'd have expected the blog to be more visible

also that more section is very weird, it feels like we just collected things and put it there I don't think i ever saw such anywhere

![image](https://github.com/threefoldfoundation/www_threefold_io/assets/64129/61cc3916-24e9-4d1d-9318-393839079cdf)

More = information I can discard

I suggest that

- remove github (already exists on the footer)
- newsroom (exists on the footer)
- make blog a main item in the menu
- careers item to be moved to the footer (how is it possible it's under help and support?)
- Move manual to or Help to a help button maybe in the menu

get rid of the dive deeper (news and intro docs are never dive deeper items)

**Comment by samtaggart** [comment]
As for the general feeling of scattered info, I am working on that as part of the overall process. For the menu, I've made the adjustments here.

<img width="1421" alt="Screen Shot 2023-12-07 at 11 39 13" src="https://github.com/threefoldfoundation/www_threefold_io/assets/50134479/18787e18-13a0-41ac-afed-8a64ab066975">
