### ISSUE TITLE
depin+threefold mention

### ISSUE THREAD

**Issue by Mik-TF** [threefoldfoundation/www_threefold_io#308]
Can we mention the link between threefold and depin on the website?

A lot of TF community members, new and old timers, have been discussing the relation between depin and TF.

We can have direct links between the website and the manual, once manual content on depin is done. See [this](https://github.com/threefoldtech/info_grid/issues/314).

**Comment by samtaggart** [comment]
@Mik-TF Good suggestion. Where do you see this living and how? Or are you not sure?

**Comment by Mik-TF** [comment]
Not sure, indeed. But perhaps #depin somewhere around here:

![image](https://github.com/threefoldfoundation/www_threefold_io/assets/77026219/2d79b6f1-6917-40c4-bb7e-df104566e4fe)

And then a direct link (next to de hashtag) leading to the TF manual once we have [content](https://github.com/threefoldtech/info_grid/issues/314) on how ThreeFold is related to depin.

**Comment by samtaggart** [comment]
Let's discuss this as a team this evening and then potentially bring it to biz dev / INCA team.

**Comment by samtaggart** [comment]
For now this message is being played up with Project Internet Capacity, so actually I think we are OK here.
