### ISSUE TITLE
Streamline Grid Page

### ISSUE THREAD

**Issue by samtaggart** [threefoldfoundation/www_threefold_io#310]
The Grid page should explain how the grid works and what has been created / how it is so different compared to other projects which are much more limited. Right now there is a lot of information but now real flow.

To brainstorm with @scottyeager and @Mik-TF.

**Comment by Mik-TF** [comment]
*  who understood the problems of the centralized Internet first-hand -->  who understood first-hand the problems of a centralized Internet
* with demand -> with the demand
* open source --> open-source
* low level -> low-level
* globally distributed -> globally-distributed
* in the form of TFT --> in the form of ThreeFold tokens (TFT)

* If possible, I would make the paragraphs more compact. It's almost on the picture

![image](https://github.com/threefoldfoundation/www_threefold_io/assets/77026219/547c051b-2cba-459a-aa7e-3465c5dcc3df)

* I would put how it works CTA button lower in the page, maybe under "A New Internet Blueprint

* I would add that the nodes are self-healing
* I would add something on quantum safe file system

Overall I think you explain well the basic features of the grid.

**Comment by samtaggart** [comment]
New iteration live – [www.threefold.io](http://www.threefold.io/)
