### ISSUE TITLE
Streamline Build Page

### ISSUE THREAD

**Issue by samtaggart** [threefoldfoundation/www_threefold_io#311]
The build page should clearly state the capabilities of the grid. It should be very action oriented and less informational. Grid page is for information / how. Also see this issue: https://github.com/threefoldfoundation/www_threefold_io/issues/300

To brainstorm with @scottyeager and @Mik-TF.

**Comment by Mik-TF** [comment]
* "created, or access raw disk on the location of your choice." --> " created. Access raw disk on the ... "
* explore capacity url could be this url https://dashboard.grid.tf/explorer/statistics (leading directly to the explorer)
* the grid tester chat is there 2 times as URLs. I would only put one. maybe remove the one in "more resources"
* It is Deploy in the menu, but build in the url. We should choose one of the two. Maybe Build
* we have 3 icons presenting info so far, autonomous compute, quantum safe storage, peer-to-peer network
   * I would add 6 more icons with content, to present the capabilities of the grid
   * e.g.
      * GPU
      * Terraform and Pulumi
      * Ready-community solutions with the Playground
      * Seamless integration of docker image with flist
      * Go and Javascript Client
      * TFGrid CLI

**Comment by samtaggart** [comment]
New iteration live – [www.threefold.io](http://www.threefold.io/)
