### ISSUE TITLE
Streamline Farm Page

### ISSUE THREAD

**Issue by samtaggart** [threefoldfoundation/www_threefold_io#312]
The Farm page should be focused on how farming works and how to farm. I think it does a pretty good job at the moment (apart from graphics needing to be updated).

Brainstorm with @scottyeager and @Mik-TF.

**Comment by Mik-TF** [comment]
Farm page looks good indeed. Some ideas:

* Threefold -> ThreeFold
* We are growing fast -> We are growing fast!
* "3Nodes provide Internet capacity for millions of people"
   * is it true as of now? Millions

**Comment by samtaggart** [comment]
New iteration live – [www.threefold.io](http://www.threefold.io/)
