### ISSUE TITLE
Look into adding an RSS feed into the website for blog or newsroom

### ISSUE THREAD

**Issue by samtaggart** [threefoldfoundation/www_threefold_io#315]
A partner is asking if we have plans to introduce RSS as they would like to pull content from our blog and/or newsroom. I don't know a lot about RSS, need some investigation. Would it work with the way that we publish content?

**Comment by Mik-TF** [comment]
Interesting!

Since the website is in zola, I can be done directly within the config.toml file ([see here](https://www.getzola.org/documentation/templates/feeds/))

**Comment by samaradel** [comment]
implemented on staging, check please [ThreeFold](https://www2.threefold.io/atom.xml)

**Comment by Mik-TF** [comment]
@samaradel Nice!

I tested https://www2.threefold.io/atom.xml on https://rssviewer.app/ and it works well.

**Comment by samaradel** [comment]
implemented on [staging](https://www3.threefold.io/atom.xml)
