### ISSUE TITLE
Check on analytics for threefold.io

### ISSUE THREAD

**Issue by samtaggart** [threefoldfoundation/www_threefold_io#316]
Please make sure analytics are properly set up, there seems to be an issue.

**Comment by ehab-hassan** [comment]
we used Matomo for analytics I think it works for tracking
![image](https://github.com/threefoldfoundation/www_threefold_io/assets/10484295/13c1ca5b-f47e-498c-ab82-ae5275f79cd2)

![image](https://github.com/threefoldfoundation/www_threefold_io/assets/10484295/5e21ceb6-cc95-4e6d-ac82-a428225b1d33)




https://analytics.threefold.io/index.php?module=CoreHome&action=index&idSite=5&period=day&date=yesterday#?period=day&date=yesterday&category=Dashboard_Dashboard&subcategory=1

**Comment by ehab-hassan** [comment]
done

> Ah OK OK sorry, can you please ping me privately with my login details? @ehab-hassan

**Comment by samtaggart** [comment]
For sure something is up though.

e.g. Not showing any website visitors from Tanzania in the past month. This can't be possible.

**Comment by despiegk** [comment]
please complete the info on https://git.ourworld.tf/threefold_coop/info_tfcoop_internal/src/branch/main/collections/itinfo/web_stats.md

**Comment by ehab-hassan** [comment]
> please complete the info on https://git.ourworld.tf/threefold_coop/info_tfcoop_internal/src/branch/main/collections/itinfo/web_stats.md

this info can be filled in by OPS @PeterNashaat can u check this

**Comment by samtaggart** [comment]
Thanks @PeterNashaat should I assign you?

**Comment by PeterNashaat** [comment]
- Deployment docs and access are [here](https://docs.grid.tf/threefold/itenv_threefold_main/src/branch/master/deployments/lochristi_dc/matomo) .

**Comment by PeterNashaat** [comment]
- i've referenced my docs as it's better to keep all docs in one place.
