### ISSUE TITLE
profile pictures missing home page

### ISSUE THREAD

**Issue by Mik-TF** [threefoldfoundation/www_threefold_io#317]
* see here

![image](https://github.com/threefoldfoundation/www_threefold_io/assets/77026219/ad7cb660-dc44-4f2e-a228-9b71f45c68b7)

* profile pictures are missing

**Comment by ehab-hassan** [comment]
fixed at staging https://www2.threefold.io/community/

**Comment by ehab-hassan** [comment]
ll close this issue because it is updated at production
https://www.threefold.io/community/
