### ISSUE TITLE
Wikis & all websites - Remove information about "buy TFT"

### ISSUE THREAD

**Issue by maximilianrang** [threefoldfoundation/www_threefold_io#32]
A new TFT investor pointed out that there is still information out there how to buy TFT directly from Mazraa and farmers.

"Directly from a Farmer
You also have the option to buy directly from either:

Mazraa
BetterToken
With some conditions, this can be done quite easily."

To be in line with our new strategy, this has to be removed.

**Comment by samtaggart** [comment]
Removed, will be pulled in by Sunday.
