### ISSUE TITLE
Facing issues of not able to build website locally.  

### ISSUE THREAD

**Issue by amandacaster** [threefoldfoundation/www_threefold_io#329]
I have been facing multiple errors while trying to build a website locally.  @samaradel has helped me in the past and she fixed the issue but the next time I use the same commands that fixed the issue I get another error. 

The laptop is a Dell Inspiron 3rd Gen running with Windows 10. I am using VScode as the editor with Gitbash.

**Comment by amandacaster** [comment]
@AhmedHanafy725 as requested. 

This what I see now
![image](https://github.com/threefoldfoundation/www_threefold_io/assets/88147124/25c66e43-817b-4dd6-afc1-18eb6386fce0)

**Comment by ehab-hassan** [comment]
@amandacaster if this is done while you use Ubuntu now close it please.

**Comment by despiegk** [comment]
timur is on it
