### ISSUE TITLE
Old Telegram Chat - Delete

### ISSUE THREAD

**Issue by maximilianrang** [threefoldfoundation/www_threefold_io#33]
I would recommend to delete the old channel. Ppl are still finding it and will join as the search function of Telegram is pretty advanced now. We can give a final notice to migrate.

**Comment by Karoline888** [comment]
Yes agreed, after 6 months there was enough transition time, so ppl who haven't yet are apparently not active... with 1 day notice let's delete the old one and push the new one :-) Thanks Sam!

**Comment by samtaggart** [comment]
The owner of the group should be able to "Delete and Leave" a Telegram group but @nbabenko has no such option. Next best options, if we can't figure it out...

- We could manually remove all 1,000 people (this would take about an hour to do).
- We could delete the whole chat history and keep one message there.

Anything else?

**Comment by maximilianrang** [comment]
We could install a bot that kicks ppl upon joining and tells them to join the new chat. Amazix can set this up for us.

**Comment by samtaggart** [comment]
We're going to wait to see if we move forward with Amazix and then they will be able to advise here. First convo on Wednesday

**Comment by Karoline888** [comment]
Thank you for the update. Highly appreciated. Curious what the next step is after talking with Amazix on Wed.
have a great start of the week

**Comment by samtaggart** [comment]
We will address this with Amazix this week as we are onboarding on Tuesday.

**Comment by samtaggart** [comment]
Group deleted.
