### ISSUE TITLE
Generate and implement file with all manual+exterior URLs

### ISSUE THREAD

**Issue by Mik-TF** [threefoldfoundation/www_threefold_io#337]
# Feature Request

- Generate and implement file with all manual+exterior URLs
  - e.g. as a yaml file: Buy_TFT: [https://manual.grid.tf/threefold_token/buy_sell_tft/buy_sell_tft.html](https://manual.grid.tf/threefold_token/buy_sell_tft/buy_sell_tft.html) 
- Within the website files, we call the general variable and it uses its associated URL
  - in the case above, we'd have something like: You can learn more about how to buy TFT by reading the \[manual\]\(Buy_TFT\)

# Advantages

- If URLs are updated on the manual, we can simply update the one file within the www_threefold_io repo, and the URLs within the whole website will be updated

Idea from @xmonader, as discussed in implementing this for tfgrid-sdk-ts, we can also implement it for the threefold.io website.

**Comment by samtaggart** [comment]
@Mik-TF A bit confused on this one, can you clarify? Not sure what needs to be done and by who

**Comment by Mik-TF** [comment]
The dashboard uses this: https://github.com/threefoldtech/tfgrid-sdk-ts/blob/development/packages/playground/src/utils/manual.ts

I think you could check for the URLs needed on threefold_io and a dev could set the implementation in the website repo.

**Comment by Mik-TF** [comment]
Not needed with new UI/UX.
