### ISSUE TITLE
Website doesn't render well on laptop screen

### ISSUE THREAD

**Issue by xmonader** [threefoldfoundation/www_threefold_io#344]
this is 100% 

![image](https://github.com/threefoldfoundation/www_threefold_io/assets/64129/aba04373-80e4-4fc7-8eef-b4b099d3746d)

As you can see this seems to be too big, too many spaces, and the support icon is overlaying and this is how it looks on 67%
![image](https://github.com/threefoldfoundation/www_threefold_io/assets/64129/00e993b1-7043-42d3-a339-96cae3d1f670)

**Comment by samtaggart** [comment]
@ehab-hassan Can you look into this and consult @xmonader if you have any questions or clarifications?

**Comment by ehab-hassan** [comment]
Ok I think we can make images smaller also I think we can hide the tags from here and leave them inside person page

**Comment by samtaggart** [comment]
@ehab-hassan Can you confirm with @xmonader if he is just referring to this page in particular or other pages as well?

**Comment by ehab-hassan** [comment]
it'll be like this at small screens 100%
![image](https://github.com/threefoldfoundation/www_threefold_io/assets/10484295/d6567cba-f146-4e6b-a528-c428d70b469d)

at big screen 1920
![image](https://github.com/threefoldfoundation/www_threefold_io/assets/10484295/67d633a6-c8cb-48a1-bd1a-33499e5beeac)

@xmonader please check at https://dev.threefold.io/people/

ll do the same for News and Blog

**Comment by samtaggart** [comment]
Hi @ehab-hassan were you able to execute this for blog and newsroom yet? I can't tell.

**Comment by ehab-hassan** [comment]
@samtaggart not yet ll check it soon

**Comment by samtaggart** [comment]
Hi @ehab-hassan What is the progress here? It looks like this has been updated for blog but not newsroom?

**Comment by samtaggart** [comment]
This has been completed for people and blog. News is in a separate issue.
