### ISSUE TITLE
How it works section, about, not good enough

### ISSUE THREAD

**Issue by xmonader** [threefoldfoundation/www_threefold_io#346]
![image](https://github.com/threefoldfoundation/www_threefold_io/assets/64129/096b7550-6485-4c8a-a549-52bcb8a3a578)

this is unusable

**Comment by despiegk** [comment]
I agree
the https://www.threefold.io/host/ how it works doesn't say much

I don't think anyone will understand how it works from this, maybe some more context would be great
maybe link to manual?
