### ISSUE TITLE
Join in section

### ISSUE THREAD

**Issue by xmonader** [threefoldfoundation/www_threefold_io#347]
![image](https://github.com/threefoldfoundation/www_threefold_io/assets/64129/c031e455-16ef-4051-a907-89694712eea2)

It seems to be redundant and adding too much noise, given the data is already in the footer?

**Comment by samtaggart** [comment]
This was adjusted a while back.

<img width="1378" alt="Screenshot 2024-06-21 at 10 38 16" src="https://github.com/threefoldfoundation/www_threefold_io/assets/50134479/cdfa9eb4-8967-4cd5-94e0-093a36454b73">
