### ISSUE TITLE
Shouldn't we merge blog and news?

### ISSUE THREAD

**Issue by xmonader** [threefoldfoundation/www_threefold_io#350]
Both seems to be overlapping?

**Comment by despiegk** [comment]
no, they are very distinct but maybe not how we do it here

blogs are stories, news are things which happened and go away over time

**Comment by despiegk** [comment]
but we can see why its confusing now, team will adjust

**Comment by samtaggart** [comment]
Duplicate issue, will address here https://github.com/threefoldfoundation/www_threefold_io/issues/357
