### ISSUE TITLE
we need 1 page per utilization partner

### ISSUE THREAD

**Issue by despiegk** [threefoldfoundation/www_threefold_io#352]
https://www.threefold.io/utilization/

- we need 1 page per 
- implement using our blog framework, we can then link to it
- we need to explain per partner
    - why did they chose us
    - what are they going to do on us
    - roadmap of what comes by when
    - what will user be able to do with it
    - how does it work
    - link to demo's

**Comment by samtaggart** [comment]
For now I have made improvements to the writeups for each partner on the utilization page. We will tackle this next week, need a meeting with Kristof to dig into each of these.

**Comment by samtaggart** [comment]
For reference: https://git.ourworld.tf/threefold_coop/circle_promotion/issues/97

**Comment by samtaggart** [comment]
Amanda and Emilie will work on getting these live on threefold_data.

@ehab-hassan Can you please apply the same CSS changes to https://www.threefold.io/partners/ as well?

Also is there a way to hide old projects? Same as we did for threefold_community under people page?

**Comment by emilieo** [comment]
All partners been added here: https://dev.threefold.io/partners/ 

Waiting for a demo video for Vverse and @ehab-hassan is helping to make this video https://vimeo.com/919967495/340e62170b?share=copy public so we can embed it on the sovereign internet in tanzania partner page

**Comment by samtaggart** [comment]
Thanks @emilieo I've gone through and made some updates now live on dev.threefold.io.

**Comment by samtaggart** [comment]
@ehab-hassan Can you please apply the same css filters to the partner page on threefold.io so that it is thinner?

**Comment by ehab-hassan** [comment]
> @ehab-hassan Can you please apply the same css filters to the partner page on threefold.io so that it is thinner?

sure
