### ISSUE TITLE
get hero usable for this website

### ISSUE THREAD

**Issue by despiegk** [threefoldfoundation/www_threefold_io#353]
with quick manual & heroscript as example in this repo

## deliverables

- [ ] link to manual where it gets explained how to use it
- [ ] link to how to use our components
- [ ] link how to use collections as blogs, news, ...
- [ ] check the css, there seem to be some issues
- [ ] heroscript example 
- [ ] link to install of hero

**Comment by despiegk** [comment]
please put instructions on https://github.com/threefoldfoundation/www_threefold_io homepage

use the newest hero please, zola features should be in hero

**Comment by timurgordon** [comment]
https://github.com/freeflowuniverse/crystallib/tree/development_zola/examples/webtools/zola/threefold_heroscript example builds the development threefold website.

The following repos must be checked out in the `development_zola` branch
- `threefoldfoundation/www_threefold_io`
- `threefoldfoundation/threefold_data`
- `freeflowuniverse/crystallib`
- `freeflowuniverse/webcomponents`

Remaining work: 
- fix footer template and create component in webcomponents
- correct formation of md files' front matter (yaml) in `threefold_data`
- parsing links inside links: some images are placed inside links, and the `doctree` module fails to recognize these as links of images and thus fails to fix and export. example: `[![Image](.../.../)](.../.../)`

deliverables and documentation is being created as a site itself using hero & Zola

**Comment by timurgordon** [comment]
parsing links inside links fixed with 264fc10bd5df9839caeb9b204afa372538df8010

**Comment by samtaggart** [comment]
Hi @timurgordon just checking in, what is the status here?

**Comment by samtaggart** [comment]
Hi @timurgordon Will this be complete before the end of the weekend? I'd like to open a new project for next week.

**Comment by Mik-TF** [comment]
Status?

**Comment by Mik-TF** [comment]
Closing for now. We focus on 12.12.24.
