### ISSUE TITLE
news: Sovereign internet: A game changer to Tanzania

### ISSUE THREAD

**Issue by despiegk** [threefoldfoundation/www_threefold_io#354]
https://docs.google.com/document/d/1Zw8hbAfbwm5uST6_zPm2Gr6e_L4tuVj_ecIyR_uCkN0/edit#heading=h.l3mcviioimzi

then link from news into this one (news is just very small link to this longer doc), need to have the video

then create partner page for Tanzania and link back to this blog too

we need much more meat and make big thing from this

## deliverables

- [x] video with subtitles (we have at least 2), put on vimeo and embed
- [ ] do we have video extracts from event itself maybe some elements of moses can be used
- [x] newspaper articles (for the paying one we can show picture not of everything but like 60% and then link to news website)

**Comment by despiegk** [comment]
see also https://www.threefold.io/newsroom/duniayetulaunchdar/

**Comment by marionrvrn** [comment]
Video 1 with eng subtitles: https://vimeo.com/manage/videos/920060589/d033b79295
Video 2 : https://vimeo.com/manage/videos/919967495/340e62170b
