### ISSUE TITLE
news: threefold signs agreement with government of Zanzibar for Digital Freezone

### ISSUE THREAD

**Issue by despiegk** [threefoldfoundation/www_threefold_io#355]
- date aug
- need to find video president where he speaks
- coverage on newspapers
- explain why relevant, we as threefold will empower this project with our technology
    - we deliver the digital backbone, 
    - we deliver our hero as ...
    - we deliver 3nodes
    - we agreed with government to also work on future internet project for full island
    - we are investigating how to do incubation with government

**Comment by emilieo** [comment]
First draft here: https://docs.google.com/document/d/1KfbF_rgGEQFY9gu5ONXwd766L8VE2fd8nOa-Cbiroys/edit?usp=sharing

**Comment by samtaggart** [comment]
@emilieo Please take a look here at the videos we have: https://drive.google.com/drive/folders/1oykc8MbEjBI0MadnTCETLt3CV7ofTrI5?usp=drive_link

**Comment by emilieo** [comment]
cut down one video for the news article and uploaded it to the drive under the name "Free Zone President Speech (cut down for news).mp4"
