### ISSUE TITLE
people page

### ISSUE THREAD

**Issue by despiegk** [threefoldfoundation/www_threefold_io#356]
- community is not a person
- the filter does not work
- maybe we need to add something about our experience? didn't we have something like this in past?

**Comment by despiegk** [comment]
why not have our story here, we are these internet pioneers, we worked on ...
we made this, we made that, ...
but in a fun not ego way

**Comment by samtaggart** [comment]
Re: the above:

- "Community is Not a Person" is being resolved in another issue (#345)
- Filter also being addressed in another issue (#343)

@marionrvrn Can you conceptualize something with Sasha and we can execute on it early next week? It can also be a header which points to the About page

**Comment by samtaggart** [comment]
This is satisfied by the about page for now, which we will improve in next iteration.
