### ISSUE TITLE
blog three-layer not interesting enough

### ISSUE THREAD

**Issue by despiegk** [threefoldfoundation/www_threefold_io#358]
https://www.threefold.io/blog/three-layers/

- we should not use non saying pictures, this is distracting,
- the article should be more structured, make it easier to read
- use more images maybe but ones who say something

don't get hang up on the style too much, maybe make a video and explain what you mean, maybe its a good idea we organize some zoom sessions where we talk about a topic and make it come alive

e.g. what was the internet how does it work, ... but we can go in steps, like now its not interesting enough

**Comment by emilieo** [comment]
Updated article in this document: https://docs.google.com/document/d/1E6DlK69Oj_8qOuisAVB36BEFpIi1x2UizMtP96q_36s/edit#heading=h.d21ejoo502t9 

Need to check and then update on website
Look into creating video content

**Comment by emilieo** [comment]
changes have been committed to development branch
