### ISSUE TITLE
only link to new UI

### ISSUE THREAD

**Issue by despiegk** [threefoldfoundation/www_threefold_io#359]
<img width="890" alt="image" src="https://github.com/threefoldfoundation/www_threefold_io/assets/6021844/02e9bb4a-e65f-4d47-9e5e-6ef0edf54ec8">

dont have old and new, we need to check manual too to only use new one

**Comment by samtaggart** [comment]
I will change on the website but this should be solved organically, right?

Won't next.dashboard.grid.tf become dashboard.grid.tf when TF Grid 3.13 goes to mainnet?

**Comment by samtaggart** [comment]
Updated two links to the dashboard on the website to next.dashboard.grid.tf
