### ISSUE TITLE
show how we are different in communication across web presence

### ISSUE THREAD

**Issue by maximilianrang** [threefoldfoundation/www_threefold_io#36]
We are expecting more visitors that come from the crypto world and want to learn more about who we are. As threefold.io is the main website that we communicate on coinmarketcap and other portals it will be the to-go website for this valuable target audience.

For more precise communication on what we are, we would like to add a 2 column section. The left column is what we are not, right column is what we are.

**HEADLINE: NOT YOUR AVERAGE CRYPTO PROJECT**
**Headline left column - IF YOU ARE LOOKING FOR THESE THINGS, PLEASE MOVE ON**
**Headline right column - WE ARE P2P**

We are not a blockchain -> But we are utilizing blockchain
No ICO or pump&dump -> But our token is from 2018
and a few more lines like this

**Comment by samtaggart** [comment]
@maximilianrang To provide a better description and we can get this done ASAP.

**Comment by Sacha96** [comment]
@samtaggart we need to use above language on platforms such as cooinmarketcap etc.. leading to main.io prior this week.
