### ISSUE TITLE
blog/solar-comparison update

### ISSUE THREAD

**Issue by despiegk** [threefoldfoundation/www_threefold_io#360]
https://www.threefold.io/blog/solar-comparison/

- the picture who matters (at bottomn), is too low quality
- maybe have other picture too (there are 2 in this)
- the one at top doesn't say much, not sure it adds value like this

**Comment by emilieo** [comment]
Updated images on this document: https://docs.google.com/document/d/1E6DlK69Oj_8qOuisAVB36BEFpIi1x2UizMtP96q_36s/edit#heading=h.d21ejoo502t9

**Comment by emilieo** [comment]
new images have been committed to development branch
