### ISSUE TITLE
Support page?

### ISSUE THREAD

**Issue by xmonader** [threefoldfoundation/www_threefold_io#365]
It was referenced in some of the projects and now it's gone.

**Comment by samtaggart** [comment]
Hi @xmonader what do you mean that it was "referenced in some of the projects" ?

**Comment by samtaggart** [comment]
Support now links directly to the crisp chat.

**Comment by xmonader** [comment]
I can't use an external link like crisp.net in apple store or android store. ![Screenshot_2024-03-11-09-34-07-909_com.android.chrome.jpg](https://github.com/threefoldfoundation/www_threefold_io/assets/64129/03b53807-23dd-4b88-91fa-125aeefd5f9e)

**Comment by samtaggart** [comment]
OK fair enough, we will come up with a quick support page and push this asap.

**Comment by samtaggart** [comment]
Brought back live for now. We can always improve.

https://threefold.io/support/
