### ISSUE TITLE
What does buy hosting and sell hosting mean 

### ISSUE THREAD

**Issue by xmonader** [threefoldfoundation/www_threefold_io#366]
![IMG_20240307_170651_168.jpg](https://github.com/threefoldfoundation/www_threefold_io/assets/64129/ebd0edd8-4094-4cdd-b072-8ea5b4ba456f)

**Comment by Mik-TF** [comment]
It isn't clear at all I agree.

- Buy Cloud Resources
- Sell Cloud Resources

perhaps?

**Comment by samtaggart** [comment]
Where do you see this @xmonader ? It's not on our website ...

**Comment by samtaggart** [comment]
Think this must have been on an old version or an unpublished branch because we don't use that terminology anywhere on the website.
