### ISSUE TITLE
Suggestion to display all prices in same currency

### ISSUE THREAD

**Issue by sabrinasadik** [threefoldfoundation/www_threefold_io#37]
Received a message on the live chat with a suggestion to put all prices on the website either in EUR or in USD, not both since this seems to be confusing.

"I'm looking at your webpage ( https://new.threefold.io/cloud/#pricing ), and prices are in EUR, but on the same page is this message: "The equivalent amount will be billed in TFT at a TFT price of 0.10 USD." This is confusing, to have prices in EUR and USD on the same page?! Maybe you should fix that."

**Comment by samtaggart** [comment]
Thanks @sabrinasadik we actually already addressed this. Put prices on website into USD.

**Comment by sabrinasadik** [comment]
Addressed or planned to address? Because it still says EUR on the website

**Comment by samtaggart** [comment]
Sorry – it's live on local, it will be updated in the next push which should be later today.

<img width="1009" alt="Screen Shot 2021-03-23 at 6 20 36 PM" src="https://user-images.githubusercontent.com/50134479/112170983-8b508580-8c04-11eb-9701-50bac55e1215.png">
