### ISSUE TITLE
team data

### ISSUE THREAD

**Issue by xmonader** [threefoldfoundation/www_threefold_io#370]
currently the team data is managed and updated at https://github.com/threefoldfoundation/threefold_data, I noticed that this repo also has an outdated copy of the data, and that shouldn't be the case. threefold_data repo should be the source of truth

**Comment by samtaggart** [comment]
Yes, known issue, I am working on this with @timurgordon asap

**Comment by samtaggart** [comment]
I had intended to move this issue here: https://git.ourworld.tf/threefold_coop/circle_promotion/issues/92

**Comment by timurgordon** [comment]
threefold_data will be the single source of team data, we were adding people to the _io repo manually but it will begjn to pull from threefold_data when the switch to the new building dcropt is completed

**Comment by samtaggart** [comment]
Hi @timurgordon thanks, please share updated progress. I would like to close this project by the end of the weekend and get started on the next one.

**Comment by samtaggart** [comment]
Talking with Timur today.

**Comment by Mik-TF** [comment]
Status?

**Comment by samtaggart** [comment]
cc: @timurgordon

As far as I can tell this was never implemented and probably needs to stay on the backburner for now, but let's see what Timur says.

**Comment by Mik-TF** [comment]
Good. Closing for now. We have people page which is fine with basic info.
