### ISSUE TITLE
dashboard.grid.tf is not found 

### ISSUE THREAD

**Issue by Nayer-Sobhy** [threefoldfoundation/www_threefold_io#374]
when clicking on the Explore Threefold Grid capacity 
<img width="1433" alt="Screenshot 2024-03-12 at 11 17 43 AM" src="https://github.com/threefoldfoundation/www_threefold_io/assets/14869003/ce15613f-579f-4afa-8783-d5465055e02b">

I get 404 page not found error 
https://dashboard.grid.tf/explorer/statistics
<img width="1437" alt="Screenshot 2024-03-12 at 11 18 02 AM" src="https://github.com/threefoldfoundation/www_threefold_io/assets/14869003/957298d1-dbe6-407e-9c9d-5b737267faaf">

**Comment by samtaggart** [comment]
Updated on development, will be updated on production later today!
