### ISSUE TITLE
no links to the icons 

### ISSUE THREAD

**Issue by Nayer-Sobhy** [threefoldfoundation/www_threefold_io#375]
Shouldn't these icons be hyperlinks to more info about each one in a new page or redirecting to the bottom of the page with info. Maybe even a popup info when the user hover on it 
<img width="1439" alt="Screenshot 2024-03-12 at 11 20 05 AM" src="https://github.com/threefoldfoundation/www_threefold_io/assets/14869003/6d086c36-6559-4781-9f2e-e59dabf5d685">

**Comment by Mik-TF** [comment]
Yeah @scottyeager wrote an isue for this: https://github.com/threefoldfoundation/www_threefold_io/issues/372

It's missing the numbers! We can close this issue in favor of the other, as it covers the same problem.

**Comment by scottyeager** [comment]
I think the issues are different enough to keep both. Mine is just about adding number, not about making the elements interactive.

On the second point, I guess it depends on what we want to do with the user journey. Is this a jumping off point for further exploration via some links? Is it a place to stop and learn more via popups? Or is the purpose just to impress with the quantity of capacity available as a stop along reading this page?

To me these as non interactive elements is okay, but I'm open to doing something more with them too.

**Comment by samtaggart** [comment]
Talked with Amanda.

We want to look into the feasibility of hover text. (Amanda will check with Sasha Astiadi on what the possibilities are here.)

Then we need to develop the hover text and implement.

The idea is that the hover text will be educational / providing context on what e.g. capacity or CPU cores means.

**Comment by sasha-astiadi** [comment]
what would the hover text be? the description of each item, or the numbers / amount of live data pulled from the explorer? @samtaggart @scottyeager

**Comment by samtaggart** [comment]
No the hover text would be some kind of educational text about what "capacity" means or "cores" etc. It would be static text not live data.

**Comment by samtaggart** [comment]
Is this possible? @sasha-astiadi @ehab-hassan

**Comment by ehab-hassan** [comment]
![image](https://github.com/threefoldfoundation/www_threefold_io/assets/10484295/999af4a3-6413-4cdd-b74d-2c44d3a28b31)

@samtaggart I added a tooltip it ll be like this when hovering but needs text to be shorter may maximum 10 words.

**Comment by ehab-hassan** [comment]
updated at staging

**Comment by samtaggart** [comment]
OK! I edited the text a bit, but kept it so it does not cover up any information.
