### ISSUE TITLE
site can't provide a secure connection  https://next.dashboard.grid.tf/

### ISSUE THREAD

**Issue by Nayer-Sobhy** [threefoldfoundation/www_threefold_io#376]
when clicking on Visit the dashboard from https://threefold.io/host/
<img width="1436" alt="Screenshot 2024-03-12 at 11 24 56 AM" src="https://github.com/threefoldfoundation/www_threefold_io/assets/14869003/c4b58532-9671-4276-962e-ff9e7dd3804b">

I get directed to https://next.dashboard.grid.tf/ and I get 
<img width="1432" alt="Screenshot 2024-03-12 at 11 24 35 AM" src="https://github.com/threefoldfoundation/www_threefold_io/assets/14869003/f8690ea9-6151-46f0-af3c-552a2b0e06dc">

**Comment by samtaggart** [comment]
Thank you. Fixed on development, will move to production today!
