### ISSUE TITLE
Create community page – with support as a key section

### ISSUE THREAD

**Issue by amandacaster** [threefoldfoundation/www_threefold_io#378]
Why don't we use the support page as a page for all community channels by categorizing them under their use for example 

<ul>
<li> Looking for the team to support you resolve an issue </li>
<ul>
<li> Crisp</li>
<li> Github</li>
<li> Support email / info email address</li>
</ul>
</ul>
<ul>
<li> Looking to support the team and the community</li>
<ul>
<li> Main Telegram</li>
<li> Farmers chat (Telegram)</li>
<li> Grid Testers (Telegram) </li>
<li> Forum </li>
</ul>
</ul>
<ul>
<li> News & updates </li>
<ul>
<li> Telegram News & Updates </li>
<li> Reddit</li>
<li> X - Twitter </li>
<li> LinkedIn </li>
</ul>
</ul>
<ul>
<li> Documentation & Tutorials </li>
<ul>
<li> Manual</li>
<li> Youtube </li>
<li> Substack </li>
<li> Medium </li>
</ul>
</ul>

**Comment by samtaggart** [comment]
@ehab-hassan Can you help here? Just want something simple. Feel free to enhance / improve.

We used to have these icons on the home page but we removed. I can't find the code but maybe you can on GitHub?

![community_page](https://github.com/threefoldfoundation/www_threefold_io/assets/50134479/cad597f7-675f-4f83-b749-59065619e314)

Then for the calendar, you can use the below embed code.

<iframe src="https://calendar.google.com/calendar/embed?height=600&wkst=2&ctz=Europe%2FBrussels&bgcolor=%23ffffff&title&showTitle=0&showPrint=0&showCalendars=0&src=Y185OGMwNTEwZDVlMmMzMGY1MGM1NTNmZmUxZDNiOTRjMTliMzRmNTNiNDhhNzY3NjdkNDEyNTU3ZjVhYzc1ODAyQGdyb3VwLmNhbGVuZGFyLmdvb2dsZS5jb20&color=%2333B679" style="border:solid 1px #777" width="800" height="600" frameborder="0" scrolling="no"></iframe>

- [ ] Create community page
- [ ] Update link on home page "Join the Community" (last section) to community page
- [ ] Add Community to footer under Newsletter
- [ ] On Support page, update "Other Channels" button to Community page

**Comment by ehab-hassan** [comment]
@samtaggart need links for telegram groups

updated at staging

**Comment by samtaggart** [comment]
OK I added links and fixed some typos. Thanks!
