### ISSUE TITLE
odd double hr tags in the team page

### ISSUE THREAD

**Issue by xmonader** [threefoldfoundation/www_threefold_io#382]
![image](https://github.com/threefoldfoundation/www_threefold_io/assets/64129/1c18405d-fe73-44b5-be0b-77eca5931a75)

**Comment by samtaggart** [comment]
@ehab-hassan needs to look into this.

**Comment by ehab-hassan** [comment]
fixed at development
![image](https://github.com/threefoldfoundation/www_threefold_io/assets/10484295/87b8657a-6911-4fe5-81ef-ff65e698e332)
