### ISSUE TITLE
Re-tag all newsroom posts and blog articles

### ISSUE THREAD

**Issue by samtaggart** [threefoldfoundation/www_threefold_io#383]
We need to re-tag all newsroom posts and blog articles but there are way too many of them to go through.

- [x] @timurgordon Quickly write a script to pull all of the newsroom posts and blog articles at www_threefold_io and their categories and tags in a spreadsheet
- [x] @amandacaster and @samtaggart decide on new tags
- [x] @amandacaster Update all newsroom posts and blog articles and send back to Timur
- [ ] @timurgordon Make sure the data gets reflected correctly

**Comment by samtaggart** [comment]
Meeting with Timur today.

**Comment by samtaggart** [comment]
Amanda and I will cross-check each others' work today and send over to Timur.

**Comment by Mik-TF** [comment]
Status? Looks done as I understand.

**Comment by samtaggart** [comment]
Yes this is done.
