### ISSUE TITLE
Edit / remove / update blogs

### ISSUE THREAD

**Issue by samtaggart** [threefoldfoundation/www_threefold_io#384]
See the plan here:

https://docs.google.com/document/d/1E6DlK69Oj_8qOuisAVB36BEFpIi1x2UizMtP96q_36s/edit#heading=h.d21ejoo502t9

**Comment by Mik-TF** [comment]
As I understand, the blog section was revised. IMO we can close this issue.

**Comment by samtaggart** [comment]
Yes done.
