### ISSUE TITLE
Landing page improvements

### ISSUE THREAD

**Issue by emilieo** [threefoldfoundation/www_threefold_io#398]
Marc feedback:

- Need to say why our cloud is the best / why it is different and better than ICP
- Need further education / graphics in simple visual terms 
- Doesn't talk about how you can earn from farming - this needs to be clear
- There is no indication that this product is already running with many participants looks new → we already have all the grid stats displayed but maybe needs to be clearer?
- No link to market price of existing coin
- Currently you need to go to the second page to understand how to become an internet service provider → would prefer some return indicators

**Comment by emilieo** [comment]
Edits made here: https://www.canva.com/design/DAGD-tXZ-48/m4tw8p9i0m7sMlDdXHt-Ng/edit?utm_content=DAGD-tXZ-48&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton

**Comment by emilieo** [comment]
Canva link: https://www.canva.com/design/DAGD-tXZ-48/m4tw8p9i0m7sMlDdXHt-Ng/edit?utm_content=DAGD-tXZ-48&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton

Update all font to Lato

Section 1: decentralized autonomous cloud
Change according to canva link above
- change title 
- change paragraph
- change picture 
- add button

Section 2: Partners
New small banner section. Add all logos as per canva

Section 3: the threefold grid 
Change according to canva link above
- change title
- change picture
- change paragraph
- change buttons

Section 4: host2earn
Change according to canva link above
- change title
- change picture
- change paragraph
- change button (1 button for now as per comment on canva)

Section 5: TFT
New section. Add as per canva link above

Section 6: Why decentralized cloud
Change according to canva link above
- title moved to left
- subtitle changed to blue

Section 7: Ecosystem
New section. Add as per canva link above. (boxes are taken from the existing design on this page: https://www.threefold.io/partners/)

Section 8: DePIN Layer Zero
New section. Add as per canva link above. 

Section 9: Latest News
Change according to canva link above
- change title
- add third column
- update pictures and text

Section 10: Join in
Keep this section the same just change the title section and change all font to Lato

**Comment by ehab-hassan** [comment]
@emilieo Can't find Section 8?
Section 8: DePIN Layer Zero
New section. Add as per the Canva link above.

**Comment by emilieo** [comment]
@ehab-hassan this section has been moved to Iteration 3 --> will update the issue now

**Comment by emilieo** [comment]
Added a new section to link to the new deploy page on this canva [link](https://www.canva.com/design/DAGD-tXZ-48/m4tw8p9i0m7sMlDdXHt-Ng/edit?utm_content=DAGD-tXZ-48&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton). 

New Section: Deploy on the grid
- Add as per the canva link above
- deploy now links to dashboard
- dive deeper links to the new deploy page

**Comment by ehab-hassan** [comment]
modification at home page 
https://docs.google.com/document/d/11T-gavVfZzjBnJWNgDlWaQVznq6aKqzMzBaO0iSzdgA/edit

**Comment by emilieo** [comment]
A few changes to be made from feedback here: https://docs.google.com/document/d/11T-gavVfZzjBnJWNgDlWaQVznq6aKqzMzBaO0iSzdgA/edit?usp=sharing

@ehab-hassan is getting a new icon for the 900+ Farms in Section 2. I am updating the third news item.
