### ISSUE TITLE
About page improvements

### ISSUE THREAD

**Issue by emilieo** [threefoldfoundation/www_threefold_io#399]
Marc feedback:

- Rather than 1.0 Internet better to see the team’s previous successes and exits - use numbers
- Show a timeline with tech evolution and make this project the continuity of the success of the other
- Our why → the global mission is ok, first why is to take the market share from GG and Amazon and bring it to shareholders who value decentralization. The look and feel are too non-profit, and not attractive from a token/ROI perspective

**Comment by emilieo** [comment]
Canva link here: https://www.canva.com/design/DAGD-tXZ-48/m4tw8p9i0m7sMlDdXHt-Ng/edit?utm_content=DAGD-tXZ-48&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton

Update all font to Lato

Section 1: founded by internet 1.0 pioneers
change according to canva link
- add button

Section 2: our story
new section. Add section according to canva link 

Section 3: 30+ years of technology development 
new section. Add section according to canva link

Section 4: Roadmap
new section. Add section according to canva link

Section 5: The team
new section. Add section according to canva link

Section 6: The vision
Can we make this squares clickable so when you click on one it will flip around and show the text as per the slides on canva? (the 5 vision slides show this - would just be one section but created 4 more to show the right text when you click it)

**Comment by ehab-hassan** [comment]
all done
@emilieo 
Some comments 
I think the vision section needs to be at the top maybe after our story
I need images of vision without rounded corners.

**Comment by emilieo** [comment]
Amendments being made by @ehab-hassan based on feedback here: https://docs.google.com/document/d/11T-gavVfZzjBnJWNgDlWaQVznq6aKqzMzBaO0iSzdgA/edit?usp=sharing
