### ISSUE TITLE
Utilization page improvements

### ISSUE THREAD

**Issue by emilieo** [threefoldfoundation/www_threefold_io#400]
Marc feedback: 

- Looks patchworky
- Many different components building with ThreeFold → building on what, with / on top of the network. This is unclear 
- The ecosystem map of who is using the tech should be on the landing page to show traction → an ecosystem map → we already show the partners on the landing page but maybe can be explained better - currently no explanation
- Lacking a roadmap in the development of this ecosystem → Marion and I have created a roadmap for the about page - check if this is okay or needs to be altered based on this new feedback (roadmap here: https://www.canva.com/design/DAGCrrCGHhE/fdeSOR977YZm-7pMF5qkRg/edit?utm_content=DAGCrrCGHhE&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton)

**Comment by emilieo** [comment]
Canva link here: https://www.canva.com/design/DAGD-tXZ-48/m4tw8p9i0m7sMlDdXHt-Ng/edit?utm_content=DAGD-tXZ-48&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton

Section 1: Utilization and ecosystem
Change according to canva link
- switch picture and text position
- update title colour 
- add subtitle
- change picture

Section 2: building with threefold
change design according to canva link (could use the element / design from this page? https://www.threefold.io/partners/)
- change subtitle colour

Section 3: Community utilization
Change according to canva link
- switch picture and text
- add subtitle
- change title colour
- make background grey
- change picture
- update text
- change colours of buttons and their layout on page

**Comment by ehab-hassan** [comment]
@emilieo how many partners do we have 6 or 7?

also, this part is not clear to me
![image](https://github.com/threefoldfoundation/www_threefold_io/assets/10484295/7386ab42-b1ac-4452-9ea9-cbf5cff04fa3)

**Comment by ehab-hassan** [comment]
that is what done for now

![image](https://github.com/threefoldfoundation/www_threefold_io/assets/10484295/1a610912-2120-461e-b5a9-499613f33ba5)
