### ISSUE TITLE
News/blog improvements

### ISSUE THREAD

**Issue by emilieo** [threefoldfoundation/www_threefold_io#401]
Marc feedback: 

- Can’t see a difference between both tabs. 
- Ordering AMA/next meetup, signups higher up in the visibility ranking
- Rest of the content is probably SEO
- Could do with some youtube/video action

**Comment by emilieo** [comment]
Need to get Kristof's opinion on combining these two pages. 

Need better sorting and tagging --> Sam is checking this with Timur when he is back in Znz

**Comment by Mik-TF** [comment]
We updated blog, closing for now. We can create new issue if needed.
