### ISSUE TITLE
Team page improvements

### ISSUE THREAD

**Issue by emilieo** [threefoldfoundation/www_threefold_io#402]
Marc feedback: 

- Looks like a great bunch of people but more philanthropic gathering
- We don’t know who is doing what (tech, dev, community etc.) → need to add clear job titles so know exactly what roles ppl have
- From a coinlaunch perspective there is no strong signaling of execution on ROI on invest

**Comment by emilieo** [comment]
Created issue here: https://git.ourworld.tf/tfgrid/circle_promotion/issues/154

**Comment by Mik-TF** [comment]
Team page is simpler with clear info on who is doing what. https://www.threefold.io/people/
