### ISSUE TITLE
Host page improvements

### ISSUE THREAD

**Issue by emilieo** [threefoldfoundation/www_threefold_io#405]
As per Marc's feedback have updated the host page on this canva link: https://www.canva.com/design/DAGD-tXZ-48/m4tw8p9i0m7sMlDdXHt-Ng/edit?utm_content=DAGD-tXZ-48&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton

- [x] Section 1: host the cloud, empower human potential
change as per the canva link
- placement of different elements quite different
- new picture
- change text
- add button

- [x] Section 2: how it works
change as per the canva link
- replace pictures 
- change colour of button
- change colour of subtitle
- change background colour to white

- [x] Section 3: kickstart your journey
- change background colour to grey
- update subtitle colour
- update button style and colour

- [x] Section 4: dashboard
- change colour of title
- change colour of text
- change image
- add button (change colours)

- [x] Section 5: for people for the planet for you
no changes to this section

**Comment by ehab-hassan** [comment]
![image](https://github.com/threefoldfoundation/www_threefold_io/assets/10484295/316fce85-f0dc-4028-a9a3-e041baf71f4c)
this section structure doesn't make sense maybe add img at the right and text at the left or center all and put img at the top.

**Comment by ehab-hassan** [comment]
done, just update the issue with links of the new buttons
![image](https://github.com/threefoldfoundation/www_threefold_io/assets/10484295/9b5c6cf6-456c-433d-9644-cf26cdd16265)
