### ISSUE TITLE
Add Deploy Page

### ISSUE THREAD

**Issue by emilieo** [threefoldfoundation/www_threefold_io#410]
Add the Deploy Page on this canva link: https://www.canva.com/design/DAGD-tXZ-48/m4tw8p9i0m7sMlDdXHt-Ng/edit

Add a Deploy button to the menu bar that takes you to this page. Place it after Host.

- [x] Section 1: Deploy on the grid
- add this section as per canva link
- developer document button goes here: https://www.manual.grid.tf/documentation/developers/developers.html
- sysadmin document button goes here: https://www.manual.grid.tf/documentation/system_administrators/system_administrators.html 

- [x] Section 2: Key Features
- Add this section as per canva link
- Dive deeper button takes you here: https://manual.grid.tf/documentation/developers/developers.html

- [x] Section 3: Ready Community Applications
- Add this section as per canva link
- Learn more takes you here: https://manual.grid.tf/documentation/dashboard/deploy/applications.html?highlight=ready#
- Deploy takes you to dashboard

**Comment by ehab-hassan** [comment]
done all updated
@emilieo it ll be better if we have a source image of the hero section or other img

**Comment by emilieo** [comment]
Deploy page complete on "development_ehab_updates" branch. Closing this issue.
