### ISSUE TITLE
Add Token Page

### ISSUE THREAD

**Issue by emilieo** [threefoldfoundation/www_threefold_io#412]
Add the Token Page on this canva link: https://www.canva.com/design/DAGD-tXZ-48/m4tw8p9i0m7sMlDdXHt-Ng/edit?utm_content=DAGD-tXZ-48&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton

Add a TFT button to the menu bar that takes you to this page. Place it after Utilization.

- [x] Section 1: all transactions use one token
- Add this section as per canva link 
- Get a node button goes here: https://marketplace.3node.global/?sl=en
- How to buy TFT button goes here: https://manual.grid.tf/documentation/threefold_token/buy_sell_tft/buy_sell_tft.html

- [x] Section 2: the farming process
- Add this section as per canva link 
- Dive deeper button goes here: https://manual.grid.tf/documentation/farmers/farmers.html 

- [x] Section 3: the utilization process
- Add this section as per canva link 
- Dive deeper button goes here: https://manual.grid.tf/knowledge_base/cloud/cloud_toc.html

**Comment by ehab-hassan** [comment]
done

![image](https://github.com/threefoldfoundation/www_threefold_io/assets/10484295/b208a8ec-a862-4964-8c7a-44bb6a7fa94a)
