### ISSUE TITLE
Simplify the Nav Bar

### ISSUE THREAD

**Issue by emilieo** [threefoldfoundation/www_threefold_io#413]
Under 'development_ehab_updates' let's add a new item in the nav bar called 'Info' and then have it as a click-down button which includes News, Blog, People and Documentation. 

See similar example from ourworld website below:

<img width="1311" alt="Screenshot 2024-05-29 at 09 57 21" src="https://github.com/threefoldfoundation/www_threefold_io/assets/72612369/b922946d-6e97-4646-89eb-ceccaa5712bd">

**Comment by ehab-hassan** [comment]
done updated at my branch
