### ISSUE TITLE
Broken Image - Newsroom page

### ISSUE THREAD

**Issue by amandacaster** [threefoldfoundation/www_threefold_io#414]
The image for may_community_discussion_v4 is broken on the dev branch. On VScode it seems correct

![image](https://github.com/threefoldfoundation/www_threefold_io/assets/88147124/015ae4b2-9ed1-419c-8090-1bbb83a9d6f9)

Sam checked it locally and the image is seen. We tried changing the image name but it still does not work. 

![image](https://github.com/threefoldfoundation/www_threefold_io/assets/88147124/ab639dec-b02f-49f4-b03a-e6081e0ff912)

**Comment by ehab-hassan** [comment]
fixed, try to avoid capital letters with naming that happen because of "V4" at image name 
![image](https://github.com/threefoldfoundation/www_threefold_io/assets/10484295/feab6949-e79d-4c1f-8e87-5c28d94202f3)

**Comment by amandacaster** [comment]
Thanks @ehab-hassan!
