### ISSUE TITLE
TF_IO: Update main partners featured on threefold.io

### ISSUE THREAD

**Issue by samtaggart** [threefoldfoundation/www_threefold_io#42]
1. HPE
2. Solidaridad
3. CasperLabs
4. DigiByte
5. Dash
6. TAG

Here is CasperLabs logo:
<img width="1000" alt="casper-logo-symbol-red" src="https://user-images.githubusercontent.com/50134479/113762458-4444b300-9721-11eb-8df2-1431f8181c00.png">

**Comment by samtaggart** [comment]
@Vilnite Looks good, only thing is can we replace Green Edge with Tag? GE is still listed there.

**Comment by Vilnite** [comment]
Ahh, my bad, didn't spot that

**Comment by samtaggart** [comment]
Great!
