### ISSUE TITLE
Create customized error 404 page

### ISSUE THREAD

**Issue by samtaggart** [threefoldfoundation/www_threefold_io#427]
We will be removing some content over the next days from blog and newsroom, some of which has been communicated or shared externally in the past. We want to make sure people have a better experience than just "this threefold.io page cannot be found" (see screenshot).

<img width="1421" alt="Screenshot 2024-06-25 at 10 37 39" src="https://github.com/threefoldfoundation/www_threefold_io/assets/50134479/34634e48-a78d-4e4a-934b-4f7e88d33cbf">

Please replace any 404 / broken page with something new.

**Comment by samtaggart** [comment]
Let's try something like this, open to ideas to make it more playful (e.g. with an image).

![You seem to have ended up on a missing page](https://github.com/threefoldfoundation/www_threefold_io/assets/50134479/66883dc8-bc3c-403d-8c62-21fd614c6aa5)

**Comment by samtaggart** [comment]
## You seem to have ended up on a missing page!

This could mean that you’ve entered the wrong URL or you’ve clicked on content which has moved locations or is no longer live. If you need assistance, click on the blue chat icon at the bottom of the screen to speak with real humans on our support team. Or go back to [home](https://threefold.io/).

**Comment by samtaggart** [comment]
Need help from someone on the web team for this one.

**Comment by ehab-hassan** [comment]
worked locally but not at development @samaradel can u check

**Comment by samtaggart** [comment]
Hi @ehab-hassan @samaradel Is there any update here?

**Comment by ehab-hassan** [comment]
> Hi @ehab-hassan @samaradel Is there any update here?

Not yet still investigating why not working at staging

**Comment by samtaggart** [comment]
OK no problem. @samaradel hopefully you can figure out the solution on Sunday so we can close the project but let's see.

**Comment by ehab-hassan** [comment]
![image](https://github.com/threefoldfoundation/www_threefold_io/assets/10484295/4b7d2dab-67b9-4a26-be94-fd84fc02e1b0)
@samtaggart fixed at staging please Check

**Comment by samtaggart** [comment]
Amazing, well done.
