### ISSUE TITLE
Remove mention of TFT as utility token 

### ISSUE THREAD

**Issue by Mik-TF** [threefoldfoundation/www_threefold_io#428]
# Todo

- Remove mention of TFT as utility token
    - 1 token does not give you a fixed amount of compute or storage.  

# Notes

- At minimum, We have to say is "similar to a utility token".

**Comment by samtaggart** [comment]
Where do we say this on the website?

**Comment by Mik-TF** [comment]
I'd go with a search and make sure all blogs are OK, etc.:

https://github.com/search?q=repo%3Athreefoldfoundation%2Fwww_threefold_io%20utility&type=code

**Comment by Mik-TF** [comment]
Done as I understand, with new website version.
