### ISSUE TITLE
Landing Page Improvements

### ISSUE THREAD

**Issue by amandacaster** [threefoldfoundation/www_threefold_io#432]
Sections to be added/changed, please check the canva [here](https://www.canva.com/design/DAGNLbQ_scs/Lj-ZUdgmHqZGLRZyMInIKQ/edit?utm_content=DAGNLbQ_scs&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton) for design, layout & content. For the Images please check the drive [here](https://drive.google.com/drive/folders/1NAhUjrZcvftaHmeqVN8nuTrUXztCMw4z?usp=sharing)

- [x] Add Technology Page & Tokens in the header & remove Get TFT and the email button 
![image](https://github.com/user-attachments/assets/c513ce82-bc7a-4818-b624-3e078462a50c)
- [x] Link Get A Node to the Get A Node page 
- [x] Remove Host the Cloud and Deploy button 
![image](https://github.com/user-attachments/assets/47ef9a28-3b5d-4adf-9c4b-1cd21cd7ace4)
- [x] Add section - It starts with nodes and link Get A Node to the Get A Node page and Build A Node to Host Page
![image](https://github.com/user-attachments/assets/154f4296-0110-4e7f-a1da-3a3a93ae1e18)
- [x] Add section - Project INCA intro & A base layer for DEPIN
![image](https://github.com/user-attachments/assets/51270565-b15b-4fef-b00c-20ecbc65c43d)
- [x] Add section Collaboration, Not Competition 
![image](https://github.com/user-attachments/assets/d72234af-b965-46af-80c5-566d63f437c9)
- [x] Change - Why Decentralized Cloud to Advantages of a Decentralized Cloud
![image](https://github.com/user-attachments/assets/ba9896cf-ed3e-4d05-8df2-27727d2bfae2)
- [x] Change layout, design, and content under What does it mean to be a truly Decentralized Autonomous Cloud for everyone?
![image](https://github.com/user-attachments/assets/f046f15e-5f8d-4adf-b63a-57b7b5407e82)
- [x] Change layout for Latest News 
![image](https://github.com/user-attachments/assets/a544995f-f15c-473a-8bb3-d4cad4551577)
- [x] Change the layout of Join In 
![image](https://github.com/user-attachments/assets/098342ea-2560-4970-834a-79ea43537c7e)

**Comment by ehab-hassan** [comment]
done 
u can check it locally at development_Aug_2024

![image](https://github.com/user-attachments/assets/7af74cee-d4d8-49e2-97a1-53c3e3574267)

**Comment by amandacaster** [comment]
All the above done, and pushed to dev.threefold.io, it is being reviewed now, adding comments in #445
