### ISSUE TITLE
About Page Improvement

### ISSUE THREAD

**Issue by amandacaster** [threefoldfoundation/www_threefold_io#433]
Sections to be added/changed, please check the canva [here](https://www.canva.com/design/DAGNLbQ_scs/Lj-ZUdgmHqZGLRZyMInIKQ/edit?utm_content=DAGNLbQ_scs&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton) for design, layout & content. For the Images please check the drive [here](https://drive.google.com/drive/folders/1NAhUjrZcvftaHmeqVN8nuTrUXztCMw4z?usp=sharing)

- [x] Change  Meet the Project to A Credible Alternative To Centralized Clouds
![image](https://github.com/user-attachments/assets/8376eb27-8394-4001-891f-94d31ff0952b)
Link Host the Cloud page to the Host Page and Deploy Button to the Deploy page
- [x] Change  Our Story to Rethinking The Way The Internet Works
![image](https://github.com/user-attachments/assets/e633734e-8c76-4cf2-a37d-a17860136614) 
- [x] Changes layout for the Roadmap
![image](https://github.com/user-attachments/assets/76848617-c409-4819-99ca-f54a6fd42945)
- [x] Add Our Mission & Vision
![image](https://github.com/user-attachments/assets/efaa7e66-e201-4da1-bae7-61260228ec9a)
- [x] Change content under Meet the team. 
![image](https://github.com/user-attachments/assets/08ca59b2-be36-4ba8-82db-15d3c91b48ed)
- [x] Add SIX EXITS TO DATE, MULTIPLE WORLD RECORDS above 30+ Years Of Technology Development
![image](https://github.com/user-attachments/assets/20f2c99c-1d33-47dd-bab3-0034e742b2c6)
- [x] Add section Be A Part of Our Journey 
![image](https://github.com/user-attachments/assets/ec616365-919a-4c82-9ee9-6d5e42273b43)

**Comment by ehab-hassan** [comment]
Done
![image](https://github.com/user-attachments/assets/d1480236-680b-4d8d-916d-75ded15b33a7)

**Comment by amandacaster** [comment]
All the above done, and pushed to dev.threefold.io, it is being reviewed now, adding comments in #445
