### ISSUE TITLE
Host Page Imporvement

### ISSUE THREAD

**Issue by amandacaster** [threefoldfoundation/www_threefold_io#435]
Sections to be added/changed, please check the canva [here](https://www.canva.com/design/DAGNLbQ_scs/Lj-ZUdgmHqZGLRZyMInIKQ/edit?utm_content=DAGNLbQ_scs&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton) for design, layout & content. For the Images please check the drive [here](https://drive.google.com/drive/folders/1NAhUjrZcvftaHmeqVN8nuTrUXztCMw4z?usp=sharing)

- [x] Add Manual button under the intro Host the Cloud, and link to the [manual](https://manual.grid.tf/) too. 
![image](https://github.com/user-attachments/assets/235997f8-96fa-41a1-820f-036589ac4de3)

**Comment by ehab-hassan** [comment]
done 

![image](https://github.com/user-attachments/assets/29520fbd-5766-44c9-ac03-ef73fe0ddd6d)

**Comment by amandacaster** [comment]
All the above done, and pushed to dev.threefold.io, it is being reviewed now, adding comments in #445
