### ISSUE TITLE
Adding Technology page 

### ISSUE THREAD

**Issue by amandacaster** [threefoldfoundation/www_threefold_io#436]
Sections to be added - please see the canva [here](https://www.canva.com/design/DAGNLbQ_scs/Lj-ZUdgmHqZGLRZyMInIKQ/edit?utm_content=DAGNLbQ_scs&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton) for the design, layout and content. For the Images please check the drive [here](https://drive.google.com/drive/folders/1NAhUjrZcvftaHmeqVN8nuTrUXztCMw4z?usp=sharing)

- [x] Add Technology to the header and remove utilization 
![image](https://github.com/user-attachments/assets/3b710396-1f3c-41e3-9381-58d4879c354a)
- [x] Add section Intro-PIONEERING A NEW ERA OF AUTONOMOUS COMPUTING
![image](https://github.com/user-attachments/assets/9a07df5a-9c62-4ce0-a681-85df4fb3f00b)
link the Dive Deeper button to the [Manual](https://manual.grid.tf/)
- [x] Add section Key Innovation- 
![image](https://github.com/user-attachments/assets/7c6d651d-39ea-49ff-a891-4c1ded984103)
Make a similar design as the box in [TF9.io](https://www.tf9.io/technology/) section "tech specification" 
![image](https://github.com/user-attachments/assets/ab62382d-9075-4d19-aa14-1ea80bca6389)
- [x] Add section What's Possible with ThreeFold 
![image](https://github.com/user-attachments/assets/59a0e826-46cd-4191-a7fd-0e4e62d0b989)
Link Deploy now to https://dashboard.grid.tf and Dive Deeper to https://manual.grid.tf/documentation/dashboard/deploy/deploy.html

**Comment by ehab-hassan** [comment]
done

![image](https://github.com/user-attachments/assets/78771d88-29a3-499d-a63a-133b96e0e53b)

**Comment by amandacaster** [comment]
All the above done, and pushed to dev.threefold.io, it is being reviewed now, adding comments in #445
