### ISSUE TITLE
TFT Page Improvement

### ISSUE THREAD

**Issue by amandacaster** [threefoldfoundation/www_threefold_io#437]
Sections to be added/changed,  please check the canva [here](https://www.canva.com/design/DAGNLbQ_scs/Lj-ZUdgmHqZGLRZyMInIKQ/edit?utm_content=DAGNLbQ_scs&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton) for design, layout & content. For the Images please check the drive [here](https://drive.google.com/drive/folders/1NAhUjrZcvftaHmeqVN8nuTrUXztCMw4z?usp=sharing)

- [x] Change the header from TFT to Tokens
![image](https://github.com/user-attachments/assets/ed3bb1bd-628b-4abb-b909-1ce6cb44a5e0)
- [x] Change the Title and content under Medium of Exchange
![image](https://github.com/user-attachments/assets/cceb02ab-c9d2-47fa-a7bd-4e2bf39c43c5)
Link the Buy token button to https://manual.grid.tf/documentation/threefold_token/threefold_token.html#buy-and-sell-tft
- [x] Add the farming process under Earn, link the Become a farmer button to https://manual.grid.tf/documentation/farmers/farmers.html
![image](https://github.com/user-attachments/assets/7f0f7a45-9470-4216-9839-9fc52a185743)
- [x] Add the utilization, link the Deploy button to the deploy page
![image](https://github.com/user-attachments/assets/eb3f21a3-dfab-42b5-8d67-99a6942ab9c6)
- [x] Add section Two Tokens to Enable One Bold Vision - Explain TFT & INCA
![image](https://github.com/user-attachments/assets/352adf68-611d-40dc-b46f-0f04922d2133)
- [x] Add section Common questions and link the Ask questions to https://forum.threefold.io/
![image](https://github.com/user-attachments/assets/57da97e0-8566-4227-a64f-c7866d5b6451)

**Comment by ehab-hassan** [comment]
done 

![image](https://github.com/user-attachments/assets/8556963a-73f3-4621-95d5-d6c5b4bb5fda)

**Comment by amandacaster** [comment]
All the above done, and pushed to dev.threefold.io, it is being reviewed now, adding comments in #445
