### ISSUE TITLE
Add Get a Node Page

### ISSUE THREAD

**Issue by amandacaster** [threefoldfoundation/www_threefold_io#438]
Sections to be added/changed, please check the canva [here](https://www.canva.com/design/DAGNLbQ_scs/Lj-ZUdgmHqZGLRZyMInIKQ/edit?utm_content=DAGNLbQ_scs&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton) for design, layout & content. For the Images please check the drive [here](https://drive.google.com/drive/folders/1NAhUjrZcvftaHmeqVN8nuTrUXztCMw4z?usp=sharing). 

**_Please create the page do not push it live/masters for now, let it be in the development branch._**

- [x] Add section Farming -Become a Cloud Provider
![image](https://github.com/user-attachments/assets/fbf138d5-fffc-4e31-91af-bc7cc926a00d)
- [x] Add section Node pricing - Use layout from [https://internetcapacity.org/farming/](https://www.canva.com/link?target=https%3A%2F%2Finternetcapacity.org%2Ffarming%2F&design=DAGNLbQ_scs&accessRole=editor&linkSource=comment) - but without mentioning INCA + the buttons link to [https://csnkyhwp8b4.typeform.com/to/SnfEE9pj](https://www.canva.com/link?target=https%3A%2F%2Fcsnkyhwp8b4.typeform.com%2Fto%2FSnfEE9pj&design=DAGNLbQ_scs&accessRole=editor&linkSource=comment)
![image](https://github.com/user-attachments/assets/b3355322-4761-4cc5-a2c4-1a7465c22d6a)
- [x] Add section Nodes Leading at the Edge 
![image](https://github.com/user-attachments/assets/f571c49c-aa65-44e2-9b51-08a0397aef6a)

**Comment by ehab-hassan** [comment]
done

**Comment by amandacaster** [comment]
All the above done, and pushed to dev.threefold.io, it is being reviewed now, adding comments in #445
