### ISSUE TITLE
title uppercase for dev.threefold.io

### ISSUE THREAD

**Issue by Mik-TF** [threefoldfoundation/www_threefold_io#446]
# todo

- make it uppercase
![image](https://github.com/user-attachments/assets/bd1fd2b5-4913-4ddc-9edc-b7fd12d676bb)

What's New?

- It Starts with Nodes
![image](https://github.com/user-attachments/assets/bd495dc5-711a-4874-807f-8ee71f70289a)

- Become a Cloud & Internet Service Provider on
![image](https://github.com/user-attachments/assets/c114ffdb-33c9-4413-af20-723d561b1521)

**Comment by samtaggart** [comment]
I am handling this at the moment.
