### ISSUE TITLE
Standardize sizing of "advantages" icons on homepage

### ISSUE THREAD

**Issue by samtaggart** [threefoldfoundation/www_threefold_io#447]
Marion provided new icons with a slightly different color and when I uploaded them they are not showing up as the same size. @ehab-hassan can you help please?

<img width="1384" alt="Screenshot 2024-08-21 at 15 08 28" src="https://github.com/user-attachments/assets/05b8cfa9-81d8-4e7d-b55a-cf6d3713c8de">

**Comment by ehab-hassan** [comment]
@marionrvrn When you provide an image make sure it is cropped there a lot of white space must be all like an attachment 
![green](https://github.com/user-attachments/assets/038e1a62-ed03-4d88-b817-c2bd26c6c678)

**Comment by marionrvrn** [comment]
@ehab-hassan done, let me know if that's work for you now https://drive.google.com/drive/u/0/folders/18xl5mX5tOjhRuTDY233sS1vkLzkCGhWn

**Comment by ehab-hassan** [comment]
@samtaggart @marionrvrn can you check at development 
Did it need to be a bit smaller?

**Comment by samtaggart** [comment]
Yes @ehab-hassan we both think they need to be a bit smaller ...
