### ISSUE TITLE
Metadata update on all pages.

### ISSUE THREAD

**Issue by amandacaster** [threefoldfoundation/www_threefold_io#457]
We need to update the metadata on all the pages on the website as it is throwing 404 errors when we use the line checker. 

For example 

![image](https://github.com/user-attachments/assets/0fbe2d3b-dd71-41fe-8e76-2c2b6f69d513)

We do not have a header_new.jpeg image(Error 404 -> https://www.threefold.io/home/header_new.jpeg) on the masters branch, however we do have header_new.png
![image](https://github.com/user-attachments/assets/b08a59fb-46dd-4a20-a5ac-351921c3baec)

Will be creating issues for each page with the description and the correct image to attach.

**Comment by amandacaster** [comment]
##### Home page
**Description**: ThreeFold empowers anyone to become a cloud service provider – no technical expertise required – allowing people and organizations to buy, sell, and use cloud resources autonomously and securely.
**Image**: 
![home page section 1](https://github.com/user-attachments/assets/3cd4fbdf-7ec3-4713-9339-1f5feeaaf692)
##### About Page
**Description**: Our mission is to empower individuals and organizations with secure, private, and
autonomous access to computing resources, ensuring fair cloud access for everyone.
**Image**: 
![about page section 1](https://github.com/user-attachments/assets/2da84a44-6fac-47c1-9904-cbca83e759f3)
##### Technology Page
**Description**: Our unique technology enables a system that can scale to a planetary level and store data that can never be corrupted or lost. 
**Image**:
![tech page section 1](https://github.com/user-attachments/assets/4fd56fe6-06de-4b30-8fa6-6a5bbc54ab7a)
##### Host Page
**Description**: Anyone can now become a cloud service provider, bringing local capacity to where people need it most while earning for your contributions. 
**Image**: 
![host section 1](https://github.com/user-attachments/assets/88b9825a-a4f9-4cd1-a333-5c27616dd38c)
##### Deploy Page
**Description**: ThreeFold has developed extensive technology and tools for developers and system administrators.
**Image**: 
![DEPLOY SECTION 1](https://github.com/user-attachments/assets/b95479f0-1aea-4236-bad3-a6f770f27304)
 ##### Utilization Page
**Description**: ThreeFold’s decentralized autonomous cloud is in its third generation and ready to go commercial.
**Image**: 
![TF Website - Iteration 2 (32)](https://github.com/user-attachments/assets/6f74dfb8-8146-4513-bc42-a1f06f446d68)
##### Tokens Page
**Description**: ThreeFold, tokens are vital for facilitating peer-to-peer transactions between participants and catalyzing the growth of the ecosystem.
**Image**: 
![threefold io -2](https://github.com/user-attachments/assets/db060c2a-07d2-4555-b906-51c2e33887b3)

**Comment by samtaggart** [comment]
Still to add:

- [ ] Get a Node
- [ ] Newsroom
- [ ] Blog
- [ ] People
- [ ] Partners
- [ ] Community

**Comment by ehab-hassan** [comment]
Fixed at telegram, Facebook, X, Linkedin

![image](https://github.com/user-attachments/assets/370cc6dd-90c9-4b16-8a9b-3445d3c3325f)
![image](https://github.com/user-attachments/assets/627b82d1-8580-44ac-9637-3a5ea2f617b4)
![image](https://github.com/user-attachments/assets/c294201a-2e65-44af-80b2-fdfcba59aba1)
![image](https://github.com/user-attachments/assets/949be629-6588-4476-8993-0fa001e5ac5d)

**Comment by ehab-hassan** [comment]
@amandacaster send me text for the rest of pages

**Comment by amandacaster** [comment]
- [ ] ##### Get a Node Page
**Description**: Becoming a host involves providing compute, storage, and network resources to the grid
**Image**: 
![get a node section 1](https://github.com/user-attachments/assets/ce874841-df2c-4249-8c9f-91250d000cb5)

- [ ] ##### People Page
**Description**: We are a passionate group on a collective mission to improve the world for the people around us.
**Image**: 
![photo_2024-09-18_12-31-45](https://github.com/user-attachments/assets/9b976454-fcfc-4e95-a447-bd7ad6706b4d)

- [ ] #### Partners
**Description**:  Meet the core projects we are working with to drive utilization of the ThreeFold Grid.
**Image**:  
![TF Website - Iteration 2 (32)](https://github.com/user-attachments/assets/0dcf78c0-ed74-45bb-ac90-c83eeec2f9b9)

- [ ] ##### Newsroom  Page
**Description**: Check the latest updates on how we are building a more open, decentralized, and scalable internet for everyone.
**Image**: 
![newsroom_metadata](https://github.com/user-attachments/assets/3b76912f-64ed-4c80-a6fd-de4893d9dd08)

- [ ] ##### Blogs Page
**Description**: Dive in to read more of our stories, our past, our present, and our future. We envision a global, community-driven network of interconnected servers and nodes—the grid—that democratizes computing power and storage.
**Image**: 
![blog_metadata](https://github.com/user-attachments/assets/fa2845b0-4d31-4e2e-9c65-a41d353c41c0)

- [ ] ##### Community
**Description**: Join the Community
**Image**: 
![community_metadata](https://github.com/user-attachments/assets/53649943-7361-4886-a0ea-9a441f252b55)

**Comment by ehab-hassan** [comment]
@samtaggart @amandacaster, everything works fine except the people page image. I have no idea why 
So I think we can close this issue and create new one for just the People page and make blocked for now?

**Comment by amandacaster** [comment]
Thanks @Ehab! Will do that.
