### ISSUE TITLE
Metadata for the People page

### ISSUE THREAD

**Issue by amandacaster** [threefoldfoundation/www_threefold_io#469]
@Ehab has been working on the metadata for all the pages in issue #457, all the pages is working fine, except the people page.  

He will be investigating the issue in this ticket. 

Description: We are a passionate group on a collective mission to improve the world for the people around us.
Image:
![image](https://github.com/user-attachments/assets/79b16538-1d18-46e1-a008-4c305792f457)

Closing issue #457

**Comment by Mik-TF** [comment]
Status? @ehab-hassan is this still relevant? I think we might be able to close the issue since we update the people page. Thanks.

**Comment by ehab-hassan** [comment]
Yes will close it
