### ISSUE TITLE
Updates to people page

### ISSUE THREAD

**Issue by samtaggart** [threefoldfoundation/www_threefold_io#473]
- [x] We got rid of biographies for now because there were too many inconsistencies and it looks unprofessional. Plus it is a lot of maintenance. So, for now, let's please make it so you cannot click into the individual profiles of people.
- [x] Can we HIDE filter for now, we may re-introduce but for now it is not necessary

@ehab-hassan Can you help here?

<img width="1110" alt="Screenshot 2024-09-25 at 13 13 13" src="https://github.com/user-attachments/assets/eb3dfc9f-1e42-4586-82b4-86b69463d53c">

**Comment by samtaggart** [comment]
@Mik-TF Yes this is for later ...

**Comment by ehab-hassan** [comment]
done at development
https://dev.threefold.io/people/
