### ISSUE TITLE
Please check formatting for bulleted lists

### ISSUE THREAD

**Issue by samtaggart** [threefoldfoundation/www_threefold_io#477]
Bulleted text appears smaller than normal text. Should all be the same. cc: @ehab-hassan 

<img width="1020" alt="Screenshot 2024-09-30 at 11 06 54" src="https://github.com/user-attachments/assets/949bd972-48a3-44a3-af77-e7c9c9cf5715">

**Comment by ehab-hassan** [comment]
all the same size at development
https://dev.threefold.io/blog/hatch-podcast/

![image](https://github.com/user-attachments/assets/5a44037f-030c-4d0e-8fa9-ce12204523ff)
