### ISSUE TITLE
fix  columns - Collaboration, Innovation, Evolution section

### ISSUE THREAD

**Issue by sasha-astiadi** [threefoldfoundation/www_threefold_io#482]
<img width="1421" alt="Screenshot 2024-10-14 at 12 15 08" src="https://github.com/user-attachments/assets/9a9cbc8e-1c6f-45b0-81e3-60f7f527dd40">

- [x] make sure texts within the row/column
- [x] make sure its responsive

**Comment by sasha-astiadi** [comment]
@ehab-hassan @samtaggart pls check

**Comment by samtaggart** [comment]
This was my doing, will need @ehab-hassan to check it.

**Comment by ehab-hassan** [comment]
fixed at development

**Comment by ehab-hassan** [comment]
closed as website changed
