### ISSUE TITLE
Update partners and utilization page

### ISSUE THREAD

**Issue by marionrvrn** [threefoldfoundation/www_threefold_io#484]
Related to this issue: https://git.ourworld.tf/tfgrid/circle_promotion/issues/293

- [x] Remove homepage partner banner for now
- [x] Archive/Remove the utilization page for now (until we have clearer directions from biz dev team)

**Comment by ehab-hassan** [comment]
done at development

**Comment by ehab-hassan** [comment]
closed as website changed
