### ISSUE TITLE
Update node section

### ISSUE THREAD

**Issue by Mik-TF** [threefoldfoundation/www_threefold_io#486]
# Situation

- We are currently working with Robert to define nodes to sell for V4
- We should update the node page with the new node models

# Details

- The AI model has an error, it's 4090:

![image](https://github.com/user-attachments/assets/ec76bc16-bcbf-4abc-9e8e-91395dfbd2d1)

**Comment by ehab-hassan** [comment]
u mean RTX here?

![image](https://github.com/user-attachments/assets/5062f2d0-5ff1-4039-8985-1da9603eeb0a)

**Comment by Mik-TF** [comment]
Thanks Ehab. Sorry I never saw your reply! We can close. We removed this.
