### ISSUE TITLE
Remove low quality images on all pages

### ISSUE THREAD

**Issue by marionrvrn** [threefoldfoundation/www_threefold_io#489]
The website needs a cleaner and simpler look, let's fix the images for now

- [x] Remove the images from the HERO section of each page, as the quality of the images is not ideal-- better to do without them: see https://www.canva.com/design/DAGVyd6jCJ0/0bK_VZcKx-lCXSle7ZGw9A/edit

- [ ] Review it together to see how does it look

**Comment by ehab-hassan** [comment]
@marionrvrn all headers are updated please check at https://dev.threefold.io/

**Comment by ehab-hassan** [comment]
closed as website changed
