### ISSUE TITLE
Minimal implementation of new website in progress

### ISSUE THREAD

**Issue by timurgordon** [threefoldfoundation/www_threefold_io#491]
to implement the basics:
- picocss and minimal css all around
- markdown driven components
- simple layout

remove zola, use tech in crystallib web module.

**Comment by Mik-TF** [comment]
@xmonader said lately that we want all websites in Zola as much as possible. I don't think this issue is needed for now, nor a priority.

@timurgordon lmk what you think. I propose to close and use Zola for now.

**Comment by samtaggart** [comment]
Personally I don't think this is really needed at this point ...

**Comment by Mik-TF** [comment]
Let's focus on 12.12.24 for now. And stakeholders agreed to have all websites in zola for now.
