### ISSUE TITLE
TF_IO - the home page can be more impressive, its not in line with design

### ISSUE THREAD

**Issue by despiegk** [threefoldfoundation/www_threefold_io#52]
![image](https://user-images.githubusercontent.com/6021844/113499713-68817380-9518-11eb-985a-f0102601b59e.png)

the mockup was much nicer
the lady is way to small

it needs to be more wide, please go back to the original design from Zia

> actually the home page is less nice than it has been, the links to the subsections looks very non professional

**Comment by despiegk** [comment]
different fonts as well
why is so much hard coded in image?
why could this not be as proper HTML?

**Comment by Vilnite** [comment]
@despiegk 
Hardcoded as image is because we don't have components that would support design provided. 
If we wanna match design mockup fastest way is to put it as image.

**Comment by Vilnite** [comment]
@ehab-hassan home page header now looks a bit disproportional and un-even.

Can we make image to fill half of the top page? Like this:
<img width="1440" alt="Screenshot 2021-04-05 at 09 41 57" src="https://user-images.githubusercontent.com/20182572/113545986-d77fca80-95f3-11eb-83c1-3d349424dbd4.png">

**Comment by Vilnite** [comment]
See if we can add grey background as asked on initial mockup (ai file sent on telegram):

<img width="1102" alt="Screenshot 2021-04-05 at 11 17 06" src="https://user-images.githubusercontent.com/20182572/113554190-9a223980-9601-11eb-9718-07851dee42b4.png">

**Comment by ehab-hassan** [comment]
for gray nav and header
that ll affect at all nav bar at website,
also the tow header a home and Why page and maybe token page ll be gray background while all one components
