### ISSUE TITLE
Add WHY page

### ISSUE THREAD

**Issue by Sacha96** [threefoldfoundation/www_threefold_io#53]
main header - use image + text 

404 block - use image + text

Tackling the root issues - create new component 

achieving goals through partnerships - create new component 

internet changes lives - text + buttons 

<img width="235" alt="Screenshot 2021-04-04 at 14 02 18" src="https://user-images.githubusercontent.com/54844940/113506589-fe7fc300-9545-11eb-9423-ace997361d17.png">

**Comment by Vilnite** [comment]
Good job with a Why page :)

yet again same as home page - we need to even out header:

<img width="1440" alt="Screenshot 2021-04-05 at 09 51 33" src="https://user-images.githubusercontent.com/20182572/113546453-b23f8c00-95f4-11eb-9c0f-73d0cb649bcb.png">
