### ISSUE TITLE
TF_IO: Add Token page

### ISSUE THREAD

**Issue by Sacha96** [threefoldfoundation/www_threefold_io#54]
Zia will provide token page monday morning. this will be top priority on Monday and should be live on same day.

make sure we link to buying options - also review wiki page

make sure flow is good for 
1. experts that already know how to get tokens
2. links for newcomers too

**Comment by Vilnite** [comment]
Here's Token page mockup from Zia, please follow exact direction (ai file sent on telegram):
![REF FILE - TOKEN IO](https://user-images.githubusercontent.com/20182572/113569766-b16e2080-961b-11eb-8d0c-49fb8e782f50.png)

**Comment by Vilnite** [comment]
For product and comparison components let's not use hardcoded image approach.
Let's apply image, text and button separately!
