### ISSUE TITLE
NEWS ROOM - Only displaying items from tab"1"

### ISSUE THREAD

**Issue by maximilianrang** [threefoldfoundation/www_threefold_io#57]
https://www.threefold.io/threefold/news/3
![image](https://user-images.githubusercontent.com/61866569/113554033-b7f39c80-9609-11eb-93d6-9a0951e780ac.png)
When clicking 2,3 or 4 it does still only show tab 1s content. This needs to be fixed.

**Comment by samaradel** [comment]
It works.

content from page 3 
![image](https://user-images.githubusercontent.com/11662805/113860778-b7dcd380-97a6-11eb-8fca-fced5e24fa79.png)

content from page 1 
![image](https://user-images.githubusercontent.com/11662805/113860929-e65aae80-97a6-11eb-8e8a-448ea03b80a4.png)
