### ISSUE TITLE
Arrange partners subpage, so most exciting ones are displayed on top

### ISSUE THREAD

**Issue by maximilianrang** [threefoldfoundation/www_threefold_io#64]
https://www.threefold.io/threefold/partners

Currently the partner page is not impressive because most of the partners showing on top are not that exciting. Maybe we need a different template that fits more partners in less space. At least we need to make sure our biggest partners, especially the blockchain ones show up on top.

**Comment by Sacha96** [comment]
changing template won't happen but we will definitely re-organize to show most exciting partnerships first and remote unknown ones like covid fighters

**Comment by samtaggart** [comment]
This is already being addressed and prioritized in a different issue.
