### ISSUE TITLE
TF_IO: Edit token page buttons

### ISSUE THREAD

**Issue by Sacha96** [threefoldfoundation/www_threefold_io#66]
<img width="1194" alt="Screenshot 2021-04-18 at 15 04 54" src="https://user-images.githubusercontent.com/54844940/115146591-70ccc900-a057-11eb-9e39-b03ddff9d041.png">

please see button 2 i added in publishtools notes just need to code it thanks

**Comment by Vilnite** [comment]
@samaradel please add another button here, on token page:

<img width="1440" alt="Screenshot 2021-04-18 at 17 20 31" src="https://user-images.githubusercontent.com/20182572/115150934-3b35d900-a073-11eb-8847-4adeff7724ff.png">


Details for button (name & link) are commented out in main.md
