### ISSUE TITLE
Create Support Page

### ISSUE THREAD

**Issue by VonSub** [threefoldfoundation/www_threefold_io#71]
## Situation right now:

We have Contact us in navigation and footer that immediately opens a "mailto" info@threefold.io having all support requests going to info mail that leaves them unanswered and such...

## To Do
Let's create more detailed Support page that consists of components guiding to our FAQs, Forum, Support chat, Telegram and email. 

Combine components such as:

- [x] For FAQ's
<img width="1234" alt="Screenshot 2021-07-07 at 16 26 03" src="https://user-images.githubusercontent.com/20182572/124766950-0a619380-df40-11eb-99a6-872828e85c9d.png">

- [x] Add printscreen of updated Forum and guiding people to Forum

- [x] For remaining contacts:
<img width="1267" alt="Screenshot 2021-07-06 at 09 57 43" src="https://user-images.githubusercontent.com/20182572/124556771-5da0ec80-de41-11eb-9348-82d5dbae1764.png">

**Support & Troubleshooting:** blue chat bubble on the bottom is there for urgent support 24/7
**General Questions:** Forum 
**Farming Questions:** Farming FAQ on Forum 
**Node Shop & Orders Questions:** Node Shop FAQ on Forum
**Token Questions:** Token FAQ on Forum 
**Tester-Capacity user Questions:** Testing Telegram Group
**Token Listing Proposals:** listing@threefold.io - need to set up still.
**Press Inquiry / PR:** press@threefold.io
**Partnerships:** kristine@threefold.io
**Community support:** Telegram Main channel

- [x]  @Sacha96 check content

**Comment by Vilnite** [comment]
Layout:
![support_page](https://user-images.githubusercontent.com/20182572/125074089-80433780-e0c5-11eb-8a91-196ae6a48120.png)

**Comment by Vilnite** [comment]
Need promo team to review content and provide design (aka images).

**Comment by Sacha96** [comment]
Alright went through it and changes text

**Comment by Sacha96** [comment]
lets add threefold brands on there - tft picture, grid, tech etc.. please propose from what's used on websites

**Comment by Sacha96** [comment]
also lead add a first block like on careers page but for support :)
