### ISSUE TITLE
TB/PB missing in graphic

### ISSUE THREAD

**Issue by andhartl** [threefoldfoundation/www_threefold_io#74]
<img width="981" alt="image" src="https://user-images.githubusercontent.com/18591016/119146688-2b7f2b00-ba4b-11eb-855e-64704ff6ccd2.png">

Pls add TB to SSD and PB to HDD

**Comment by Vilnite** [comment]
I can't find where to fix this in new Farming website.

@samaradel can you please make sure text for stats SSD and HDD is updated?

![IMAGE 2021-05-24 08:58:24](https://user-images.githubusercontent.com/20182572/119298553-4da4c300-bc6e-11eb-8618-425bd6411600.jpg)

**Comment by Vilnite** [comment]
Please change data that we are pulling in from Explorer to: 
- Farms
- Capacity (HDD Storage Capacity)
- Countries

Name them exactly like that as well as keep sequence as shown above: Farms, Capacity, Countries

Thank you.
