### ISSUE TITLE
Define new navigation for .farming to be in threefold.io

### ISSUE THREAD

**Issue by Sacha96** [threefoldfoundation/www_threefold_io#77]
Description:

We need to leverage the threefold grid and farming on threefold.io as it takes a key place in new strategy.

Deliverables:
- [x] Finish threefold.io main page
- [x] Finish edits to Farming journey 
- [x] Bring new navigation

Idea:
- Add Farming, 3Node to main ways to participate
- Add more buttons on main page to lead to both

**Comment by Vilnite** [comment]
Update per this content doc: https://docs.google.com/document/d/1QHeu5OsyqDo0E-KkerD2_YZMepB4uKWyBKuua8vQDQQ/edit#

**Comment by Sacha96** [comment]
Header

1 Home (Logo)
2 TF Universe 
— Universe Home
— ThreeFold Farming
— ThreeFold Token
— ThreeFold Kube Cloud
— ThreeFold Marketplace
— Digital Twin
— Conscious Internet
— ThreeFold Tech
3 Why
4 Token
5 Participate
— Start Farming // threefold.io/farming/get_3node
— Buy the Token // https://threefold.io/token
— Test the Cloud // https://threefold.io/cloud
— Try the Marketplace // https://threefold.io/marketplace
— Build with the SDK // https://sdk.threefold.io/#/
6 Learn
— About Farming // threefold.io/farming
— How Farming works // threefold.io/farming//how_it_works
— What is TFT? // https://threefold.io/token
— Live Capacity // https://explorer.threefold.io
— What is the Internet? // https://info.threefold.io/info/threefold#/threefold__grid_intro
— Planet Positive
— Peer-to-Peer
— Data Sovereignty
— ThreeFold Glossary
7 Collaborators
— People
— Partners
— Alliance 
8 More Info
— Blog
— Newsroom
— Forum
— Contact Us

___________________________

Footer:

1. TF Universe
- Universe Home
- ThreeFold Token
- ThreeFold Farming
- ThreeFold Kube Cloud
- ThreeFold Marketplace
- Digital Twin
- Conscious Internet 
- ThreeFold Tech 

2. Participate
— Start Farming // threefold.io/farming/get_3node
— Buy the Token // https://threefold.io/token
— Test the Cloud // https://threefold.io/cloud
— Try the Marketplace // https://threefold.io/marketplace
— Build with the SDK // https://sdk.threefold.io/#/
— Testing community

3. Learn 
— About Farming // threefold.io/farming
— How Farming works // threefold.io/farming//how_it_works
— What is TFT? // https://threefold.io/token
— Live Capacity // https://explorer.threefold.io
— What is the Internet? // https://info.threefold.io/info/threefold#/threefold__grid_intro
— Planet Positive
— Peer-to-Peer
— Data Sovereignty
— ThreeFold Glossary

4. About Us

- ThreeFold
- Partners
- People 
- Blog 
- NewsRoom
- Forum 
- Contact Us

**Comment by Sacha96** [comment]
@Vilnite @ehab-hassan @samaradel
