### ISSUE TITLE
Improve resolution for website image featuring grid products

### ISSUE THREAD

**Issue by samtaggart** [threefoldfoundation/www_threefold_io#83]
![120214345-66504280-c245-11eb-83a1-fa6ad5b2b18e](https://user-images.githubusercontent.com/50134479/120268651-e1017800-c2ae-11eb-96c4-47fd08ffb7ff.png)

This image is pixelating on 4K screens. @ehab-hassan Please tell me what is needed. I believe I sent you the SVG but is that not good enough? Do you have any suggestions for how to solve?

**Comment by ehab-hassan** [comment]
yes the SVG not working with me, I used the png one because we need to go production
I sent Today To Zia to give me the ai file old version

**Comment by ehab-hassan** [comment]
fixed at development
