### ISSUE TITLE
Threefold.io - Edit solutions block 

### ISSUE THREAD

**Issue by Sacha96** [threefoldfoundation/www_threefold_io#85]
![Screenshot 2021-06-07 at 19 36 15 (2)](https://user-images.githubusercontent.com/54844940/121048321-be4bf380-c7c7-11eb-89e6-ab3a8f545b6b.png)

was requested by kds to change this block into blog format and guide to different websites

use this kind of block

![Screenshot 2021-06-07 at 19 39 35](https://user-images.githubusercontent.com/54844940/121048732-1be04000-c7c8-11eb-9144-fd18a20b1977.png)

don't show sdk

show only: 
- zerostore filesystem
- kubernetes cloud
- digital twin

and link to websites

**Comment by Sacha96** [comment]
block 1: Kubernetes Cloud

image: 
![Screenshot 2021-06-09 at 12 23 56](https://user-images.githubusercontent.com/54844940/121319769-95d60d80-c91d-11eb-810e-84482191ee94.png)

text: First Peer-to-Peer Kubernetes compatible cloud solution on the market. Comes with Docker and other developer favorites.

link: https://threefold.io/info/cloud#/cloud__evdc

block 2: Quantum-Safe Storage

image: ![Screenshot 2021-06-09 at 12 23 24](https://user-images.githubusercontent.com/54844940/121319685-81921080-c91d-11eb-9bb3-ff956b663d89.png)

text: An unbreakable Filestystem compatible with all storage protocols and tools for app data, videos, public datasets, security archives and more.

link: https://threefold.io/info/cloud#/cloud__threefold_filesystem

block 3:  Digital Twin

image: ![Screenshot 2021-06-09 at 12 21 09](https://user-images.githubusercontent.com/54844940/121319368-324be000-c91d-11eb-9fcd-172c0031d75f.png)

text: Your digital avatar that gives you access to secure and private communication, socials and office tools. 

link: https://threefold.io/info/cloud#/cloud__threefold_filesystem

**Comment by Sacha96** [comment]
take images from dt and cloud repo

**Comment by ehab-hassan** [comment]
![image](https://user-images.githubusercontent.com/10484295/121330521-6243b500-c916-11eb-8705-c5085ede9fef.png)
 done at development
 
 @Sacha96  @Vilnite  should I keep the button (Explore the ThreeFold Universe) from old section or remove it
