### ISSUE TITLE
Links update at Nav

### ISSUE THREAD

**Issue by ehab-hassan** [threefoldfoundation/www_threefold_io#87]
where(the  threefold grid) to go while we don't have about page anymore at io website?
![pic1](https://user-images.githubusercontent.com/10484295/121352462-2f58eb80-c92d-11eb-8f1e-1a6ab13a5dfb.png)

where(the  threefold grid) to go while we don't have about page anymore at io website?

also here at footer no how_it_works page anymore should remove this link at io and farming?
![footer](https://user-images.githubusercontent.com/10484295/121352721-6af3b580-c92d-11eb-8aa1-21d13f7a6c04.jpg)

**Comment by Vilnite** [comment]
It's linked correctly:
The TF Grid links to: https://threefold.io/farming (main page of farming)
How Farming works links to: https://threefold.io/farming/farming (farming page of farming)
