### ISSUE TITLE
TF UMBRELLA - update font

### ISSUE THREAD

**Issue by Vilnite** [threefoldfoundation/www_threefold_io#9]
Please update font for all website to Futura
https://www.wfonts.com/font/futura
(Futura Book font.ttf)

<img width="1023" alt="Screenshot 2021-02-11 at 10 56 37" src="https://user-images.githubusercontent.com/20182572/107617105-f434fd00-6c57-11eb-86e2-ee602d1376ea.png">

**Comment by Vilnite** [comment]
Please bring back updated font.

**Comment by ehab-hassan** [comment]
updated at staging
https://www2.threefold.io/
