### ISSUE TITLE
Add FAQ component

### ISSUE THREAD

**Issue by Vilnite** [threefoldfoundation/www_threefold_io#90]
Create and add FAQ component to:
- [x] threefold_io (after 'in the news' section on the bottom of home page)
- [x] farming (right above last cta section 'Join the ThreeFold Grid' on the bottom of home page)
- [x] examplesite (on the bottom of home page)

Please take first one:
https://tailwindui.com/components/marketing/sections/faq-sections

<img width="1170" alt="Screenshot 2021-06-14 at 10 33 30" src="https://user-images.githubusercontent.com/20182572/121855578-305a9600-ccfc-11eb-992c-4fc8512b3143.png">

**Comment by Sacha96** [comment]
BTW Shouldn't be on home page!! We just need a FAQ page!

**Comment by Vilnite** [comment]
After discussion with @Sacha96 moved FAQ section under More Info.
