### ISSUE TITLE
Website Navigation

### ISSUE THREAD

**Issue by Sacha96** [threefoldfoundation/www_threefold_io#96]
Description:

We need a better website navigation and more links to the wiki. 

Deliverables:

- [x] New navigation 

- Home = ThreeFold Logo
- Why
- Grid (dropdown)
-- Introduction > https://threefold.io/farming/
-- Start Farming > https://threefold.io/farming/farming
-- Get a 3Node > https://threefold.io/farming/get_3node
-- FAQ > https://forum.threefold.io/c/farming/farming-faq/53
- Token (dropdown)
-- Introduction > https://threefold.io/token
-- Buy TFT > https://threefold.io/info/threefold#/threefold__how_to_buy_and_sell
-- Tokenomics > https://threefold.io/info/threefold#/threefold__tokenomics
-- Distribution > https://threefold.io/info/threefold#/threefold__token_overview
-- FAQ > https://forum.threefold.io/c/threefold-token/tft-faq/57
- Use (dropdown)
-- Kubernetes Cloud > https://threefold.io/info/cloud#/cloud__evdc
-- Quantum-Safe Storage > https://threefold.io/info/cloud#/cloud__threefold_filesystem
-- Marketplace > https://threefold.io/marketplace
-- Digital Twin > https://mydigitaltwin.io/
- Technology (dropdown)
-- Web2 vs Web3 vs P2P > https://threefold.io/info/threefold#/threefold__grid_compare
-- Grid Technology > https://threefold.io/info/threefold#/internet4__zos_3node_tfgrid_intro
-- Operating system > https://threefold.io/info/threefold#/internet4__tfgrid_primitives
-- Smart Contract for IT > https://threefold.io/info/threefold#/internet4__smartcontract_it
-- P2P Network > https://threefold.io/info/threefold#/internet4__planetary_network
-- FAQ > https://forum.threefold.io/c/technical-discussion/technical-faq/55
- Collaborators (Stays Same)
- Participate (links to TF Universe home page)

<img width="1388" alt="Screenshot 2021-07-06 at 10 41 33" src="https://user-images.githubusercontent.com/20182572/124561800-f5eda000-de46-11eb-868e-a731244478f2.png">

- More Info (Stays Same)

- [x] More links to wiki (embedded in navigation)

- [x] QA with @Sacha96

**Comment by Vilnite** [comment]
More links to wiki requires to improve wiki user flow as well. Suggested changes: https://github.com/threefoldfoundation/info_threefold/issues/69
