### ISSUE TITLE
upgrade npm deps

### ISSUE THREAD

**Issue by despiegk** [threefoldfoundation/www_threefold_io#99]
![image](https://user-images.githubusercontent.com/6021844/125194269-83732a80-e261-11eb-9df6-95efe2a12a1c.png)

please update https://github.com/threefoldfoundation/www_threefold_io/blob/gitpod/gitpod/package.json

lots of old packages, need to update & test

**Comment by despiegk** [comment]
source file is now on https://github.com/threefoldfoundation/data_threefold/blob/development/gitpod_scripts/package.json

**Comment by Vilnite** [comment]
@hossnys please check if this is still relevant after latest publishtools update

**Comment by hossnys** [comment]
it's just normal warning we are good to close this , that what i got from dev team .
